// Package lite provides a lightweight terminal user interface for meept.
package lite

import (
	"fmt"
	"strings"
	"sync"

	"github.com/caimlas/meept/internal/tui"
	"github.com/caimlas/meept/internal/tui/types"
)

// SessionManager handles session-related commands.
type SessionManager struct {
	rpc            *tui.RPCClient
	currentSession *types.Session
	mu             sync.RWMutex
}

// NewSessionManager creates a new session manager.
func NewSessionManager(rpc *tui.RPCClient) *SessionManager {
	return &SessionManager{
		rpc: rpc,
	}
}

// List returns all sessions.
func (s *SessionManager) List() ([]types.Session, error) {
	resp, err := s.rpc.ListSessions()
	if err != nil {
		return nil, fmt.Errorf("failed to list sessions: %w", err)
	}
	return resp.Sessions, nil
}

// Switch switches to a session by name or ID.
// It searches for a session matching the provided nameOrID first by exact ID match,
// then by exact name match, and finally by name prefix match.
func (s *SessionManager) Switch(nameOrID string) (*types.Session, error) {
	if nameOrID == "" {
		return nil, fmt.Errorf("session name or ID required")
	}

	sessions, err := s.List()
	if err != nil {
		return nil, err
	}

	// Search in order: exact ID, exact name, name prefix
	var match *types.Session

	// First pass: exact ID match
	for i := range sessions {
		if sessions[i].ID == nameOrID {
			match = &sessions[i]
			break
		}
	}

	// Second pass: exact name match (case-insensitive)
	if match == nil {
		lowerNameOrID := strings.ToLower(nameOrID)
		for i := range sessions {
			if strings.ToLower(sessions[i].Name) == lowerNameOrID {
				match = &sessions[i]
				break
			}
		}
	}

	// Third pass: name prefix match (case-insensitive)
	if match == nil {
		lowerNameOrID := strings.ToLower(nameOrID)
		var prefixMatches []*types.Session
		for i := range sessions {
			if strings.HasPrefix(strings.ToLower(sessions[i].Name), lowerNameOrID) {
				prefixMatches = append(prefixMatches, &sessions[i])
			}
		}
		if len(prefixMatches) == 1 {
			match = prefixMatches[0]
		} else if len(prefixMatches) > 1 {
			return nil, fmt.Errorf("ambiguous session name: %q matches %d sessions", nameOrID, len(prefixMatches))
		}
	}

	// Fourth pass: ID prefix match
	if match == nil {
		var idPrefixMatches []*types.Session
		for i := range sessions {
			if strings.HasPrefix(sessions[i].ID, nameOrID) {
				idPrefixMatches = append(idPrefixMatches, &sessions[i])
			}
		}
		if len(idPrefixMatches) == 1 {
			match = idPrefixMatches[0]
		} else if len(idPrefixMatches) > 1 {
			return nil, fmt.Errorf("ambiguous session ID: %q matches %d sessions", nameOrID, len(idPrefixMatches))
		}
	}

	if match == nil {
		return nil, fmt.Errorf("session not found: %q", nameOrID)
	}

	s.SetCurrent(match)
	return match, nil
}

// Create creates a new session with optional name.
// If name is empty, a default name based on timestamp will be generated by the server.
func (s *SessionManager) Create(name string) (*types.Session, error) {
	session, err := s.rpc.CreateSession(name)
	if err != nil {
		return nil, fmt.Errorf("failed to create session: %w", err)
	}

	s.SetCurrent(session)
	return session, nil
}

// Current returns the current session.
func (s *SessionManager) Current() *types.Session {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.currentSession
}

// SetCurrent sets the current session.
func (s *SessionManager) SetCurrent(session *types.Session) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.currentSession = session
}

// LoadOrCreate loads the most recent session or creates a new one.
// This is useful for initializing the session manager at startup.
func (s *SessionManager) LoadOrCreate() (*types.Session, error) {
	// First, try to get the most recent session
	session, err := s.rpc.GetMostRecentSession()
	if err == nil && session != nil && session.ID != "" {
		s.SetCurrent(session)
		return session, nil
	}

	// No recent session found, create a new one
	return s.Create("")
}

// Delete deletes a session by ID.
// Returns an error if attempting to delete the current session.
func (s *SessionManager) Delete(sessionID string) error {
	s.mu.RLock()
	current := s.currentSession
	s.mu.RUnlock()

	if current != nil && current.ID == sessionID {
		return fmt.Errorf("cannot delete the current session")
	}

	if err := s.rpc.DeleteSession(sessionID); err != nil {
		return fmt.Errorf("failed to delete session: %w", err)
	}

	return nil
}

// GetMessages retrieves messages for the current session.
func (s *SessionManager) GetMessages(offset, limit int) ([]types.SessionMessage, int, error) {
	current := s.Current()
	if current == nil {
		return nil, 0, fmt.Errorf("no active session")
	}

	resp, err := s.rpc.GetSessionMessages(current.ID, offset, limit)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to get messages: %w", err)
	}

	return resp.Messages, resp.Total, nil
}

// SaveMessages saves messages to the current session.
func (s *SessionManager) SaveMessages(messages []types.SessionMessage) error {
	current := s.Current()
	if current == nil {
		return fmt.Errorf("no active session")
	}

	if err := s.rpc.SaveSessionMessages(current.ID, messages); err != nil {
		return fmt.Errorf("failed to save messages: %w", err)
	}

	return nil
}

// UpdateDescription updates the description of the current session.
func (s *SessionManager) UpdateDescription(description string) error {
	current := s.Current()
	if current == nil {
		return fmt.Errorf("no active session")
	}

	if err := s.rpc.UpdateSessionDescription(current.ID, description); err != nil {
		return fmt.Errorf("failed to update description: %w", err)
	}

	// Update local copy
	s.mu.Lock()
	if s.currentSession != nil {
		s.currentSession.Description = description
	}
	s.mu.Unlock()

	return nil
}

// GenerateDescription uses LLM to generate a description for the current session.
func (s *SessionManager) GenerateDescription(firstMessage, projectName string) (*types.GenerateDescriptionResult, error) {
	current := s.Current()
	if current == nil {
		return nil, fmt.Errorf("no active session")
	}

	result, err := s.rpc.GenerateSessionDescription(current.ID, firstMessage, projectName)
	if err != nil {
		return nil, fmt.Errorf("failed to generate description: %w", err)
	}

	// Update local copy with generated description
	s.mu.Lock()
	if s.currentSession != nil && result.Description != "" {
		s.currentSession.Description = result.Description
	}
	if s.currentSession != nil && result.Name != "" {
		s.currentSession.Name = result.Name
	}
	s.mu.Unlock()

	return result, nil
}

// Stop stops all work for the current session.
func (s *SessionManager) Stop() (*types.StopSessionResponse, error) {
	current := s.Current()
	if current == nil {
		return nil, fmt.Errorf("no active session")
	}

	resp, err := s.rpc.StopSession(current.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to stop session: %w", err)
	}

	return resp, nil
}

// GetChildTasks returns tasks associated with the current session.
func (s *SessionManager) GetChildTasks() ([]string, error) {
	current := s.Current()
	if current == nil {
		return nil, fmt.Errorf("no active session")
	}

	tasks, err := s.rpc.GetSessionChildTasks(current.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get child tasks: %w", err)
	}

	return tasks, nil
}

// ConversationID returns the conversation ID for the current session.
// Returns empty string if no session is active.
func (s *SessionManager) ConversationID() string {
	s.mu.RLock()
	defer s.mu.RUnlock()

	if s.currentSession == nil {
		return ""
	}
	return s.currentSession.ConversationID
}
