// Code generated by "stringer -linecomment -type=Mode -output=internal/tui/vim/mode_string.go internal/tui/vim/mode.go"; DO NOT EDIT.

package vim

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeNormal-0]
	_ = x[ModeInsert-1]
	_ = x[ModeVisual-2]
	_ = x[ModeCommand-3]
}

const _Mode_name = "NORMALINSERTVISUALCOMMAND"

var _Mode_index = [...]uint8{0, 6, 12, 18, 25}

func (i Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Mode_index)-1 {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[idx]:_Mode_index[idx+1]]
}
