/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type WebSocketAPI interface {

	/*
	GetWebSocket WebSocket connection for real-time updates

	Establishes a WebSocket connection for receiving real-time agent progress events.
Clients can subscribe to specific sessions via subscribe messages.


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetWebSocketRequest
	*/
	GetWebSocket(ctx context.Context) ApiGetWebSocketRequest

	// GetWebSocketExecute executes the request
	GetWebSocketExecute(r ApiGetWebSocketRequest) (*http.Response, error)
}

// WebSocketAPIService WebSocketAPI service
type WebSocketAPIService service

type ApiGetWebSocketRequest struct {
	ctx context.Context
	ApiService WebSocketAPI
	sessionId *string
}

// Optional session ID to filter events
func (r ApiGetWebSocketRequest) SessionId(sessionId string) ApiGetWebSocketRequest {
	r.sessionId = &sessionId
	return r
}

func (r ApiGetWebSocketRequest) Execute() (*http.Response, error) {
	return r.ApiService.GetWebSocketExecute(r)
}

/*
GetWebSocket WebSocket connection for real-time updates

Establishes a WebSocket connection for receiving real-time agent progress events.
Clients can subscribe to specific sessions via subscribe messages.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetWebSocketRequest
*/
func (a *WebSocketAPIService) GetWebSocket(ctx context.Context) ApiGetWebSocketRequest {
	return ApiGetWebSocketRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *WebSocketAPIService) GetWebSocketExecute(r ApiGetWebSocketRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "WebSocketAPIService.GetWebSocket")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/ws"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.sessionId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "session_id", r.sessionId, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
