/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UIActionDef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UIActionDef{}

// UIActionDef struct for UIActionDef
type UIActionDef struct {
	Id string `json:"id"`
	Label string `json:"label"`
	Type string `json:"type"`
	Styleomitempty *string `json:"style,omitempty,omitempty"`
}

type _UIActionDef UIActionDef

// NewUIActionDef instantiates a new UIActionDef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUIActionDef(id string, label string, type_ string) *UIActionDef {
	this := UIActionDef{}
	this.Id = id
	this.Label = label
	this.Type = type_
	return &this
}

// NewUIActionDefWithDefaults instantiates a new UIActionDef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUIActionDefWithDefaults() *UIActionDef {
	this := UIActionDef{}
	return &this
}

// GetId returns the Id field value
func (o *UIActionDef) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UIActionDef) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UIActionDef) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *UIActionDef) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *UIActionDef) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *UIActionDef) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *UIActionDef) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UIActionDef) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UIActionDef) SetType(v string) {
	o.Type = v
}

// GetStyleomitempty returns the Styleomitempty field value if set, zero value otherwise.
func (o *UIActionDef) GetStyleomitempty() string {
	if o == nil || IsNil(o.Styleomitempty) {
		var ret string
		return ret
	}
	return *o.Styleomitempty
}

// GetStyleomitemptyOk returns a tuple with the Styleomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIActionDef) GetStyleomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Styleomitempty) {
		return nil, false
	}
	return o.Styleomitempty, true
}

// HasStyleomitempty returns a boolean if a field has been set.
func (o *UIActionDef) HasStyleomitempty() bool {
	if o != nil && !IsNil(o.Styleomitempty) {
		return true
	}

	return false
}

// SetStyleomitempty gets a reference to the given string and assigns it to the Styleomitempty field.
func (o *UIActionDef) SetStyleomitempty(v string) {
	o.Styleomitempty = &v
}

func (o UIActionDef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UIActionDef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	if !IsNil(o.Styleomitempty) {
		toSerialize["style,omitempty"] = o.Styleomitempty
	}
	return toSerialize, nil
}

func (o *UIActionDef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUIActionDef := _UIActionDef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUIActionDef)

	if err != nil {
		return err
	}

	*o = UIActionDef(varUIActionDef)

	return err
}

type NullableUIActionDef struct {
	value *UIActionDef
	isSet bool
}

func (v NullableUIActionDef) Get() *UIActionDef {
	return v.value
}

func (v *NullableUIActionDef) Set(val *UIActionDef) {
	v.value = val
	v.isSet = true
}

func (v NullableUIActionDef) IsSet() bool {
	return v.isSet
}

func (v *NullableUIActionDef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUIActionDef(val *UIActionDef) *NullableUIActionDef {
	return &NullableUIActionDef{value: val, isSet: true}
}

func (v NullableUIActionDef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUIActionDef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


