/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatRequest{}

// ChatRequest struct for ChatRequest
type ChatRequest struct {
	Message string `json:"message"`
	ConversationId string `json:"conversation_id"`
	AgentIdomitempty *string `json:"agent_id,omitempty,omitempty"`
}

type _ChatRequest ChatRequest

// NewChatRequest instantiates a new ChatRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatRequest(message string, conversationId string) *ChatRequest {
	this := ChatRequest{}
	this.Message = message
	this.ConversationId = conversationId
	return &this
}

// NewChatRequestWithDefaults instantiates a new ChatRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatRequestWithDefaults() *ChatRequest {
	this := ChatRequest{}
	return &this
}

// GetMessage returns the Message field value
func (o *ChatRequest) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ChatRequest) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ChatRequest) SetMessage(v string) {
	o.Message = v
}

// GetConversationId returns the ConversationId field value
func (o *ChatRequest) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *ChatRequest) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *ChatRequest) SetConversationId(v string) {
	o.ConversationId = v
}

// GetAgentIdomitempty returns the AgentIdomitempty field value if set, zero value otherwise.
func (o *ChatRequest) GetAgentIdomitempty() string {
	if o == nil || IsNil(o.AgentIdomitempty) {
		var ret string
		return ret
	}
	return *o.AgentIdomitempty
}

// GetAgentIdomitemptyOk returns a tuple with the AgentIdomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatRequest) GetAgentIdomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.AgentIdomitempty) {
		return nil, false
	}
	return o.AgentIdomitempty, true
}

// HasAgentIdomitempty returns a boolean if a field has been set.
func (o *ChatRequest) HasAgentIdomitempty() bool {
	if o != nil && !IsNil(o.AgentIdomitempty) {
		return true
	}

	return false
}

// SetAgentIdomitempty gets a reference to the given string and assigns it to the AgentIdomitempty field.
func (o *ChatRequest) SetAgentIdomitempty(v string) {
	o.AgentIdomitempty = &v
}

func (o ChatRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	toSerialize["conversation_id"] = o.ConversationId
	if !IsNil(o.AgentIdomitempty) {
		toSerialize["agent_id,omitempty"] = o.AgentIdomitempty
	}
	return toSerialize, nil
}

func (o *ChatRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"conversation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatRequest := _ChatRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatRequest)

	if err != nil {
		return err
	}

	*o = ChatRequest(varChatRequest)

	return err
}

type NullableChatRequest struct {
	value *ChatRequest
	isSet bool
}

func (v NullableChatRequest) Get() *ChatRequest {
	return v.value
}

func (v *NullableChatRequest) Set(val *ChatRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChatRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChatRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatRequest(val *ChatRequest) *NullableChatRequest {
	return &NullableChatRequest{value: val, isSet: true}
}

func (v NullableChatRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


