/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForkSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForkSessionRequest{}

// ForkSessionRequest struct for ForkSessionRequest
type ForkSessionRequest struct {
	SessionId string `json:"session_id"`
	FromMessageId int32 `json:"from_message_id"`
	Nameomitempty *string `json:"name,omitempty,omitempty"`
}

type _ForkSessionRequest ForkSessionRequest

// NewForkSessionRequest instantiates a new ForkSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForkSessionRequest(sessionId string, fromMessageId int32) *ForkSessionRequest {
	this := ForkSessionRequest{}
	this.SessionId = sessionId
	this.FromMessageId = fromMessageId
	return &this
}

// NewForkSessionRequestWithDefaults instantiates a new ForkSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForkSessionRequestWithDefaults() *ForkSessionRequest {
	this := ForkSessionRequest{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *ForkSessionRequest) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *ForkSessionRequest) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *ForkSessionRequest) SetSessionId(v string) {
	o.SessionId = v
}

// GetFromMessageId returns the FromMessageId field value
func (o *ForkSessionRequest) GetFromMessageId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FromMessageId
}

// GetFromMessageIdOk returns a tuple with the FromMessageId field value
// and a boolean to check if the value has been set.
func (o *ForkSessionRequest) GetFromMessageIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromMessageId, true
}

// SetFromMessageId sets field value
func (o *ForkSessionRequest) SetFromMessageId(v int32) {
	o.FromMessageId = v
}

// GetNameomitempty returns the Nameomitempty field value if set, zero value otherwise.
func (o *ForkSessionRequest) GetNameomitempty() string {
	if o == nil || IsNil(o.Nameomitempty) {
		var ret string
		return ret
	}
	return *o.Nameomitempty
}

// GetNameomitemptyOk returns a tuple with the Nameomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForkSessionRequest) GetNameomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Nameomitempty) {
		return nil, false
	}
	return o.Nameomitempty, true
}

// HasNameomitempty returns a boolean if a field has been set.
func (o *ForkSessionRequest) HasNameomitempty() bool {
	if o != nil && !IsNil(o.Nameomitempty) {
		return true
	}

	return false
}

// SetNameomitempty gets a reference to the given string and assigns it to the Nameomitempty field.
func (o *ForkSessionRequest) SetNameomitempty(v string) {
	o.Nameomitempty = &v
}

func (o ForkSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForkSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_id"] = o.SessionId
	toSerialize["from_message_id"] = o.FromMessageId
	if !IsNil(o.Nameomitempty) {
		toSerialize["name,omitempty"] = o.Nameomitempty
	}
	return toSerialize, nil
}

func (o *ForkSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
		"from_message_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForkSessionRequest := _ForkSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForkSessionRequest)

	if err != nil {
		return err
	}

	*o = ForkSessionRequest(varForkSessionRequest)

	return err
}

type NullableForkSessionRequest struct {
	value *ForkSessionRequest
	isSet bool
}

func (v NullableForkSessionRequest) Get() *ForkSessionRequest {
	return v.value
}

func (v *NullableForkSessionRequest) Set(val *ForkSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableForkSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableForkSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForkSessionRequest(val *ForkSessionRequest) *NullableForkSessionRequest {
	return &NullableForkSessionRequest{value: val, isSet: true}
}

func (v NullableForkSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForkSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


