/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRequest{}

// GetRequest struct for GetRequest
type GetRequest struct {
	JobId string `json:"job_id"`
}

type _GetRequest GetRequest

// NewGetRequest instantiates a new GetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRequest(jobId string) *GetRequest {
	this := GetRequest{}
	this.JobId = jobId
	return &this
}

// NewGetRequestWithDefaults instantiates a new GetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRequestWithDefaults() *GetRequest {
	this := GetRequest{}
	return &this
}

// GetJobId returns the JobId field value
func (o *GetRequest) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *GetRequest) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *GetRequest) SetJobId(v string) {
	o.JobId = v
}

func (o GetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	return toSerialize, nil
}

func (o *GetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRequest := _GetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRequest)

	if err != nil {
		return err
	}

	*o = GetRequest(varGetRequest)

	return err
}

type NullableGetRequest struct {
	value *GetRequest
	isSet bool
}

func (v NullableGetRequest) Get() *GetRequest {
	return v.value
}

func (v *NullableGetRequest) Set(val *GetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRequest(val *GetRequest) *NullableGetRequest {
	return &NullableGetRequest{value: val, isSet: true}
}

func (v NullableGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


