/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RetryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RetryRequest{}

// RetryRequest struct for RetryRequest
type RetryRequest struct {
	JobId string `json:"job_id"`
}

type _RetryRequest RetryRequest

// NewRetryRequest instantiates a new RetryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRetryRequest(jobId string) *RetryRequest {
	this := RetryRequest{}
	this.JobId = jobId
	return &this
}

// NewRetryRequestWithDefaults instantiates a new RetryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRetryRequestWithDefaults() *RetryRequest {
	this := RetryRequest{}
	return &this
}

// GetJobId returns the JobId field value
func (o *RetryRequest) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *RetryRequest) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *RetryRequest) SetJobId(v string) {
	o.JobId = v
}

func (o RetryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RetryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	return toSerialize, nil
}

func (o *RetryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRetryRequest := _RetryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRetryRequest)

	if err != nil {
		return err
	}

	*o = RetryRequest(varRetryRequest)

	return err
}

type NullableRetryRequest struct {
	value *RetryRequest
	isSet bool
}

func (v NullableRetryRequest) Get() *RetryRequest {
	return v.value
}

func (v *NullableRetryRequest) Set(val *RetryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRetryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRetryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRetryRequest(val *RetryRequest) *NullableRetryRequest {
	return &NullableRetryRequest{value: val, isSet: true}
}

func (v NullableRetryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRetryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


