/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelTaskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelTaskRequest{}

// CancelTaskRequest struct for CancelTaskRequest
type CancelTaskRequest struct {
	Id string `json:"id"`
}

type _CancelTaskRequest CancelTaskRequest

// NewCancelTaskRequest instantiates a new CancelTaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelTaskRequest(id string) *CancelTaskRequest {
	this := CancelTaskRequest{}
	this.Id = id
	return &this
}

// NewCancelTaskRequestWithDefaults instantiates a new CancelTaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelTaskRequestWithDefaults() *CancelTaskRequest {
	this := CancelTaskRequest{}
	return &this
}

// GetId returns the Id field value
func (o *CancelTaskRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CancelTaskRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CancelTaskRequest) SetId(v string) {
	o.Id = v
}

func (o CancelTaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelTaskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CancelTaskRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelTaskRequest := _CancelTaskRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelTaskRequest)

	if err != nil {
		return err
	}

	*o = CancelTaskRequest(varCancelTaskRequest)

	return err
}

type NullableCancelTaskRequest struct {
	value *CancelTaskRequest
	isSet bool
}

func (v NullableCancelTaskRequest) Get() *CancelTaskRequest {
	return v.value
}

func (v *NullableCancelTaskRequest) Set(val *CancelTaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelTaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelTaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelTaskRequest(val *CancelTaskRequest) *NullableCancelTaskRequest {
	return &NullableCancelTaskRequest{value: val, isSet: true}
}

func (v NullableCancelTaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelTaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


