/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the SessionService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionService{}

// SessionService struct for SessionService
type SessionService struct {
	Store map[string]interface{} `json:"store,omitempty"`
}

// NewSessionService instantiates a new SessionService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionService() *SessionService {
	this := SessionService{}
	return &this
}

// NewSessionServiceWithDefaults instantiates a new SessionService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionServiceWithDefaults() *SessionService {
	this := SessionService{}
	return &this
}

// GetStore returns the Store field value if set, zero value otherwise.
func (o *SessionService) GetStore() map[string]interface{} {
	if o == nil || IsNil(o.Store) {
		var ret map[string]interface{}
		return ret
	}
	return o.Store
}

// GetStoreOk returns a tuple with the Store field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionService) GetStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Store) {
		return map[string]interface{}{}, false
	}
	return o.Store, true
}

// HasStore returns a boolean if a field has been set.
func (o *SessionService) HasStore() bool {
	if o != nil && !IsNil(o.Store) {
		return true
	}

	return false
}

// SetStore gets a reference to the given map[string]interface{} and assigns it to the Store field.
func (o *SessionService) SetStore(v map[string]interface{}) {
	o.Store = v
}

func (o SessionService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Store) {
		toSerialize["store"] = o.Store
	}
	return toSerialize, nil
}

type NullableSessionService struct {
	value *SessionService
	isSet bool
}

func (v NullableSessionService) Get() *SessionService {
	return v.value
}

func (v *NullableSessionService) Set(val *SessionService) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionService) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionService(val *SessionService) *NullableSessionService {
	return &NullableSessionService{value: val, isSet: true}
}

func (v NullableSessionService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


