/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetMessagesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMessagesRequest{}

// GetMessagesRequest struct for GetMessagesRequest
type GetMessagesRequest struct {
	Id string `json:"id"`
	Offsetomitempty *int32 `json:"offset,omitempty,omitempty"`
	Limitomitempty *int32 `json:"limit,omitempty,omitempty"`
}

type _GetMessagesRequest GetMessagesRequest

// NewGetMessagesRequest instantiates a new GetMessagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMessagesRequest(id string) *GetMessagesRequest {
	this := GetMessagesRequest{}
	this.Id = id
	return &this
}

// NewGetMessagesRequestWithDefaults instantiates a new GetMessagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMessagesRequestWithDefaults() *GetMessagesRequest {
	this := GetMessagesRequest{}
	return &this
}

// GetId returns the Id field value
func (o *GetMessagesRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetMessagesRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetMessagesRequest) SetId(v string) {
	o.Id = v
}

// GetOffsetomitempty returns the Offsetomitempty field value if set, zero value otherwise.
func (o *GetMessagesRequest) GetOffsetomitempty() int32 {
	if o == nil || IsNil(o.Offsetomitempty) {
		var ret int32
		return ret
	}
	return *o.Offsetomitempty
}

// GetOffsetomitemptyOk returns a tuple with the Offsetomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMessagesRequest) GetOffsetomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.Offsetomitempty) {
		return nil, false
	}
	return o.Offsetomitempty, true
}

// HasOffsetomitempty returns a boolean if a field has been set.
func (o *GetMessagesRequest) HasOffsetomitempty() bool {
	if o != nil && !IsNil(o.Offsetomitempty) {
		return true
	}

	return false
}

// SetOffsetomitempty gets a reference to the given int32 and assigns it to the Offsetomitempty field.
func (o *GetMessagesRequest) SetOffsetomitempty(v int32) {
	o.Offsetomitempty = &v
}

// GetLimitomitempty returns the Limitomitempty field value if set, zero value otherwise.
func (o *GetMessagesRequest) GetLimitomitempty() int32 {
	if o == nil || IsNil(o.Limitomitempty) {
		var ret int32
		return ret
	}
	return *o.Limitomitempty
}

// GetLimitomitemptyOk returns a tuple with the Limitomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMessagesRequest) GetLimitomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.Limitomitempty) {
		return nil, false
	}
	return o.Limitomitempty, true
}

// HasLimitomitempty returns a boolean if a field has been set.
func (o *GetMessagesRequest) HasLimitomitempty() bool {
	if o != nil && !IsNil(o.Limitomitempty) {
		return true
	}

	return false
}

// SetLimitomitempty gets a reference to the given int32 and assigns it to the Limitomitempty field.
func (o *GetMessagesRequest) SetLimitomitempty(v int32) {
	o.Limitomitempty = &v
}

func (o GetMessagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMessagesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Offsetomitempty) {
		toSerialize["offset,omitempty"] = o.Offsetomitempty
	}
	if !IsNil(o.Limitomitempty) {
		toSerialize["limit,omitempty"] = o.Limitomitempty
	}
	return toSerialize, nil
}

func (o *GetMessagesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetMessagesRequest := _GetMessagesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetMessagesRequest)

	if err != nil {
		return err
	}

	*o = GetMessagesRequest(varGetMessagesRequest)

	return err
}

type NullableGetMessagesRequest struct {
	value *GetMessagesRequest
	isSet bool
}

func (v NullableGetMessagesRequest) Get() *GetMessagesRequest {
	return v.value
}

func (v *NullableGetMessagesRequest) Set(val *GetMessagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMessagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMessagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMessagesRequest(val *GetMessagesRequest) *NullableGetMessagesRequest {
	return &NullableGetMessagesRequest{value: val, isSet: true}
}

func (v NullableGetMessagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMessagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


