/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRequest{}

// ListRequest struct for ListRequest
type ListRequest struct {
	Stateomitempty *string `json:"state,omitempty,omitempty"`
	Limitomitempty *int32 `json:"limit,omitempty,omitempty"`
}

// NewListRequest instantiates a new ListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRequest() *ListRequest {
	this := ListRequest{}
	return &this
}

// NewListRequestWithDefaults instantiates a new ListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRequestWithDefaults() *ListRequest {
	this := ListRequest{}
	return &this
}

// GetStateomitempty returns the Stateomitempty field value if set, zero value otherwise.
func (o *ListRequest) GetStateomitempty() string {
	if o == nil || IsNil(o.Stateomitempty) {
		var ret string
		return ret
	}
	return *o.Stateomitempty
}

// GetStateomitemptyOk returns a tuple with the Stateomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRequest) GetStateomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Stateomitempty) {
		return nil, false
	}
	return o.Stateomitempty, true
}

// HasStateomitempty returns a boolean if a field has been set.
func (o *ListRequest) HasStateomitempty() bool {
	if o != nil && !IsNil(o.Stateomitempty) {
		return true
	}

	return false
}

// SetStateomitempty gets a reference to the given string and assigns it to the Stateomitempty field.
func (o *ListRequest) SetStateomitempty(v string) {
	o.Stateomitempty = &v
}

// GetLimitomitempty returns the Limitomitempty field value if set, zero value otherwise.
func (o *ListRequest) GetLimitomitempty() int32 {
	if o == nil || IsNil(o.Limitomitempty) {
		var ret int32
		return ret
	}
	return *o.Limitomitempty
}

// GetLimitomitemptyOk returns a tuple with the Limitomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRequest) GetLimitomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.Limitomitempty) {
		return nil, false
	}
	return o.Limitomitempty, true
}

// HasLimitomitempty returns a boolean if a field has been set.
func (o *ListRequest) HasLimitomitempty() bool {
	if o != nil && !IsNil(o.Limitomitempty) {
		return true
	}

	return false
}

// SetLimitomitempty gets a reference to the given int32 and assigns it to the Limitomitempty field.
func (o *ListRequest) SetLimitomitempty(v int32) {
	o.Limitomitempty = &v
}

func (o ListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Stateomitempty) {
		toSerialize["state,omitempty"] = o.Stateomitempty
	}
	if !IsNil(o.Limitomitempty) {
		toSerialize["limit,omitempty"] = o.Limitomitempty
	}
	return toSerialize, nil
}

type NullableListRequest struct {
	value *ListRequest
	isSet bool
}

func (v NullableListRequest) Get() *ListRequest {
	return v.value
}

func (v *NullableListRequest) Set(val *ListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRequest(val *ListRequest) *NullableListRequest {
	return &NullableListRequest{value: val, isSet: true}
}

func (v NullableListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


