/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteTaskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteTaskRequest{}

// DeleteTaskRequest struct for DeleteTaskRequest
type DeleteTaskRequest struct {
	Id string `json:"id"`
}

type _DeleteTaskRequest DeleteTaskRequest

// NewDeleteTaskRequest instantiates a new DeleteTaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteTaskRequest(id string) *DeleteTaskRequest {
	this := DeleteTaskRequest{}
	this.Id = id
	return &this
}

// NewDeleteTaskRequestWithDefaults instantiates a new DeleteTaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteTaskRequestWithDefaults() *DeleteTaskRequest {
	this := DeleteTaskRequest{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteTaskRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteTaskRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteTaskRequest) SetId(v string) {
	o.Id = v
}

func (o DeleteTaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteTaskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DeleteTaskRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteTaskRequest := _DeleteTaskRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteTaskRequest)

	if err != nil {
		return err
	}

	*o = DeleteTaskRequest(varDeleteTaskRequest)

	return err
}

type NullableDeleteTaskRequest struct {
	value *DeleteTaskRequest
	isSet bool
}

func (v NullableDeleteTaskRequest) Get() *DeleteTaskRequest {
	return v.value
}

func (v *NullableDeleteTaskRequest) Set(val *DeleteTaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteTaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteTaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteTaskRequest(val *DeleteTaskRequest) *NullableDeleteTaskRequest {
	return &NullableDeleteTaskRequest{value: val, isSet: true}
}

func (v NullableDeleteTaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteTaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


