/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the CacheService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CacheService{}

// CacheService struct for CacheService
type CacheService struct {
	Cache map[string]interface{} `json:"cache,omitempty"`
}

// NewCacheService instantiates a new CacheService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCacheService() *CacheService {
	this := CacheService{}
	return &this
}

// NewCacheServiceWithDefaults instantiates a new CacheService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCacheServiceWithDefaults() *CacheService {
	this := CacheService{}
	return &this
}

// GetCache returns the Cache field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CacheService) GetCache() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Cache
}

// GetCacheOk returns a tuple with the Cache field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CacheService) GetCacheOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Cache) {
		return map[string]interface{}{}, false
	}
	return o.Cache, true
}

// HasCache returns a boolean if a field has been set.
func (o *CacheService) HasCache() bool {
	if o != nil && !IsNil(o.Cache) {
		return true
	}

	return false
}

// SetCache gets a reference to the given map[string]interface{} and assigns it to the Cache field.
func (o *CacheService) SetCache(v map[string]interface{}) {
	o.Cache = v
}

func (o CacheService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CacheService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Cache != nil {
		toSerialize["cache"] = o.Cache
	}
	return toSerialize, nil
}

type NullableCacheService struct {
	value *CacheService
	isSet bool
}

func (v NullableCacheService) Get() *CacheService {
	return v.value
}

func (v *NullableCacheService) Set(val *CacheService) {
	v.value = val
	v.isSet = true
}

func (v NullableCacheService) IsSet() bool {
	return v.isSet
}

func (v *NullableCacheService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCacheService(val *CacheService) *NullableCacheService {
	return &NullableCacheService{value: val, isSet: true}
}

func (v NullableCacheService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCacheService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


