/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PipelineStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineStep{}

// PipelineStep struct for PipelineStep
type PipelineStep struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Status string `json:"status"`
	Erroromitempty *string `json:"error,omitempty,omitempty"`
	StartedAtomitempty NullableString `json:"started_at,omitempty,omitempty"`
	EndedAtomitempty NullableString `json:"ended_at,omitempty,omitempty"`
}

type _PipelineStep PipelineStep

// NewPipelineStep instantiates a new PipelineStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStep(id string, name string, status string) *PipelineStep {
	this := PipelineStep{}
	this.Id = id
	this.Name = name
	this.Status = status
	return &this
}

// NewPipelineStepWithDefaults instantiates a new PipelineStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStepWithDefaults() *PipelineStep {
	this := PipelineStep{}
	return &this
}

// GetId returns the Id field value
func (o *PipelineStep) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PipelineStep) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PipelineStep) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PipelineStep) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *PipelineStep) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PipelineStep) SetStatus(v string) {
	o.Status = v
}

// GetErroromitempty returns the Erroromitempty field value if set, zero value otherwise.
func (o *PipelineStep) GetErroromitempty() string {
	if o == nil || IsNil(o.Erroromitempty) {
		var ret string
		return ret
	}
	return *o.Erroromitempty
}

// GetErroromitemptyOk returns a tuple with the Erroromitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineStep) GetErroromitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Erroromitempty) {
		return nil, false
	}
	return o.Erroromitempty, true
}

// HasErroromitempty returns a boolean if a field has been set.
func (o *PipelineStep) HasErroromitempty() bool {
	if o != nil && !IsNil(o.Erroromitempty) {
		return true
	}

	return false
}

// SetErroromitempty gets a reference to the given string and assigns it to the Erroromitempty field.
func (o *PipelineStep) SetErroromitempty(v string) {
	o.Erroromitempty = &v
}

// GetStartedAtomitempty returns the StartedAtomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PipelineStep) GetStartedAtomitempty() string {
	if o == nil || IsNil(o.StartedAtomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.StartedAtomitempty.Get()
}

// GetStartedAtomitemptyOk returns a tuple with the StartedAtomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PipelineStep) GetStartedAtomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAtomitempty.Get(), o.StartedAtomitempty.IsSet()
}

// HasStartedAtomitempty returns a boolean if a field has been set.
func (o *PipelineStep) HasStartedAtomitempty() bool {
	if o != nil && o.StartedAtomitempty.IsSet() {
		return true
	}

	return false
}

// SetStartedAtomitempty gets a reference to the given NullableString and assigns it to the StartedAtomitempty field.
func (o *PipelineStep) SetStartedAtomitempty(v string) {
	o.StartedAtomitempty.Set(&v)
}
// SetStartedAtomitemptyNil sets the value for StartedAtomitempty to be an explicit nil
func (o *PipelineStep) SetStartedAtomitemptyNil() {
	o.StartedAtomitempty.Set(nil)
}

// UnsetStartedAtomitempty ensures that no value is present for StartedAtomitempty, not even an explicit nil
func (o *PipelineStep) UnsetStartedAtomitempty() {
	o.StartedAtomitempty.Unset()
}

// GetEndedAtomitempty returns the EndedAtomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PipelineStep) GetEndedAtomitempty() string {
	if o == nil || IsNil(o.EndedAtomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.EndedAtomitempty.Get()
}

// GetEndedAtomitemptyOk returns a tuple with the EndedAtomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PipelineStep) GetEndedAtomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndedAtomitempty.Get(), o.EndedAtomitempty.IsSet()
}

// HasEndedAtomitempty returns a boolean if a field has been set.
func (o *PipelineStep) HasEndedAtomitempty() bool {
	if o != nil && o.EndedAtomitempty.IsSet() {
		return true
	}

	return false
}

// SetEndedAtomitempty gets a reference to the given NullableString and assigns it to the EndedAtomitempty field.
func (o *PipelineStep) SetEndedAtomitempty(v string) {
	o.EndedAtomitempty.Set(&v)
}
// SetEndedAtomitemptyNil sets the value for EndedAtomitempty to be an explicit nil
func (o *PipelineStep) SetEndedAtomitemptyNil() {
	o.EndedAtomitempty.Set(nil)
}

// UnsetEndedAtomitempty ensures that no value is present for EndedAtomitempty, not even an explicit nil
func (o *PipelineStep) UnsetEndedAtomitempty() {
	o.EndedAtomitempty.Unset()
}

func (o PipelineStep) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	if !IsNil(o.Erroromitempty) {
		toSerialize["error,omitempty"] = o.Erroromitempty
	}
	if o.StartedAtomitempty.IsSet() {
		toSerialize["started_at,omitempty"] = o.StartedAtomitempty.Get()
	}
	if o.EndedAtomitempty.IsSet() {
		toSerialize["ended_at,omitempty"] = o.EndedAtomitempty.Get()
	}
	return toSerialize, nil
}

func (o *PipelineStep) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPipelineStep := _PipelineStep{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPipelineStep)

	if err != nil {
		return err
	}

	*o = PipelineStep(varPipelineStep)

	return err
}

type NullablePipelineStep struct {
	value *PipelineStep
	isSet bool
}

func (v NullablePipelineStep) Get() *PipelineStep {
	return v.value
}

func (v *NullablePipelineStep) Set(val *PipelineStep) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStep) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStep(val *PipelineStep) *NullablePipelineStep {
	return &NullablePipelineStep{value: val, isSet: true}
}

func (v NullablePipelineStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


