/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompactSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompactSessionRequest{}

// CompactSessionRequest struct for CompactSessionRequest
type CompactSessionRequest struct {
	Id string `json:"id"`
}

type _CompactSessionRequest CompactSessionRequest

// NewCompactSessionRequest instantiates a new CompactSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompactSessionRequest(id string) *CompactSessionRequest {
	this := CompactSessionRequest{}
	this.Id = id
	return &this
}

// NewCompactSessionRequestWithDefaults instantiates a new CompactSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompactSessionRequestWithDefaults() *CompactSessionRequest {
	this := CompactSessionRequest{}
	return &this
}

// GetId returns the Id field value
func (o *CompactSessionRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CompactSessionRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CompactSessionRequest) SetId(v string) {
	o.Id = v
}

func (o CompactSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompactSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *CompactSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompactSessionRequest := _CompactSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompactSessionRequest)

	if err != nil {
		return err
	}

	*o = CompactSessionRequest(varCompactSessionRequest)

	return err
}

type NullableCompactSessionRequest struct {
	value *CompactSessionRequest
	isSet bool
}

func (v NullableCompactSessionRequest) Get() *CompactSessionRequest {
	return v.value
}

func (v *NullableCompactSessionRequest) Set(val *CompactSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCompactSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCompactSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompactSessionRequest(val *CompactSessionRequest) *NullableCompactSessionRequest {
	return &NullableCompactSessionRequest{value: val, isSet: true}
}

func (v NullableCompactSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompactSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


