/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ProjectService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectService{}

// ProjectService struct for ProjectService
type ProjectService struct {
	Pm map[string]interface{} `json:"pm,omitempty"`
	Store map[string]interface{} `json:"store,omitempty"`
}

// NewProjectService instantiates a new ProjectService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectService() *ProjectService {
	this := ProjectService{}
	return &this
}

// NewProjectServiceWithDefaults instantiates a new ProjectService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectServiceWithDefaults() *ProjectService {
	this := ProjectService{}
	return &this
}

// GetPm returns the Pm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ProjectService) GetPm() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Pm
}

// GetPmOk returns a tuple with the Pm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ProjectService) GetPmOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Pm) {
		return map[string]interface{}{}, false
	}
	return o.Pm, true
}

// HasPm returns a boolean if a field has been set.
func (o *ProjectService) HasPm() bool {
	if o != nil && !IsNil(o.Pm) {
		return true
	}

	return false
}

// SetPm gets a reference to the given map[string]interface{} and assigns it to the Pm field.
func (o *ProjectService) SetPm(v map[string]interface{}) {
	o.Pm = v
}

// GetStore returns the Store field value if set, zero value otherwise.
func (o *ProjectService) GetStore() map[string]interface{} {
	if o == nil || IsNil(o.Store) {
		var ret map[string]interface{}
		return ret
	}
	return o.Store
}

// GetStoreOk returns a tuple with the Store field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectService) GetStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Store) {
		return map[string]interface{}{}, false
	}
	return o.Store, true
}

// HasStore returns a boolean if a field has been set.
func (o *ProjectService) HasStore() bool {
	if o != nil && !IsNil(o.Store) {
		return true
	}

	return false
}

// SetStore gets a reference to the given map[string]interface{} and assigns it to the Store field.
func (o *ProjectService) SetStore(v map[string]interface{}) {
	o.Store = v
}

func (o ProjectService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Pm != nil {
		toSerialize["pm"] = o.Pm
	}
	if !IsNil(o.Store) {
		toSerialize["store"] = o.Store
	}
	return toSerialize, nil
}

type NullableProjectService struct {
	value *ProjectService
	isSet bool
}

func (v NullableProjectService) Get() *ProjectService {
	return v.value
}

func (v *NullableProjectService) Set(val *ProjectService) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectService) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectService(val *ProjectService) *NullableProjectService {
	return &NullableProjectService{value: val, isSet: true}
}

func (v NullableProjectService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


