/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePlanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlanRequest{}

// CreatePlanRequest struct for CreatePlanRequest
type CreatePlanRequest struct {
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	ProjectId *string `json:"project_id,omitempty"`
	ProjectPath *string `json:"project_path,omitempty"`
	SessionId string `json:"session_id"`
}

type _CreatePlanRequest CreatePlanRequest

// NewCreatePlanRequest instantiates a new CreatePlanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlanRequest(title string, sessionId string) *CreatePlanRequest {
	this := CreatePlanRequest{}
	this.Title = title
	this.SessionId = sessionId
	return &this
}

// NewCreatePlanRequestWithDefaults instantiates a new CreatePlanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlanRequestWithDefaults() *CreatePlanRequest {
	this := CreatePlanRequest{}
	return &this
}

// GetTitle returns the Title field value
func (o *CreatePlanRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreatePlanRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreatePlanRequest) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreatePlanRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreatePlanRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreatePlanRequest) SetDescription(v string) {
	o.Description = &v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *CreatePlanRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *CreatePlanRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *CreatePlanRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetProjectPath returns the ProjectPath field value if set, zero value otherwise.
func (o *CreatePlanRequest) GetProjectPath() string {
	if o == nil || IsNil(o.ProjectPath) {
		var ret string
		return ret
	}
	return *o.ProjectPath
}

// GetProjectPathOk returns a tuple with the ProjectPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequest) GetProjectPathOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectPath) {
		return nil, false
	}
	return o.ProjectPath, true
}

// HasProjectPath returns a boolean if a field has been set.
func (o *CreatePlanRequest) HasProjectPath() bool {
	if o != nil && !IsNil(o.ProjectPath) {
		return true
	}

	return false
}

// SetProjectPath gets a reference to the given string and assigns it to the ProjectPath field.
func (o *CreatePlanRequest) SetProjectPath(v string) {
	o.ProjectPath = &v
}

// GetSessionId returns the SessionId field value
func (o *CreatePlanRequest) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *CreatePlanRequest) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *CreatePlanRequest) SetSessionId(v string) {
	o.SessionId = v
}

func (o CreatePlanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.ProjectPath) {
		toSerialize["project_path"] = o.ProjectPath
	}
	toSerialize["session_id"] = o.SessionId
	return toSerialize, nil
}

func (o *CreatePlanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"session_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlanRequest := _CreatePlanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlanRequest)

	if err != nil {
		return err
	}

	*o = CreatePlanRequest(varCreatePlanRequest)

	return err
}

type NullableCreatePlanRequest struct {
	value *CreatePlanRequest
	isSet bool
}

func (v NullableCreatePlanRequest) Get() *CreatePlanRequest {
	return v.value
}

func (v *NullableCreatePlanRequest) Set(val *CreatePlanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlanRequest(val *CreatePlanRequest) *NullableCreatePlanRequest {
	return &NullableCreatePlanRequest{value: val, isSet: true}
}

func (v NullableCreatePlanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


