/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SkillUIDescriptor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillUIDescriptor{}

// SkillUIDescriptor struct for SkillUIDescriptor
type SkillUIDescriptor struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Description string `json:"description"`
	UiType string `json:"ui_type"`
	Category *string `json:"category,omitempty"`
	Tags NullableString `json:"tags,omitempty"`
	Examples NullableString `json:"examples,omitempty"`
	RiskLevel *string `json:"risk_level,omitempty"`
	Body *string `json:"body,omitempty"`
	Fields []string `json:"fields,omitempty"`
	Actions []string `json:"actions,omitempty"`
}

type _SkillUIDescriptor SkillUIDescriptor

// NewSkillUIDescriptor instantiates a new SkillUIDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillUIDescriptor(slug string, name string, description string, uiType string) *SkillUIDescriptor {
	this := SkillUIDescriptor{}
	this.Slug = slug
	this.Name = name
	this.Description = description
	this.UiType = uiType
	return &this
}

// NewSkillUIDescriptorWithDefaults instantiates a new SkillUIDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillUIDescriptorWithDefaults() *SkillUIDescriptor {
	this := SkillUIDescriptor{}
	return &this
}

// GetSlug returns the Slug field value
func (o *SkillUIDescriptor) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *SkillUIDescriptor) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *SkillUIDescriptor) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SkillUIDescriptor) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SkillUIDescriptor) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SkillUIDescriptor) SetDescription(v string) {
	o.Description = v
}

// GetUiType returns the UiType field value
func (o *SkillUIDescriptor) GetUiType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UiType
}

// GetUiTypeOk returns a tuple with the UiType field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetUiTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UiType, true
}

// SetUiType sets field value
func (o *SkillUIDescriptor) SetUiType(v string) {
	o.UiType = v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *SkillUIDescriptor) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *SkillUIDescriptor) SetCategory(v string) {
	o.Category = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetTags() string {
	if o == nil || IsNil(o.Tags.Get()) {
		var ret string
		return ret
	}
	return *o.Tags.Get()
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetTagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags.Get(), o.Tags.IsSet()
}

// HasTags returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasTags() bool {
	if o != nil && o.Tags.IsSet() {
		return true
	}

	return false
}

// SetTags gets a reference to the given NullableString and assigns it to the Tags field.
func (o *SkillUIDescriptor) SetTags(v string) {
	o.Tags.Set(&v)
}
// SetTagsNil sets the value for Tags to be an explicit nil
func (o *SkillUIDescriptor) SetTagsNil() {
	o.Tags.Set(nil)
}

// UnsetTags ensures that no value is present for Tags, not even an explicit nil
func (o *SkillUIDescriptor) UnsetTags() {
	o.Tags.Unset()
}

// GetExamples returns the Examples field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetExamples() string {
	if o == nil || IsNil(o.Examples.Get()) {
		var ret string
		return ret
	}
	return *o.Examples.Get()
}

// GetExamplesOk returns a tuple with the Examples field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetExamplesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Examples.Get(), o.Examples.IsSet()
}

// HasExamples returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasExamples() bool {
	if o != nil && o.Examples.IsSet() {
		return true
	}

	return false
}

// SetExamples gets a reference to the given NullableString and assigns it to the Examples field.
func (o *SkillUIDescriptor) SetExamples(v string) {
	o.Examples.Set(&v)
}
// SetExamplesNil sets the value for Examples to be an explicit nil
func (o *SkillUIDescriptor) SetExamplesNil() {
	o.Examples.Set(nil)
}

// UnsetExamples ensures that no value is present for Examples, not even an explicit nil
func (o *SkillUIDescriptor) UnsetExamples() {
	o.Examples.Unset()
}

// GetRiskLevel returns the RiskLevel field value if set, zero value otherwise.
func (o *SkillUIDescriptor) GetRiskLevel() string {
	if o == nil || IsNil(o.RiskLevel) {
		var ret string
		return ret
	}
	return *o.RiskLevel
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetRiskLevelOk() (*string, bool) {
	if o == nil || IsNil(o.RiskLevel) {
		return nil, false
	}
	return o.RiskLevel, true
}

// HasRiskLevel returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasRiskLevel() bool {
	if o != nil && !IsNil(o.RiskLevel) {
		return true
	}

	return false
}

// SetRiskLevel gets a reference to the given string and assigns it to the RiskLevel field.
func (o *SkillUIDescriptor) SetRiskLevel(v string) {
	o.RiskLevel = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *SkillUIDescriptor) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *SkillUIDescriptor) SetBody(v string) {
	o.Body = &v
}

// GetFields returns the Fields field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetFieldsOk() ([]string, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given []string and assigns it to the Fields field.
func (o *SkillUIDescriptor) SetFields(v []string) {
	o.Fields = v
}

// GetActions returns the Actions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetActions() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetActionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []string and assigns it to the Actions field.
func (o *SkillUIDescriptor) SetActions(v []string) {
	o.Actions = v
}

func (o SkillUIDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkillUIDescriptor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["ui_type"] = o.UiType
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if o.Tags.IsSet() {
		toSerialize["tags"] = o.Tags.Get()
	}
	if o.Examples.IsSet() {
		toSerialize["examples"] = o.Examples.Get()
	}
	if !IsNil(o.RiskLevel) {
		toSerialize["risk_level"] = o.RiskLevel
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	return toSerialize, nil
}

func (o *SkillUIDescriptor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"name",
		"description",
		"ui_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkillUIDescriptor := _SkillUIDescriptor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkillUIDescriptor)

	if err != nil {
		return err
	}

	*o = SkillUIDescriptor(varSkillUIDescriptor)

	return err
}

type NullableSkillUIDescriptor struct {
	value *SkillUIDescriptor
	isSet bool
}

func (v NullableSkillUIDescriptor) Get() *SkillUIDescriptor {
	return v.value
}

func (v *NullableSkillUIDescriptor) Set(val *SkillUIDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillUIDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillUIDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillUIDescriptor(val *SkillUIDescriptor) *NullableSkillUIDescriptor {
	return &NullableSkillUIDescriptor{value: val, isSet: true}
}

func (v NullableSkillUIDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillUIDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


