/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PipelineStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineStatusResponse{}

// PipelineStatusResponse struct for PipelineStatusResponse
type PipelineStatusResponse struct {
	PipelineId string `json:"pipeline_id"`
	Name string `json:"name"`
	Status string `json:"status"`
	Steps []string `json:"steps"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type _PipelineStatusResponse PipelineStatusResponse

// NewPipelineStatusResponse instantiates a new PipelineStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineStatusResponse(pipelineId string, name string, status string, steps []string, createdAt string, updatedAt string) *PipelineStatusResponse {
	this := PipelineStatusResponse{}
	this.PipelineId = pipelineId
	this.Name = name
	this.Status = status
	this.Steps = steps
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewPipelineStatusResponseWithDefaults instantiates a new PipelineStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineStatusResponseWithDefaults() *PipelineStatusResponse {
	this := PipelineStatusResponse{}
	return &this
}

// GetPipelineId returns the PipelineId field value
func (o *PipelineStatusResponse) GetPipelineId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PipelineId
}

// GetPipelineIdOk returns a tuple with the PipelineId field value
// and a boolean to check if the value has been set.
func (o *PipelineStatusResponse) GetPipelineIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PipelineId, true
}

// SetPipelineId sets field value
func (o *PipelineStatusResponse) SetPipelineId(v string) {
	o.PipelineId = v
}

// GetName returns the Name field value
func (o *PipelineStatusResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PipelineStatusResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PipelineStatusResponse) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *PipelineStatusResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PipelineStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PipelineStatusResponse) SetStatus(v string) {
	o.Status = v
}

// GetSteps returns the Steps field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *PipelineStatusResponse) GetSteps() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PipelineStatusResponse) GetStepsOk() ([]string, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *PipelineStatusResponse) SetSteps(v []string) {
	o.Steps = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PipelineStatusResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PipelineStatusResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PipelineStatusResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PipelineStatusResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PipelineStatusResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PipelineStatusResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

func (o PipelineStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pipeline_id"] = o.PipelineId
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	if o.Steps != nil {
		toSerialize["steps"] = o.Steps
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *PipelineStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pipeline_id",
		"name",
		"status",
		"steps",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPipelineStatusResponse := _PipelineStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPipelineStatusResponse)

	if err != nil {
		return err
	}

	*o = PipelineStatusResponse(varPipelineStatusResponse)

	return err
}

type NullablePipelineStatusResponse struct {
	value *PipelineStatusResponse
	isSet bool
}

func (v NullablePipelineStatusResponse) Get() *PipelineStatusResponse {
	return v.value
}

func (v *NullablePipelineStatusResponse) Set(val *PipelineStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineStatusResponse(val *PipelineStatusResponse) *NullablePipelineStatusResponse {
	return &NullablePipelineStatusResponse{value: val, isSet: true}
}

func (v NullablePipelineStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


