/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemoryQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryQueryRequest{}

// MemoryQueryRequest struct for MemoryQueryRequest
type MemoryQueryRequest struct {
	Query string `json:"query"`
	Limit *int32 `json:"limit,omitempty"`
	Category *string `json:"category,omitempty"`
}

type _MemoryQueryRequest MemoryQueryRequest

// NewMemoryQueryRequest instantiates a new MemoryQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryQueryRequest(query string) *MemoryQueryRequest {
	this := MemoryQueryRequest{}
	this.Query = query
	return &this
}

// NewMemoryQueryRequestWithDefaults instantiates a new MemoryQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryQueryRequestWithDefaults() *MemoryQueryRequest {
	this := MemoryQueryRequest{}
	return &this
}

// GetQuery returns the Query field value
func (o *MemoryQueryRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *MemoryQueryRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *MemoryQueryRequest) SetQuery(v string) {
	o.Query = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *MemoryQueryRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryQueryRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *MemoryQueryRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *MemoryQueryRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *MemoryQueryRequest) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemoryQueryRequest) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *MemoryQueryRequest) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *MemoryQueryRequest) SetCategory(v string) {
	o.Category = &v
}

func (o MemoryQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	return toSerialize, nil
}

func (o *MemoryQueryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemoryQueryRequest := _MemoryQueryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemoryQueryRequest)

	if err != nil {
		return err
	}

	*o = MemoryQueryRequest(varMemoryQueryRequest)

	return err
}

type NullableMemoryQueryRequest struct {
	value *MemoryQueryRequest
	isSet bool
}

func (v NullableMemoryQueryRequest) Get() *MemoryQueryRequest {
	return v.value
}

func (v *NullableMemoryQueryRequest) Set(val *MemoryQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryQueryRequest(val *MemoryQueryRequest) *NullableMemoryQueryRequest {
	return &NullableMemoryQueryRequest{value: val, isSet: true}
}

func (v NullableMemoryQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


