/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the MemoryService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemoryService{}

// MemoryService struct for MemoryService
type MemoryService struct {
	Manager map[string]interface{} `json:"manager,omitempty"`
}

// NewMemoryService instantiates a new MemoryService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemoryService() *MemoryService {
	this := MemoryService{}
	return &this
}

// NewMemoryServiceWithDefaults instantiates a new MemoryService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemoryServiceWithDefaults() *MemoryService {
	this := MemoryService{}
	return &this
}

// GetManager returns the Manager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MemoryService) GetManager() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Manager
}

// GetManagerOk returns a tuple with the Manager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MemoryService) GetManagerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Manager) {
		return map[string]interface{}{}, false
	}
	return o.Manager, true
}

// HasManager returns a boolean if a field has been set.
func (o *MemoryService) HasManager() bool {
	if o != nil && !IsNil(o.Manager) {
		return true
	}

	return false
}

// SetManager gets a reference to the given map[string]interface{} and assigns it to the Manager field.
func (o *MemoryService) SetManager(v map[string]interface{}) {
	o.Manager = v
}

func (o MemoryService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemoryService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Manager != nil {
		toSerialize["manager"] = o.Manager
	}
	return toSerialize, nil
}

type NullableMemoryService struct {
	value *MemoryService
	isSet bool
}

func (v NullableMemoryService) Get() *MemoryService {
	return v.value
}

func (v *NullableMemoryService) Set(val *MemoryService) {
	v.value = val
	v.isSet = true
}

func (v NullableMemoryService) IsSet() bool {
	return v.isSet
}

func (v *NullableMemoryService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemoryService(val *MemoryService) *NullableMemoryService {
	return &NullableMemoryService{value: val, isSet: true}
}

func (v NullableMemoryService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemoryService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


