/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentJobConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentJobConfig{}

// AgentJobConfig struct for AgentJobConfig
type AgentJobConfig struct {
	Prompt string `json:"prompt"`
	Context NullableString `json:"context,omitempty"`
	Model *string `json:"model,omitempty"`
	MaxTokens *int32 `json:"max_tokens,omitempty"`
	Temperature *float32 `json:"temperature,omitempty"`
}

type _AgentJobConfig AgentJobConfig

// NewAgentJobConfig instantiates a new AgentJobConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentJobConfig(prompt string) *AgentJobConfig {
	this := AgentJobConfig{}
	this.Prompt = prompt
	return &this
}

// NewAgentJobConfigWithDefaults instantiates a new AgentJobConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentJobConfigWithDefaults() *AgentJobConfig {
	this := AgentJobConfig{}
	return &this
}

// GetPrompt returns the Prompt field value
func (o *AgentJobConfig) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *AgentJobConfig) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *AgentJobConfig) SetPrompt(v string) {
	o.Prompt = v
}

// GetContext returns the Context field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentJobConfig) GetContext() string {
	if o == nil || IsNil(o.Context.Get()) {
		var ret string
		return ret
	}
	return *o.Context.Get()
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentJobConfig) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Context.Get(), o.Context.IsSet()
}

// HasContext returns a boolean if a field has been set.
func (o *AgentJobConfig) HasContext() bool {
	if o != nil && o.Context.IsSet() {
		return true
	}

	return false
}

// SetContext gets a reference to the given NullableString and assigns it to the Context field.
func (o *AgentJobConfig) SetContext(v string) {
	o.Context.Set(&v)
}
// SetContextNil sets the value for Context to be an explicit nil
func (o *AgentJobConfig) SetContextNil() {
	o.Context.Set(nil)
}

// UnsetContext ensures that no value is present for Context, not even an explicit nil
func (o *AgentJobConfig) UnsetContext() {
	o.Context.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *AgentJobConfig) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentJobConfig) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *AgentJobConfig) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *AgentJobConfig) SetModel(v string) {
	o.Model = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *AgentJobConfig) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentJobConfig) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *AgentJobConfig) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *AgentJobConfig) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetTemperature returns the Temperature field value if set, zero value otherwise.
func (o *AgentJobConfig) GetTemperature() float32 {
	if o == nil || IsNil(o.Temperature) {
		var ret float32
		return ret
	}
	return *o.Temperature
}

// GetTemperatureOk returns a tuple with the Temperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentJobConfig) GetTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.Temperature) {
		return nil, false
	}
	return o.Temperature, true
}

// HasTemperature returns a boolean if a field has been set.
func (o *AgentJobConfig) HasTemperature() bool {
	if o != nil && !IsNil(o.Temperature) {
		return true
	}

	return false
}

// SetTemperature gets a reference to the given float32 and assigns it to the Temperature field.
func (o *AgentJobConfig) SetTemperature(v float32) {
	o.Temperature = &v
}

func (o AgentJobConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentJobConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt"] = o.Prompt
	if o.Context.IsSet() {
		toSerialize["context"] = o.Context.Get()
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if !IsNil(o.Temperature) {
		toSerialize["temperature"] = o.Temperature
	}
	return toSerialize, nil
}

func (o *AgentJobConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentJobConfig := _AgentJobConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentJobConfig)

	if err != nil {
		return err
	}

	*o = AgentJobConfig(varAgentJobConfig)

	return err
}

type NullableAgentJobConfig struct {
	value *AgentJobConfig
	isSet bool
}

func (v NullableAgentJobConfig) Get() *AgentJobConfig {
	return v.value
}

func (v *NullableAgentJobConfig) Set(val *AgentJobConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentJobConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentJobConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentJobConfig(val *AgentJobConfig) *NullableAgentJobConfig {
	return &NullableAgentJobConfig{value: val, isSet: true}
}

func (v NullableAgentJobConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentJobConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


