/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterProjectRequest{}

// RegisterProjectRequest struct for RegisterProjectRequest
type RegisterProjectRequest struct {
	Id *string `json:"id,omitempty"`
	Name string `json:"name"`
	GitUrl *string `json:"git_url,omitempty"`
	LocalPath *string `json:"local_path,omitempty"`
}

type _RegisterProjectRequest RegisterProjectRequest

// NewRegisterProjectRequest instantiates a new RegisterProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterProjectRequest(name string) *RegisterProjectRequest {
	this := RegisterProjectRequest{}
	this.Name = name
	return &this
}

// NewRegisterProjectRequestWithDefaults instantiates a new RegisterProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterProjectRequestWithDefaults() *RegisterProjectRequest {
	this := RegisterProjectRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegisterProjectRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegisterProjectRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RegisterProjectRequest) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *RegisterProjectRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegisterProjectRequest) SetName(v string) {
	o.Name = v
}

// GetGitUrl returns the GitUrl field value if set, zero value otherwise.
func (o *RegisterProjectRequest) GetGitUrl() string {
	if o == nil || IsNil(o.GitUrl) {
		var ret string
		return ret
	}
	return *o.GitUrl
}

// GetGitUrlOk returns a tuple with the GitUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetGitUrlOk() (*string, bool) {
	if o == nil || IsNil(o.GitUrl) {
		return nil, false
	}
	return o.GitUrl, true
}

// HasGitUrl returns a boolean if a field has been set.
func (o *RegisterProjectRequest) HasGitUrl() bool {
	if o != nil && !IsNil(o.GitUrl) {
		return true
	}

	return false
}

// SetGitUrl gets a reference to the given string and assigns it to the GitUrl field.
func (o *RegisterProjectRequest) SetGitUrl(v string) {
	o.GitUrl = &v
}

// GetLocalPath returns the LocalPath field value if set, zero value otherwise.
func (o *RegisterProjectRequest) GetLocalPath() string {
	if o == nil || IsNil(o.LocalPath) {
		var ret string
		return ret
	}
	return *o.LocalPath
}

// GetLocalPathOk returns a tuple with the LocalPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetLocalPathOk() (*string, bool) {
	if o == nil || IsNil(o.LocalPath) {
		return nil, false
	}
	return o.LocalPath, true
}

// HasLocalPath returns a boolean if a field has been set.
func (o *RegisterProjectRequest) HasLocalPath() bool {
	if o != nil && !IsNil(o.LocalPath) {
		return true
	}

	return false
}

// SetLocalPath gets a reference to the given string and assigns it to the LocalPath field.
func (o *RegisterProjectRequest) SetLocalPath(v string) {
	o.LocalPath = &v
}

func (o RegisterProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.GitUrl) {
		toSerialize["git_url"] = o.GitUrl
	}
	if !IsNil(o.LocalPath) {
		toSerialize["local_path"] = o.LocalPath
	}
	return toSerialize, nil
}

func (o *RegisterProjectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterProjectRequest := _RegisterProjectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterProjectRequest)

	if err != nil {
		return err
	}

	*o = RegisterProjectRequest(varRegisterProjectRequest)

	return err
}

type NullableRegisterProjectRequest struct {
	value *RegisterProjectRequest
	isSet bool
}

func (v NullableRegisterProjectRequest) Get() *RegisterProjectRequest {
	return v.value
}

func (v *NullableRegisterProjectRequest) Set(val *RegisterProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterProjectRequest(val *RegisterProjectRequest) *NullableRegisterProjectRequest {
	return &NullableRegisterProjectRequest{value: val, isSet: true}
}

func (v NullableRegisterProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


