/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ModelService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelService{}

// ModelService struct for ModelService
type ModelService struct {
	ConfigPath *string `json:"configPath,omitempty"`
	CredStore map[string]interface{} `json:"credStore,omitempty"`
	StateDir *string `json:"stateDir,omitempty"`
}

// NewModelService instantiates a new ModelService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelService() *ModelService {
	this := ModelService{}
	return &this
}

// NewModelServiceWithDefaults instantiates a new ModelService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelServiceWithDefaults() *ModelService {
	this := ModelService{}
	return &this
}

// GetConfigPath returns the ConfigPath field value if set, zero value otherwise.
func (o *ModelService) GetConfigPath() string {
	if o == nil || IsNil(o.ConfigPath) {
		var ret string
		return ret
	}
	return *o.ConfigPath
}

// GetConfigPathOk returns a tuple with the ConfigPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelService) GetConfigPathOk() (*string, bool) {
	if o == nil || IsNil(o.ConfigPath) {
		return nil, false
	}
	return o.ConfigPath, true
}

// HasConfigPath returns a boolean if a field has been set.
func (o *ModelService) HasConfigPath() bool {
	if o != nil && !IsNil(o.ConfigPath) {
		return true
	}

	return false
}

// SetConfigPath gets a reference to the given string and assigns it to the ConfigPath field.
func (o *ModelService) SetConfigPath(v string) {
	o.ConfigPath = &v
}

// GetCredStore returns the CredStore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ModelService) GetCredStore() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.CredStore
}

// GetCredStoreOk returns a tuple with the CredStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModelService) GetCredStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CredStore) {
		return map[string]interface{}{}, false
	}
	return o.CredStore, true
}

// HasCredStore returns a boolean if a field has been set.
func (o *ModelService) HasCredStore() bool {
	if o != nil && !IsNil(o.CredStore) {
		return true
	}

	return false
}

// SetCredStore gets a reference to the given map[string]interface{} and assigns it to the CredStore field.
func (o *ModelService) SetCredStore(v map[string]interface{}) {
	o.CredStore = v
}

// GetStateDir returns the StateDir field value if set, zero value otherwise.
func (o *ModelService) GetStateDir() string {
	if o == nil || IsNil(o.StateDir) {
		var ret string
		return ret
	}
	return *o.StateDir
}

// GetStateDirOk returns a tuple with the StateDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelService) GetStateDirOk() (*string, bool) {
	if o == nil || IsNil(o.StateDir) {
		return nil, false
	}
	return o.StateDir, true
}

// HasStateDir returns a boolean if a field has been set.
func (o *ModelService) HasStateDir() bool {
	if o != nil && !IsNil(o.StateDir) {
		return true
	}

	return false
}

// SetStateDir gets a reference to the given string and assigns it to the StateDir field.
func (o *ModelService) SetStateDir(v string) {
	o.StateDir = &v
}

func (o ModelService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConfigPath) {
		toSerialize["configPath"] = o.ConfigPath
	}
	if o.CredStore != nil {
		toSerialize["credStore"] = o.CredStore
	}
	if !IsNil(o.StateDir) {
		toSerialize["stateDir"] = o.StateDir
	}
	return toSerialize, nil
}

type NullableModelService struct {
	value *ModelService
	isSet bool
}

func (v NullableModelService) Get() *ModelService {
	return v.value
}

func (v *NullableModelService) Set(val *ModelService) {
	v.value = val
	v.isSet = true
}

func (v NullableModelService) IsSet() bool {
	return v.isSet
}

func (v *NullableModelService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelService(val *ModelService) *NullableModelService {
	return &NullableModelService{value: val, isSet: true}
}

func (v NullableModelService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


