/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SkillUIDescriptor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkillUIDescriptor{}

// SkillUIDescriptor struct for SkillUIDescriptor
type SkillUIDescriptor struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Description string `json:"description"`
	UiType string `json:"ui_type"`
	Categoryomitempty *string `json:"category,omitempty,omitempty"`
	Tagsomitempty NullableString `json:"tags,omitempty,omitempty"`
	Examplesomitempty NullableString `json:"examples,omitempty,omitempty"`
	RiskLevelomitempty *string `json:"risk_level,omitempty,omitempty"`
	Bodyomitempty *string `json:"body,omitempty,omitempty"`
	Fieldsomitempty []string `json:"fields,omitempty,omitempty"`
	Actionsomitempty []string `json:"actions,omitempty,omitempty"`
}

type _SkillUIDescriptor SkillUIDescriptor

// NewSkillUIDescriptor instantiates a new SkillUIDescriptor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkillUIDescriptor(slug string, name string, description string, uiType string) *SkillUIDescriptor {
	this := SkillUIDescriptor{}
	this.Slug = slug
	this.Name = name
	this.Description = description
	this.UiType = uiType
	return &this
}

// NewSkillUIDescriptorWithDefaults instantiates a new SkillUIDescriptor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkillUIDescriptorWithDefaults() *SkillUIDescriptor {
	this := SkillUIDescriptor{}
	return &this
}

// GetSlug returns the Slug field value
func (o *SkillUIDescriptor) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *SkillUIDescriptor) SetSlug(v string) {
	o.Slug = v
}

// GetName returns the Name field value
func (o *SkillUIDescriptor) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SkillUIDescriptor) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *SkillUIDescriptor) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SkillUIDescriptor) SetDescription(v string) {
	o.Description = v
}

// GetUiType returns the UiType field value
func (o *SkillUIDescriptor) GetUiType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UiType
}

// GetUiTypeOk returns a tuple with the UiType field value
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetUiTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UiType, true
}

// SetUiType sets field value
func (o *SkillUIDescriptor) SetUiType(v string) {
	o.UiType = v
}

// GetCategoryomitempty returns the Categoryomitempty field value if set, zero value otherwise.
func (o *SkillUIDescriptor) GetCategoryomitempty() string {
	if o == nil || IsNil(o.Categoryomitempty) {
		var ret string
		return ret
	}
	return *o.Categoryomitempty
}

// GetCategoryomitemptyOk returns a tuple with the Categoryomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetCategoryomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Categoryomitempty) {
		return nil, false
	}
	return o.Categoryomitempty, true
}

// HasCategoryomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasCategoryomitempty() bool {
	if o != nil && !IsNil(o.Categoryomitempty) {
		return true
	}

	return false
}

// SetCategoryomitempty gets a reference to the given string and assigns it to the Categoryomitempty field.
func (o *SkillUIDescriptor) SetCategoryomitempty(v string) {
	o.Categoryomitempty = &v
}

// GetTagsomitempty returns the Tagsomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetTagsomitempty() string {
	if o == nil || IsNil(o.Tagsomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.Tagsomitempty.Get()
}

// GetTagsomitemptyOk returns a tuple with the Tagsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetTagsomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tagsomitempty.Get(), o.Tagsomitempty.IsSet()
}

// HasTagsomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasTagsomitempty() bool {
	if o != nil && o.Tagsomitempty.IsSet() {
		return true
	}

	return false
}

// SetTagsomitempty gets a reference to the given NullableString and assigns it to the Tagsomitempty field.
func (o *SkillUIDescriptor) SetTagsomitempty(v string) {
	o.Tagsomitempty.Set(&v)
}
// SetTagsomitemptyNil sets the value for Tagsomitempty to be an explicit nil
func (o *SkillUIDescriptor) SetTagsomitemptyNil() {
	o.Tagsomitempty.Set(nil)
}

// UnsetTagsomitempty ensures that no value is present for Tagsomitempty, not even an explicit nil
func (o *SkillUIDescriptor) UnsetTagsomitempty() {
	o.Tagsomitempty.Unset()
}

// GetExamplesomitempty returns the Examplesomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetExamplesomitempty() string {
	if o == nil || IsNil(o.Examplesomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.Examplesomitempty.Get()
}

// GetExamplesomitemptyOk returns a tuple with the Examplesomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetExamplesomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Examplesomitempty.Get(), o.Examplesomitempty.IsSet()
}

// HasExamplesomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasExamplesomitempty() bool {
	if o != nil && o.Examplesomitempty.IsSet() {
		return true
	}

	return false
}

// SetExamplesomitempty gets a reference to the given NullableString and assigns it to the Examplesomitempty field.
func (o *SkillUIDescriptor) SetExamplesomitempty(v string) {
	o.Examplesomitempty.Set(&v)
}
// SetExamplesomitemptyNil sets the value for Examplesomitempty to be an explicit nil
func (o *SkillUIDescriptor) SetExamplesomitemptyNil() {
	o.Examplesomitempty.Set(nil)
}

// UnsetExamplesomitempty ensures that no value is present for Examplesomitempty, not even an explicit nil
func (o *SkillUIDescriptor) UnsetExamplesomitempty() {
	o.Examplesomitempty.Unset()
}

// GetRiskLevelomitempty returns the RiskLevelomitempty field value if set, zero value otherwise.
func (o *SkillUIDescriptor) GetRiskLevelomitempty() string {
	if o == nil || IsNil(o.RiskLevelomitempty) {
		var ret string
		return ret
	}
	return *o.RiskLevelomitempty
}

// GetRiskLevelomitemptyOk returns a tuple with the RiskLevelomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetRiskLevelomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.RiskLevelomitempty) {
		return nil, false
	}
	return o.RiskLevelomitempty, true
}

// HasRiskLevelomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasRiskLevelomitempty() bool {
	if o != nil && !IsNil(o.RiskLevelomitempty) {
		return true
	}

	return false
}

// SetRiskLevelomitempty gets a reference to the given string and assigns it to the RiskLevelomitempty field.
func (o *SkillUIDescriptor) SetRiskLevelomitempty(v string) {
	o.RiskLevelomitempty = &v
}

// GetBodyomitempty returns the Bodyomitempty field value if set, zero value otherwise.
func (o *SkillUIDescriptor) GetBodyomitempty() string {
	if o == nil || IsNil(o.Bodyomitempty) {
		var ret string
		return ret
	}
	return *o.Bodyomitempty
}

// GetBodyomitemptyOk returns a tuple with the Bodyomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkillUIDescriptor) GetBodyomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Bodyomitempty) {
		return nil, false
	}
	return o.Bodyomitempty, true
}

// HasBodyomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasBodyomitempty() bool {
	if o != nil && !IsNil(o.Bodyomitempty) {
		return true
	}

	return false
}

// SetBodyomitempty gets a reference to the given string and assigns it to the Bodyomitempty field.
func (o *SkillUIDescriptor) SetBodyomitempty(v string) {
	o.Bodyomitempty = &v
}

// GetFieldsomitempty returns the Fieldsomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetFieldsomitempty() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Fieldsomitempty
}

// GetFieldsomitemptyOk returns a tuple with the Fieldsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetFieldsomitemptyOk() ([]string, bool) {
	if o == nil || IsNil(o.Fieldsomitempty) {
		return nil, false
	}
	return o.Fieldsomitempty, true
}

// HasFieldsomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasFieldsomitempty() bool {
	if o != nil && !IsNil(o.Fieldsomitempty) {
		return true
	}

	return false
}

// SetFieldsomitempty gets a reference to the given []string and assigns it to the Fieldsomitempty field.
func (o *SkillUIDescriptor) SetFieldsomitempty(v []string) {
	o.Fieldsomitempty = v
}

// GetActionsomitempty returns the Actionsomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SkillUIDescriptor) GetActionsomitempty() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Actionsomitempty
}

// GetActionsomitemptyOk returns a tuple with the Actionsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SkillUIDescriptor) GetActionsomitemptyOk() ([]string, bool) {
	if o == nil || IsNil(o.Actionsomitempty) {
		return nil, false
	}
	return o.Actionsomitempty, true
}

// HasActionsomitempty returns a boolean if a field has been set.
func (o *SkillUIDescriptor) HasActionsomitempty() bool {
	if o != nil && !IsNil(o.Actionsomitempty) {
		return true
	}

	return false
}

// SetActionsomitempty gets a reference to the given []string and assigns it to the Actionsomitempty field.
func (o *SkillUIDescriptor) SetActionsomitempty(v []string) {
	o.Actionsomitempty = v
}

func (o SkillUIDescriptor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkillUIDescriptor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["ui_type"] = o.UiType
	if !IsNil(o.Categoryomitempty) {
		toSerialize["category,omitempty"] = o.Categoryomitempty
	}
	if o.Tagsomitempty.IsSet() {
		toSerialize["tags,omitempty"] = o.Tagsomitempty.Get()
	}
	if o.Examplesomitempty.IsSet() {
		toSerialize["examples,omitempty"] = o.Examplesomitempty.Get()
	}
	if !IsNil(o.RiskLevelomitempty) {
		toSerialize["risk_level,omitempty"] = o.RiskLevelomitempty
	}
	if !IsNil(o.Bodyomitempty) {
		toSerialize["body,omitempty"] = o.Bodyomitempty
	}
	if o.Fieldsomitempty != nil {
		toSerialize["fields,omitempty"] = o.Fieldsomitempty
	}
	if o.Actionsomitempty != nil {
		toSerialize["actions,omitempty"] = o.Actionsomitempty
	}
	return toSerialize, nil
}

func (o *SkillUIDescriptor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"slug",
		"name",
		"description",
		"ui_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkillUIDescriptor := _SkillUIDescriptor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkillUIDescriptor)

	if err != nil {
		return err
	}

	*o = SkillUIDescriptor(varSkillUIDescriptor)

	return err
}

type NullableSkillUIDescriptor struct {
	value *SkillUIDescriptor
	isSet bool
}

func (v NullableSkillUIDescriptor) Get() *SkillUIDescriptor {
	return v.value
}

func (v *NullableSkillUIDescriptor) Set(val *SkillUIDescriptor) {
	v.value = val
	v.isSet = true
}

func (v NullableSkillUIDescriptor) IsSet() bool {
	return v.isSet
}

func (v *NullableSkillUIDescriptor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkillUIDescriptor(val *SkillUIDescriptor) *NullableSkillUIDescriptor {
	return &NullableSkillUIDescriptor{value: val, isSet: true}
}

func (v NullableSkillUIDescriptor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkillUIDescriptor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


