/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UIFieldDef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UIFieldDef{}

// UIFieldDef struct for UIFieldDef
type UIFieldDef struct {
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Requiredomitempty *bool `json:"required,omitempty,omitempty"`
	Defaultomitempty map[string]interface{} `json:"default,omitempty,omitempty"`
	Optionsomitempty NullableString `json:"options,omitempty,omitempty"`
	Placeholderomitempty *string `json:"placeholder,omitempty,omitempty"`
	Helpomitempty *string `json:"help,omitempty,omitempty"`
}

type _UIFieldDef UIFieldDef

// NewUIFieldDef instantiates a new UIFieldDef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUIFieldDef(name string, label string, type_ string) *UIFieldDef {
	this := UIFieldDef{}
	this.Name = name
	this.Label = label
	this.Type = type_
	return &this
}

// NewUIFieldDefWithDefaults instantiates a new UIFieldDef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUIFieldDefWithDefaults() *UIFieldDef {
	this := UIFieldDef{}
	return &this
}

// GetName returns the Name field value
func (o *UIFieldDef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UIFieldDef) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *UIFieldDef) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *UIFieldDef) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *UIFieldDef) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UIFieldDef) SetType(v string) {
	o.Type = v
}

// GetRequiredomitempty returns the Requiredomitempty field value if set, zero value otherwise.
func (o *UIFieldDef) GetRequiredomitempty() bool {
	if o == nil || IsNil(o.Requiredomitempty) {
		var ret bool
		return ret
	}
	return *o.Requiredomitempty
}

// GetRequiredomitemptyOk returns a tuple with the Requiredomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetRequiredomitemptyOk() (*bool, bool) {
	if o == nil || IsNil(o.Requiredomitempty) {
		return nil, false
	}
	return o.Requiredomitempty, true
}

// HasRequiredomitempty returns a boolean if a field has been set.
func (o *UIFieldDef) HasRequiredomitempty() bool {
	if o != nil && !IsNil(o.Requiredomitempty) {
		return true
	}

	return false
}

// SetRequiredomitempty gets a reference to the given bool and assigns it to the Requiredomitempty field.
func (o *UIFieldDef) SetRequiredomitempty(v bool) {
	o.Requiredomitempty = &v
}

// GetDefaultomitempty returns the Defaultomitempty field value if set, zero value otherwise.
func (o *UIFieldDef) GetDefaultomitempty() map[string]interface{} {
	if o == nil || IsNil(o.Defaultomitempty) {
		var ret map[string]interface{}
		return ret
	}
	return o.Defaultomitempty
}

// GetDefaultomitemptyOk returns a tuple with the Defaultomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetDefaultomitemptyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Defaultomitempty) {
		return map[string]interface{}{}, false
	}
	return o.Defaultomitempty, true
}

// HasDefaultomitempty returns a boolean if a field has been set.
func (o *UIFieldDef) HasDefaultomitempty() bool {
	if o != nil && !IsNil(o.Defaultomitempty) {
		return true
	}

	return false
}

// SetDefaultomitempty gets a reference to the given map[string]interface{} and assigns it to the Defaultomitempty field.
func (o *UIFieldDef) SetDefaultomitempty(v map[string]interface{}) {
	o.Defaultomitempty = v
}

// GetOptionsomitempty returns the Optionsomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UIFieldDef) GetOptionsomitempty() string {
	if o == nil || IsNil(o.Optionsomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.Optionsomitempty.Get()
}

// GetOptionsomitemptyOk returns a tuple with the Optionsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UIFieldDef) GetOptionsomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Optionsomitempty.Get(), o.Optionsomitempty.IsSet()
}

// HasOptionsomitempty returns a boolean if a field has been set.
func (o *UIFieldDef) HasOptionsomitempty() bool {
	if o != nil && o.Optionsomitempty.IsSet() {
		return true
	}

	return false
}

// SetOptionsomitempty gets a reference to the given NullableString and assigns it to the Optionsomitempty field.
func (o *UIFieldDef) SetOptionsomitempty(v string) {
	o.Optionsomitempty.Set(&v)
}
// SetOptionsomitemptyNil sets the value for Optionsomitempty to be an explicit nil
func (o *UIFieldDef) SetOptionsomitemptyNil() {
	o.Optionsomitempty.Set(nil)
}

// UnsetOptionsomitempty ensures that no value is present for Optionsomitempty, not even an explicit nil
func (o *UIFieldDef) UnsetOptionsomitempty() {
	o.Optionsomitempty.Unset()
}

// GetPlaceholderomitempty returns the Placeholderomitempty field value if set, zero value otherwise.
func (o *UIFieldDef) GetPlaceholderomitempty() string {
	if o == nil || IsNil(o.Placeholderomitempty) {
		var ret string
		return ret
	}
	return *o.Placeholderomitempty
}

// GetPlaceholderomitemptyOk returns a tuple with the Placeholderomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetPlaceholderomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Placeholderomitempty) {
		return nil, false
	}
	return o.Placeholderomitempty, true
}

// HasPlaceholderomitempty returns a boolean if a field has been set.
func (o *UIFieldDef) HasPlaceholderomitempty() bool {
	if o != nil && !IsNil(o.Placeholderomitempty) {
		return true
	}

	return false
}

// SetPlaceholderomitempty gets a reference to the given string and assigns it to the Placeholderomitempty field.
func (o *UIFieldDef) SetPlaceholderomitempty(v string) {
	o.Placeholderomitempty = &v
}

// GetHelpomitempty returns the Helpomitempty field value if set, zero value otherwise.
func (o *UIFieldDef) GetHelpomitempty() string {
	if o == nil || IsNil(o.Helpomitempty) {
		var ret string
		return ret
	}
	return *o.Helpomitempty
}

// GetHelpomitemptyOk returns a tuple with the Helpomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetHelpomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Helpomitempty) {
		return nil, false
	}
	return o.Helpomitempty, true
}

// HasHelpomitempty returns a boolean if a field has been set.
func (o *UIFieldDef) HasHelpomitempty() bool {
	if o != nil && !IsNil(o.Helpomitempty) {
		return true
	}

	return false
}

// SetHelpomitempty gets a reference to the given string and assigns it to the Helpomitempty field.
func (o *UIFieldDef) SetHelpomitempty(v string) {
	o.Helpomitempty = &v
}

func (o UIFieldDef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UIFieldDef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	if !IsNil(o.Requiredomitempty) {
		toSerialize["required,omitempty"] = o.Requiredomitempty
	}
	if !IsNil(o.Defaultomitempty) {
		toSerialize["default,omitempty"] = o.Defaultomitempty
	}
	if o.Optionsomitempty.IsSet() {
		toSerialize["options,omitempty"] = o.Optionsomitempty.Get()
	}
	if !IsNil(o.Placeholderomitempty) {
		toSerialize["placeholder,omitempty"] = o.Placeholderomitempty
	}
	if !IsNil(o.Helpomitempty) {
		toSerialize["help,omitempty"] = o.Helpomitempty
	}
	return toSerialize, nil
}

func (o *UIFieldDef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUIFieldDef := _UIFieldDef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUIFieldDef)

	if err != nil {
		return err
	}

	*o = UIFieldDef(varUIFieldDef)

	return err
}

type NullableUIFieldDef struct {
	value *UIFieldDef
	isSet bool
}

func (v NullableUIFieldDef) Get() *UIFieldDef {
	return v.value
}

func (v *NullableUIFieldDef) Set(val *UIFieldDef) {
	v.value = val
	v.isSet = true
}

func (v NullableUIFieldDef) IsSet() bool {
	return v.isSet
}

func (v *NullableUIFieldDef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUIFieldDef(val *UIFieldDef) *NullableUIFieldDef {
	return &NullableUIFieldDef{value: val, isSet: true}
}

func (v NullableUIFieldDef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUIFieldDef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


