/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTaskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTaskRequest{}

// UpdateTaskRequest struct for UpdateTaskRequest
type UpdateTaskRequest struct {
	Id string `json:"id"`
	State *string `json:"state,omitempty"`
	Name *string `json:"name,omitempty"`
}

type _UpdateTaskRequest UpdateTaskRequest

// NewUpdateTaskRequest instantiates a new UpdateTaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTaskRequest(id string) *UpdateTaskRequest {
	this := UpdateTaskRequest{}
	this.Id = id
	return &this
}

// NewUpdateTaskRequestWithDefaults instantiates a new UpdateTaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTaskRequestWithDefaults() *UpdateTaskRequest {
	this := UpdateTaskRequest{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateTaskRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateTaskRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateTaskRequest) SetId(v string) {
	o.Id = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *UpdateTaskRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTaskRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *UpdateTaskRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *UpdateTaskRequest) SetState(v string) {
	o.State = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateTaskRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTaskRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateTaskRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateTaskRequest) SetName(v string) {
	o.Name = &v
}

func (o UpdateTaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTaskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

func (o *UpdateTaskRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTaskRequest := _UpdateTaskRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTaskRequest)

	if err != nil {
		return err
	}

	*o = UpdateTaskRequest(varUpdateTaskRequest)

	return err
}

type NullableUpdateTaskRequest struct {
	value *UpdateTaskRequest
	isSet bool
}

func (v NullableUpdateTaskRequest) Get() *UpdateTaskRequest {
	return v.value
}

func (v *NullableUpdateTaskRequest) Set(val *UpdateTaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTaskRequest(val *UpdateTaskRequest) *NullableUpdateTaskRequest {
	return &NullableUpdateTaskRequest{value: val, isSet: true}
}

func (v NullableUpdateTaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


