/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VectorSearchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VectorSearchRequest{}

// VectorSearchRequest struct for VectorSearchRequest
type VectorSearchRequest struct {
	Query string `json:"query"`
	Limit *int32 `json:"limit,omitempty"`
	ShardTypes NullableString `json:"shard_types,omitempty"`
}

type _VectorSearchRequest VectorSearchRequest

// NewVectorSearchRequest instantiates a new VectorSearchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVectorSearchRequest(query string) *VectorSearchRequest {
	this := VectorSearchRequest{}
	this.Query = query
	return &this
}

// NewVectorSearchRequestWithDefaults instantiates a new VectorSearchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVectorSearchRequestWithDefaults() *VectorSearchRequest {
	this := VectorSearchRequest{}
	return &this
}

// GetQuery returns the Query field value
func (o *VectorSearchRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *VectorSearchRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *VectorSearchRequest) SetQuery(v string) {
	o.Query = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *VectorSearchRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VectorSearchRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *VectorSearchRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *VectorSearchRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetShardTypes returns the ShardTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VectorSearchRequest) GetShardTypes() string {
	if o == nil || IsNil(o.ShardTypes.Get()) {
		var ret string
		return ret
	}
	return *o.ShardTypes.Get()
}

// GetShardTypesOk returns a tuple with the ShardTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VectorSearchRequest) GetShardTypesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShardTypes.Get(), o.ShardTypes.IsSet()
}

// HasShardTypes returns a boolean if a field has been set.
func (o *VectorSearchRequest) HasShardTypes() bool {
	if o != nil && o.ShardTypes.IsSet() {
		return true
	}

	return false
}

// SetShardTypes gets a reference to the given NullableString and assigns it to the ShardTypes field.
func (o *VectorSearchRequest) SetShardTypes(v string) {
	o.ShardTypes.Set(&v)
}
// SetShardTypesNil sets the value for ShardTypes to be an explicit nil
func (o *VectorSearchRequest) SetShardTypesNil() {
	o.ShardTypes.Set(nil)
}

// UnsetShardTypes ensures that no value is present for ShardTypes, not even an explicit nil
func (o *VectorSearchRequest) UnsetShardTypes() {
	o.ShardTypes.Unset()
}

func (o VectorSearchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VectorSearchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if o.ShardTypes.IsSet() {
		toSerialize["shard_types"] = o.ShardTypes.Get()
	}
	return toSerialize, nil
}

func (o *VectorSearchRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVectorSearchRequest := _VectorSearchRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVectorSearchRequest)

	if err != nil {
		return err
	}

	*o = VectorSearchRequest(varVectorSearchRequest)

	return err
}

type NullableVectorSearchRequest struct {
	value *VectorSearchRequest
	isSet bool
}

func (v NullableVectorSearchRequest) Get() *VectorSearchRequest {
	return v.value
}

func (v *NullableVectorSearchRequest) Set(val *VectorSearchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVectorSearchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVectorSearchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVectorSearchRequest(val *VectorSearchRequest) *NullableVectorSearchRequest {
	return &NullableVectorSearchRequest{value: val, isSet: true}
}

func (v NullableVectorSearchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVectorSearchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


