/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClaimRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClaimRequest{}

// ClaimRequest struct for ClaimRequest
type ClaimRequest struct {
	WorkerId string `json:"worker_id"`
	Capabilities NullableString `json:"capabilities,omitempty"`
}

type _ClaimRequest ClaimRequest

// NewClaimRequest instantiates a new ClaimRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClaimRequest(workerId string) *ClaimRequest {
	this := ClaimRequest{}
	this.WorkerId = workerId
	return &this
}

// NewClaimRequestWithDefaults instantiates a new ClaimRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClaimRequestWithDefaults() *ClaimRequest {
	this := ClaimRequest{}
	return &this
}

// GetWorkerId returns the WorkerId field value
func (o *ClaimRequest) GetWorkerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkerId
}

// GetWorkerIdOk returns a tuple with the WorkerId field value
// and a boolean to check if the value has been set.
func (o *ClaimRequest) GetWorkerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkerId, true
}

// SetWorkerId sets field value
func (o *ClaimRequest) SetWorkerId(v string) {
	o.WorkerId = v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClaimRequest) GetCapabilities() string {
	if o == nil || IsNil(o.Capabilities.Get()) {
		var ret string
		return ret
	}
	return *o.Capabilities.Get()
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClaimRequest) GetCapabilitiesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Capabilities.Get(), o.Capabilities.IsSet()
}

// HasCapabilities returns a boolean if a field has been set.
func (o *ClaimRequest) HasCapabilities() bool {
	if o != nil && o.Capabilities.IsSet() {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given NullableString and assigns it to the Capabilities field.
func (o *ClaimRequest) SetCapabilities(v string) {
	o.Capabilities.Set(&v)
}
// SetCapabilitiesNil sets the value for Capabilities to be an explicit nil
func (o *ClaimRequest) SetCapabilitiesNil() {
	o.Capabilities.Set(nil)
}

// UnsetCapabilities ensures that no value is present for Capabilities, not even an explicit nil
func (o *ClaimRequest) UnsetCapabilities() {
	o.Capabilities.Unset()
}

func (o ClaimRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClaimRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["worker_id"] = o.WorkerId
	if o.Capabilities.IsSet() {
		toSerialize["capabilities"] = o.Capabilities.Get()
	}
	return toSerialize, nil
}

func (o *ClaimRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"worker_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClaimRequest := _ClaimRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClaimRequest)

	if err != nil {
		return err
	}

	*o = ClaimRequest(varClaimRequest)

	return err
}

type NullableClaimRequest struct {
	value *ClaimRequest
	isSet bool
}

func (v NullableClaimRequest) Get() *ClaimRequest {
	return v.value
}

func (v *NullableClaimRequest) Set(val *ClaimRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClaimRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClaimRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClaimRequest(val *ClaimRequest) *NullableClaimRequest {
	return &NullableClaimRequest{value: val, isSet: true}
}

func (v NullableClaimRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClaimRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


