/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOptions{}

// ListOptions struct for ListOptions
type ListOptions struct {
	Limitomitempty *int32 `json:"limit,omitempty,omitempty"`
	Offsetomitempty *int32 `json:"offset,omitempty,omitempty"`
	Filteromitempty *string `json:"filter,omitempty,omitempty"`
}

// NewListOptions instantiates a new ListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOptions() *ListOptions {
	this := ListOptions{}
	return &this
}

// NewListOptionsWithDefaults instantiates a new ListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOptionsWithDefaults() *ListOptions {
	this := ListOptions{}
	return &this
}

// GetLimitomitempty returns the Limitomitempty field value if set, zero value otherwise.
func (o *ListOptions) GetLimitomitempty() int32 {
	if o == nil || IsNil(o.Limitomitempty) {
		var ret int32
		return ret
	}
	return *o.Limitomitempty
}

// GetLimitomitemptyOk returns a tuple with the Limitomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOptions) GetLimitomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.Limitomitempty) {
		return nil, false
	}
	return o.Limitomitempty, true
}

// HasLimitomitempty returns a boolean if a field has been set.
func (o *ListOptions) HasLimitomitempty() bool {
	if o != nil && !IsNil(o.Limitomitempty) {
		return true
	}

	return false
}

// SetLimitomitempty gets a reference to the given int32 and assigns it to the Limitomitempty field.
func (o *ListOptions) SetLimitomitempty(v int32) {
	o.Limitomitempty = &v
}

// GetOffsetomitempty returns the Offsetomitempty field value if set, zero value otherwise.
func (o *ListOptions) GetOffsetomitempty() int32 {
	if o == nil || IsNil(o.Offsetomitempty) {
		var ret int32
		return ret
	}
	return *o.Offsetomitempty
}

// GetOffsetomitemptyOk returns a tuple with the Offsetomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOptions) GetOffsetomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.Offsetomitempty) {
		return nil, false
	}
	return o.Offsetomitempty, true
}

// HasOffsetomitempty returns a boolean if a field has been set.
func (o *ListOptions) HasOffsetomitempty() bool {
	if o != nil && !IsNil(o.Offsetomitempty) {
		return true
	}

	return false
}

// SetOffsetomitempty gets a reference to the given int32 and assigns it to the Offsetomitempty field.
func (o *ListOptions) SetOffsetomitempty(v int32) {
	o.Offsetomitempty = &v
}

// GetFilteromitempty returns the Filteromitempty field value if set, zero value otherwise.
func (o *ListOptions) GetFilteromitempty() string {
	if o == nil || IsNil(o.Filteromitempty) {
		var ret string
		return ret
	}
	return *o.Filteromitempty
}

// GetFilteromitemptyOk returns a tuple with the Filteromitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOptions) GetFilteromitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Filteromitempty) {
		return nil, false
	}
	return o.Filteromitempty, true
}

// HasFilteromitempty returns a boolean if a field has been set.
func (o *ListOptions) HasFilteromitempty() bool {
	if o != nil && !IsNil(o.Filteromitempty) {
		return true
	}

	return false
}

// SetFilteromitempty gets a reference to the given string and assigns it to the Filteromitempty field.
func (o *ListOptions) SetFilteromitempty(v string) {
	o.Filteromitempty = &v
}

func (o ListOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limitomitempty) {
		toSerialize["limit,omitempty"] = o.Limitomitempty
	}
	if !IsNil(o.Offsetomitempty) {
		toSerialize["offset,omitempty"] = o.Offsetomitempty
	}
	if !IsNil(o.Filteromitempty) {
		toSerialize["filter,omitempty"] = o.Filteromitempty
	}
	return toSerialize, nil
}

type NullableListOptions struct {
	value *ListOptions
	isSet bool
}

func (v NullableListOptions) Get() *ListOptions {
	return v.value
}

func (v *NullableListOptions) Set(val *ListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOptions(val *ListOptions) *NullableListOptions {
	return &NullableListOptions{value: val, isSet: true}
}

func (v NullableListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


