/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the Config type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Config{}

// Config struct for Config
type Config struct {
	Bus map[string]interface{} `json:"Bus,omitempty"`
	AgentRegistry map[string]interface{} `json:"AgentRegistry,omitempty"`
	Queue map[string]interface{} `json:"Queue,omitempty"`
	MemoryManager map[string]interface{} `json:"MemoryManager,omitempty"`
	TaskRegistry map[string]interface{} `json:"TaskRegistry,omitempty"`
	SessionStore map[string]interface{} `json:"SessionStore,omitempty"`
	WorkerPool map[string]interface{} `json:"WorkerPool,omitempty"`
	SkillRegistry map[string]interface{} `json:"SkillRegistry,omitempty"`
	SkillExecutor map[string]interface{} `json:"SkillExecutor,omitempty"`
	TemplateRegistry map[string]interface{} `json:"TemplateRegistry,omitempty"`
	SelfImprove map[string]interface{} `json:"SelfImprove,omitempty"`
	TokenCache map[string]interface{} `json:"TokenCache,omitempty"`
	SecurityChecker map[string]interface{} `json:"SecurityChecker,omitempty"`
	Scheduler map[string]interface{} `json:"Scheduler,omitempty"`
	CalendarClient map[string]interface{} `json:"CalendarClient,omitempty"`
	DaemonController map[string]interface{} `json:"DaemonController,omitempty"`
	RuntimeManager map[string]interface{} `json:"RuntimeManager,omitempty"`
	WorkingDir *string `json:"WorkingDir,omitempty"`
	PidFile *string `json:"PidFile,omitempty"`
	StateDir *string `json:"StateDir,omitempty"`
	BinPath *string `json:"BinPath,omitempty"`
	ProjectManager map[string]interface{} `json:"ProjectManager,omitempty"`
	PlanManager map[string]interface{} `json:"PlanManager,omitempty"`
	PlanStore map[string]interface{} `json:"PlanStore,omitempty"`
}

// NewConfig instantiates a new Config object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfig() *Config {
	this := Config{}
	return &this
}

// NewConfigWithDefaults instantiates a new Config object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigWithDefaults() *Config {
	this := Config{}
	return &this
}

// GetBus returns the Bus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetBus() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Bus
}

// GetBusOk returns a tuple with the Bus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetBusOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Bus) {
		return map[string]interface{}{}, false
	}
	return o.Bus, true
}

// HasBus returns a boolean if a field has been set.
func (o *Config) HasBus() bool {
	if o != nil && !IsNil(o.Bus) {
		return true
	}

	return false
}

// SetBus gets a reference to the given map[string]interface{} and assigns it to the Bus field.
func (o *Config) SetBus(v map[string]interface{}) {
	o.Bus = v
}

// GetAgentRegistry returns the AgentRegistry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetAgentRegistry() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AgentRegistry
}

// GetAgentRegistryOk returns a tuple with the AgentRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetAgentRegistryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AgentRegistry) {
		return map[string]interface{}{}, false
	}
	return o.AgentRegistry, true
}

// HasAgentRegistry returns a boolean if a field has been set.
func (o *Config) HasAgentRegistry() bool {
	if o != nil && !IsNil(o.AgentRegistry) {
		return true
	}

	return false
}

// SetAgentRegistry gets a reference to the given map[string]interface{} and assigns it to the AgentRegistry field.
func (o *Config) SetAgentRegistry(v map[string]interface{}) {
	o.AgentRegistry = v
}

// GetQueue returns the Queue field value if set, zero value otherwise.
func (o *Config) GetQueue() map[string]interface{} {
	if o == nil || IsNil(o.Queue) {
		var ret map[string]interface{}
		return ret
	}
	return o.Queue
}

// GetQueueOk returns a tuple with the Queue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetQueueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Queue) {
		return map[string]interface{}{}, false
	}
	return o.Queue, true
}

// HasQueue returns a boolean if a field has been set.
func (o *Config) HasQueue() bool {
	if o != nil && !IsNil(o.Queue) {
		return true
	}

	return false
}

// SetQueue gets a reference to the given map[string]interface{} and assigns it to the Queue field.
func (o *Config) SetQueue(v map[string]interface{}) {
	o.Queue = v
}

// GetMemoryManager returns the MemoryManager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetMemoryManager() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.MemoryManager
}

// GetMemoryManagerOk returns a tuple with the MemoryManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetMemoryManagerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.MemoryManager) {
		return map[string]interface{}{}, false
	}
	return o.MemoryManager, true
}

// HasMemoryManager returns a boolean if a field has been set.
func (o *Config) HasMemoryManager() bool {
	if o != nil && !IsNil(o.MemoryManager) {
		return true
	}

	return false
}

// SetMemoryManager gets a reference to the given map[string]interface{} and assigns it to the MemoryManager field.
func (o *Config) SetMemoryManager(v map[string]interface{}) {
	o.MemoryManager = v
}

// GetTaskRegistry returns the TaskRegistry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetTaskRegistry() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TaskRegistry
}

// GetTaskRegistryOk returns a tuple with the TaskRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetTaskRegistryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TaskRegistry) {
		return map[string]interface{}{}, false
	}
	return o.TaskRegistry, true
}

// HasTaskRegistry returns a boolean if a field has been set.
func (o *Config) HasTaskRegistry() bool {
	if o != nil && !IsNil(o.TaskRegistry) {
		return true
	}

	return false
}

// SetTaskRegistry gets a reference to the given map[string]interface{} and assigns it to the TaskRegistry field.
func (o *Config) SetTaskRegistry(v map[string]interface{}) {
	o.TaskRegistry = v
}

// GetSessionStore returns the SessionStore field value if set, zero value otherwise.
func (o *Config) GetSessionStore() map[string]interface{} {
	if o == nil || IsNil(o.SessionStore) {
		var ret map[string]interface{}
		return ret
	}
	return o.SessionStore
}

// GetSessionStoreOk returns a tuple with the SessionStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetSessionStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SessionStore) {
		return map[string]interface{}{}, false
	}
	return o.SessionStore, true
}

// HasSessionStore returns a boolean if a field has been set.
func (o *Config) HasSessionStore() bool {
	if o != nil && !IsNil(o.SessionStore) {
		return true
	}

	return false
}

// SetSessionStore gets a reference to the given map[string]interface{} and assigns it to the SessionStore field.
func (o *Config) SetSessionStore(v map[string]interface{}) {
	o.SessionStore = v
}

// GetWorkerPool returns the WorkerPool field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetWorkerPool() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.WorkerPool
}

// GetWorkerPoolOk returns a tuple with the WorkerPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetWorkerPoolOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.WorkerPool) {
		return map[string]interface{}{}, false
	}
	return o.WorkerPool, true
}

// HasWorkerPool returns a boolean if a field has been set.
func (o *Config) HasWorkerPool() bool {
	if o != nil && !IsNil(o.WorkerPool) {
		return true
	}

	return false
}

// SetWorkerPool gets a reference to the given map[string]interface{} and assigns it to the WorkerPool field.
func (o *Config) SetWorkerPool(v map[string]interface{}) {
	o.WorkerPool = v
}

// GetSkillRegistry returns the SkillRegistry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetSkillRegistry() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SkillRegistry
}

// GetSkillRegistryOk returns a tuple with the SkillRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetSkillRegistryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SkillRegistry) {
		return map[string]interface{}{}, false
	}
	return o.SkillRegistry, true
}

// HasSkillRegistry returns a boolean if a field has been set.
func (o *Config) HasSkillRegistry() bool {
	if o != nil && !IsNil(o.SkillRegistry) {
		return true
	}

	return false
}

// SetSkillRegistry gets a reference to the given map[string]interface{} and assigns it to the SkillRegistry field.
func (o *Config) SetSkillRegistry(v map[string]interface{}) {
	o.SkillRegistry = v
}

// GetSkillExecutor returns the SkillExecutor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetSkillExecutor() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SkillExecutor
}

// GetSkillExecutorOk returns a tuple with the SkillExecutor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetSkillExecutorOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SkillExecutor) {
		return map[string]interface{}{}, false
	}
	return o.SkillExecutor, true
}

// HasSkillExecutor returns a boolean if a field has been set.
func (o *Config) HasSkillExecutor() bool {
	if o != nil && !IsNil(o.SkillExecutor) {
		return true
	}

	return false
}

// SetSkillExecutor gets a reference to the given map[string]interface{} and assigns it to the SkillExecutor field.
func (o *Config) SetSkillExecutor(v map[string]interface{}) {
	o.SkillExecutor = v
}

// GetTemplateRegistry returns the TemplateRegistry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetTemplateRegistry() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TemplateRegistry
}

// GetTemplateRegistryOk returns a tuple with the TemplateRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetTemplateRegistryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TemplateRegistry) {
		return map[string]interface{}{}, false
	}
	return o.TemplateRegistry, true
}

// HasTemplateRegistry returns a boolean if a field has been set.
func (o *Config) HasTemplateRegistry() bool {
	if o != nil && !IsNil(o.TemplateRegistry) {
		return true
	}

	return false
}

// SetTemplateRegistry gets a reference to the given map[string]interface{} and assigns it to the TemplateRegistry field.
func (o *Config) SetTemplateRegistry(v map[string]interface{}) {
	o.TemplateRegistry = v
}

// GetSelfImprove returns the SelfImprove field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetSelfImprove() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SelfImprove
}

// GetSelfImproveOk returns a tuple with the SelfImprove field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetSelfImproveOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SelfImprove) {
		return map[string]interface{}{}, false
	}
	return o.SelfImprove, true
}

// HasSelfImprove returns a boolean if a field has been set.
func (o *Config) HasSelfImprove() bool {
	if o != nil && !IsNil(o.SelfImprove) {
		return true
	}

	return false
}

// SetSelfImprove gets a reference to the given map[string]interface{} and assigns it to the SelfImprove field.
func (o *Config) SetSelfImprove(v map[string]interface{}) {
	o.SelfImprove = v
}

// GetTokenCache returns the TokenCache field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetTokenCache() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TokenCache
}

// GetTokenCacheOk returns a tuple with the TokenCache field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetTokenCacheOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TokenCache) {
		return map[string]interface{}{}, false
	}
	return o.TokenCache, true
}

// HasTokenCache returns a boolean if a field has been set.
func (o *Config) HasTokenCache() bool {
	if o != nil && !IsNil(o.TokenCache) {
		return true
	}

	return false
}

// SetTokenCache gets a reference to the given map[string]interface{} and assigns it to the TokenCache field.
func (o *Config) SetTokenCache(v map[string]interface{}) {
	o.TokenCache = v
}

// GetSecurityChecker returns the SecurityChecker field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetSecurityChecker() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SecurityChecker
}

// GetSecurityCheckerOk returns a tuple with the SecurityChecker field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetSecurityCheckerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SecurityChecker) {
		return map[string]interface{}{}, false
	}
	return o.SecurityChecker, true
}

// HasSecurityChecker returns a boolean if a field has been set.
func (o *Config) HasSecurityChecker() bool {
	if o != nil && !IsNil(o.SecurityChecker) {
		return true
	}

	return false
}

// SetSecurityChecker gets a reference to the given map[string]interface{} and assigns it to the SecurityChecker field.
func (o *Config) SetSecurityChecker(v map[string]interface{}) {
	o.SecurityChecker = v
}

// GetScheduler returns the Scheduler field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetScheduler() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Scheduler
}

// GetSchedulerOk returns a tuple with the Scheduler field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetSchedulerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Scheduler) {
		return map[string]interface{}{}, false
	}
	return o.Scheduler, true
}

// HasScheduler returns a boolean if a field has been set.
func (o *Config) HasScheduler() bool {
	if o != nil && !IsNil(o.Scheduler) {
		return true
	}

	return false
}

// SetScheduler gets a reference to the given map[string]interface{} and assigns it to the Scheduler field.
func (o *Config) SetScheduler(v map[string]interface{}) {
	o.Scheduler = v
}

// GetCalendarClient returns the CalendarClient field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetCalendarClient() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.CalendarClient
}

// GetCalendarClientOk returns a tuple with the CalendarClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetCalendarClientOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CalendarClient) {
		return map[string]interface{}{}, false
	}
	return o.CalendarClient, true
}

// HasCalendarClient returns a boolean if a field has been set.
func (o *Config) HasCalendarClient() bool {
	if o != nil && !IsNil(o.CalendarClient) {
		return true
	}

	return false
}

// SetCalendarClient gets a reference to the given map[string]interface{} and assigns it to the CalendarClient field.
func (o *Config) SetCalendarClient(v map[string]interface{}) {
	o.CalendarClient = v
}

// GetDaemonController returns the DaemonController field value if set, zero value otherwise.
func (o *Config) GetDaemonController() map[string]interface{} {
	if o == nil || IsNil(o.DaemonController) {
		var ret map[string]interface{}
		return ret
	}
	return o.DaemonController
}

// GetDaemonControllerOk returns a tuple with the DaemonController field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetDaemonControllerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DaemonController) {
		return map[string]interface{}{}, false
	}
	return o.DaemonController, true
}

// HasDaemonController returns a boolean if a field has been set.
func (o *Config) HasDaemonController() bool {
	if o != nil && !IsNil(o.DaemonController) {
		return true
	}

	return false
}

// SetDaemonController gets a reference to the given map[string]interface{} and assigns it to the DaemonController field.
func (o *Config) SetDaemonController(v map[string]interface{}) {
	o.DaemonController = v
}

// GetRuntimeManager returns the RuntimeManager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetRuntimeManager() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.RuntimeManager
}

// GetRuntimeManagerOk returns a tuple with the RuntimeManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetRuntimeManagerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.RuntimeManager) {
		return map[string]interface{}{}, false
	}
	return o.RuntimeManager, true
}

// HasRuntimeManager returns a boolean if a field has been set.
func (o *Config) HasRuntimeManager() bool {
	if o != nil && !IsNil(o.RuntimeManager) {
		return true
	}

	return false
}

// SetRuntimeManager gets a reference to the given map[string]interface{} and assigns it to the RuntimeManager field.
func (o *Config) SetRuntimeManager(v map[string]interface{}) {
	o.RuntimeManager = v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise.
func (o *Config) GetWorkingDir() string {
	if o == nil || IsNil(o.WorkingDir) {
		var ret string
		return ret
	}
	return *o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetWorkingDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *Config) HasWorkingDir() bool {
	if o != nil && !IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given string and assigns it to the WorkingDir field.
func (o *Config) SetWorkingDir(v string) {
	o.WorkingDir = &v
}

// GetPidFile returns the PidFile field value if set, zero value otherwise.
func (o *Config) GetPidFile() string {
	if o == nil || IsNil(o.PidFile) {
		var ret string
		return ret
	}
	return *o.PidFile
}

// GetPidFileOk returns a tuple with the PidFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetPidFileOk() (*string, bool) {
	if o == nil || IsNil(o.PidFile) {
		return nil, false
	}
	return o.PidFile, true
}

// HasPidFile returns a boolean if a field has been set.
func (o *Config) HasPidFile() bool {
	if o != nil && !IsNil(o.PidFile) {
		return true
	}

	return false
}

// SetPidFile gets a reference to the given string and assigns it to the PidFile field.
func (o *Config) SetPidFile(v string) {
	o.PidFile = &v
}

// GetStateDir returns the StateDir field value if set, zero value otherwise.
func (o *Config) GetStateDir() string {
	if o == nil || IsNil(o.StateDir) {
		var ret string
		return ret
	}
	return *o.StateDir
}

// GetStateDirOk returns a tuple with the StateDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetStateDirOk() (*string, bool) {
	if o == nil || IsNil(o.StateDir) {
		return nil, false
	}
	return o.StateDir, true
}

// HasStateDir returns a boolean if a field has been set.
func (o *Config) HasStateDir() bool {
	if o != nil && !IsNil(o.StateDir) {
		return true
	}

	return false
}

// SetStateDir gets a reference to the given string and assigns it to the StateDir field.
func (o *Config) SetStateDir(v string) {
	o.StateDir = &v
}

// GetBinPath returns the BinPath field value if set, zero value otherwise.
func (o *Config) GetBinPath() string {
	if o == nil || IsNil(o.BinPath) {
		var ret string
		return ret
	}
	return *o.BinPath
}

// GetBinPathOk returns a tuple with the BinPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetBinPathOk() (*string, bool) {
	if o == nil || IsNil(o.BinPath) {
		return nil, false
	}
	return o.BinPath, true
}

// HasBinPath returns a boolean if a field has been set.
func (o *Config) HasBinPath() bool {
	if o != nil && !IsNil(o.BinPath) {
		return true
	}

	return false
}

// SetBinPath gets a reference to the given string and assigns it to the BinPath field.
func (o *Config) SetBinPath(v string) {
	o.BinPath = &v
}

// GetProjectManager returns the ProjectManager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetProjectManager() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ProjectManager
}

// GetProjectManagerOk returns a tuple with the ProjectManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetProjectManagerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ProjectManager) {
		return map[string]interface{}{}, false
	}
	return o.ProjectManager, true
}

// HasProjectManager returns a boolean if a field has been set.
func (o *Config) HasProjectManager() bool {
	if o != nil && !IsNil(o.ProjectManager) {
		return true
	}

	return false
}

// SetProjectManager gets a reference to the given map[string]interface{} and assigns it to the ProjectManager field.
func (o *Config) SetProjectManager(v map[string]interface{}) {
	o.ProjectManager = v
}

// GetPlanManager returns the PlanManager field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Config) GetPlanManager() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PlanManager
}

// GetPlanManagerOk returns a tuple with the PlanManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Config) GetPlanManagerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PlanManager) {
		return map[string]interface{}{}, false
	}
	return o.PlanManager, true
}

// HasPlanManager returns a boolean if a field has been set.
func (o *Config) HasPlanManager() bool {
	if o != nil && !IsNil(o.PlanManager) {
		return true
	}

	return false
}

// SetPlanManager gets a reference to the given map[string]interface{} and assigns it to the PlanManager field.
func (o *Config) SetPlanManager(v map[string]interface{}) {
	o.PlanManager = v
}

// GetPlanStore returns the PlanStore field value if set, zero value otherwise.
func (o *Config) GetPlanStore() map[string]interface{} {
	if o == nil || IsNil(o.PlanStore) {
		var ret map[string]interface{}
		return ret
	}
	return o.PlanStore
}

// GetPlanStoreOk returns a tuple with the PlanStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Config) GetPlanStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PlanStore) {
		return map[string]interface{}{}, false
	}
	return o.PlanStore, true
}

// HasPlanStore returns a boolean if a field has been set.
func (o *Config) HasPlanStore() bool {
	if o != nil && !IsNil(o.PlanStore) {
		return true
	}

	return false
}

// SetPlanStore gets a reference to the given map[string]interface{} and assigns it to the PlanStore field.
func (o *Config) SetPlanStore(v map[string]interface{}) {
	o.PlanStore = v
}

func (o Config) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Config) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Bus != nil {
		toSerialize["Bus"] = o.Bus
	}
	if o.AgentRegistry != nil {
		toSerialize["AgentRegistry"] = o.AgentRegistry
	}
	if !IsNil(o.Queue) {
		toSerialize["Queue"] = o.Queue
	}
	if o.MemoryManager != nil {
		toSerialize["MemoryManager"] = o.MemoryManager
	}
	if o.TaskRegistry != nil {
		toSerialize["TaskRegistry"] = o.TaskRegistry
	}
	if !IsNil(o.SessionStore) {
		toSerialize["SessionStore"] = o.SessionStore
	}
	if o.WorkerPool != nil {
		toSerialize["WorkerPool"] = o.WorkerPool
	}
	if o.SkillRegistry != nil {
		toSerialize["SkillRegistry"] = o.SkillRegistry
	}
	if o.SkillExecutor != nil {
		toSerialize["SkillExecutor"] = o.SkillExecutor
	}
	if o.TemplateRegistry != nil {
		toSerialize["TemplateRegistry"] = o.TemplateRegistry
	}
	if o.SelfImprove != nil {
		toSerialize["SelfImprove"] = o.SelfImprove
	}
	if o.TokenCache != nil {
		toSerialize["TokenCache"] = o.TokenCache
	}
	if o.SecurityChecker != nil {
		toSerialize["SecurityChecker"] = o.SecurityChecker
	}
	if o.Scheduler != nil {
		toSerialize["Scheduler"] = o.Scheduler
	}
	if o.CalendarClient != nil {
		toSerialize["CalendarClient"] = o.CalendarClient
	}
	if !IsNil(o.DaemonController) {
		toSerialize["DaemonController"] = o.DaemonController
	}
	if o.RuntimeManager != nil {
		toSerialize["RuntimeManager"] = o.RuntimeManager
	}
	if !IsNil(o.WorkingDir) {
		toSerialize["WorkingDir"] = o.WorkingDir
	}
	if !IsNil(o.PidFile) {
		toSerialize["PidFile"] = o.PidFile
	}
	if !IsNil(o.StateDir) {
		toSerialize["StateDir"] = o.StateDir
	}
	if !IsNil(o.BinPath) {
		toSerialize["BinPath"] = o.BinPath
	}
	if o.ProjectManager != nil {
		toSerialize["ProjectManager"] = o.ProjectManager
	}
	if o.PlanManager != nil {
		toSerialize["PlanManager"] = o.PlanManager
	}
	if !IsNil(o.PlanStore) {
		toSerialize["PlanStore"] = o.PlanStore
	}
	return toSerialize, nil
}

type NullableConfig struct {
	value *Config
	isSet bool
}

func (v NullableConfig) Get() *Config {
	return v.value
}

func (v *NullableConfig) Set(val *Config) {
	v.value = val
	v.isSet = true
}

func (v NullableConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfig(val *Config) *NullableConfig {
	return &NullableConfig{value: val, isSet: true}
}

func (v NullableConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


