/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UIFieldDef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UIFieldDef{}

// UIFieldDef struct for UIFieldDef
type UIFieldDef struct {
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Required *bool `json:"required,omitempty"`
	Default map[string]interface{} `json:"default,omitempty"`
	Options NullableString `json:"options,omitempty"`
	Placeholder *string `json:"placeholder,omitempty"`
	Help *string `json:"help,omitempty"`
}

type _UIFieldDef UIFieldDef

// NewUIFieldDef instantiates a new UIFieldDef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUIFieldDef(name string, label string, type_ string) *UIFieldDef {
	this := UIFieldDef{}
	this.Name = name
	this.Label = label
	this.Type = type_
	return &this
}

// NewUIFieldDefWithDefaults instantiates a new UIFieldDef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUIFieldDefWithDefaults() *UIFieldDef {
	this := UIFieldDef{}
	return &this
}

// GetName returns the Name field value
func (o *UIFieldDef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UIFieldDef) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *UIFieldDef) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *UIFieldDef) SetLabel(v string) {
	o.Label = v
}

// GetType returns the Type field value
func (o *UIFieldDef) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UIFieldDef) SetType(v string) {
	o.Type = v
}

// GetRequired returns the Required field value if set, zero value otherwise.
func (o *UIFieldDef) GetRequired() bool {
	if o == nil || IsNil(o.Required) {
		var ret bool
		return ret
	}
	return *o.Required
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.Required) {
		return nil, false
	}
	return o.Required, true
}

// HasRequired returns a boolean if a field has been set.
func (o *UIFieldDef) HasRequired() bool {
	if o != nil && !IsNil(o.Required) {
		return true
	}

	return false
}

// SetRequired gets a reference to the given bool and assigns it to the Required field.
func (o *UIFieldDef) SetRequired(v bool) {
	o.Required = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *UIFieldDef) GetDefault() map[string]interface{} {
	if o == nil || IsNil(o.Default) {
		var ret map[string]interface{}
		return ret
	}
	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetDefaultOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Default) {
		return map[string]interface{}{}, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *UIFieldDef) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given map[string]interface{} and assigns it to the Default field.
func (o *UIFieldDef) SetDefault(v map[string]interface{}) {
	o.Default = v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UIFieldDef) GetOptions() string {
	if o == nil || IsNil(o.Options.Get()) {
		var ret string
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UIFieldDef) GetOptionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *UIFieldDef) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableString and assigns it to the Options field.
func (o *UIFieldDef) SetOptions(v string) {
	o.Options.Set(&v)
}
// SetOptionsNil sets the value for Options to be an explicit nil
func (o *UIFieldDef) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *UIFieldDef) UnsetOptions() {
	o.Options.Unset()
}

// GetPlaceholder returns the Placeholder field value if set, zero value otherwise.
func (o *UIFieldDef) GetPlaceholder() string {
	if o == nil || IsNil(o.Placeholder) {
		var ret string
		return ret
	}
	return *o.Placeholder
}

// GetPlaceholderOk returns a tuple with the Placeholder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetPlaceholderOk() (*string, bool) {
	if o == nil || IsNil(o.Placeholder) {
		return nil, false
	}
	return o.Placeholder, true
}

// HasPlaceholder returns a boolean if a field has been set.
func (o *UIFieldDef) HasPlaceholder() bool {
	if o != nil && !IsNil(o.Placeholder) {
		return true
	}

	return false
}

// SetPlaceholder gets a reference to the given string and assigns it to the Placeholder field.
func (o *UIFieldDef) SetPlaceholder(v string) {
	o.Placeholder = &v
}

// GetHelp returns the Help field value if set, zero value otherwise.
func (o *UIFieldDef) GetHelp() string {
	if o == nil || IsNil(o.Help) {
		var ret string
		return ret
	}
	return *o.Help
}

// GetHelpOk returns a tuple with the Help field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UIFieldDef) GetHelpOk() (*string, bool) {
	if o == nil || IsNil(o.Help) {
		return nil, false
	}
	return o.Help, true
}

// HasHelp returns a boolean if a field has been set.
func (o *UIFieldDef) HasHelp() bool {
	if o != nil && !IsNil(o.Help) {
		return true
	}

	return false
}

// SetHelp gets a reference to the given string and assigns it to the Help field.
func (o *UIFieldDef) SetHelp(v string) {
	o.Help = &v
}

func (o UIFieldDef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UIFieldDef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	toSerialize["type"] = o.Type
	if !IsNil(o.Required) {
		toSerialize["required"] = o.Required
	}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	if !IsNil(o.Placeholder) {
		toSerialize["placeholder"] = o.Placeholder
	}
	if !IsNil(o.Help) {
		toSerialize["help"] = o.Help
	}
	return toSerialize, nil
}

func (o *UIFieldDef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUIFieldDef := _UIFieldDef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUIFieldDef)

	if err != nil {
		return err
	}

	*o = UIFieldDef(varUIFieldDef)

	return err
}

type NullableUIFieldDef struct {
	value *UIFieldDef
	isSet bool
}

func (v NullableUIFieldDef) Get() *UIFieldDef {
	return v.value
}

func (v *NullableUIFieldDef) Set(val *UIFieldDef) {
	v.value = val
	v.isSet = true
}

func (v NullableUIFieldDef) IsSet() bool {
	return v.isSet
}

func (v *NullableUIFieldDef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUIFieldDef(val *UIFieldDef) *NullableUIFieldDef {
	return &NullableUIFieldDef{value: val, isSet: true}
}

func (v NullableUIFieldDef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUIFieldDef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


