/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the SearchService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchService{}

// SearchService struct for SearchService
type SearchService struct {
	SessionStore map[string]interface{} `json:"sessionStore,omitempty"`
	TaskRegistry map[string]interface{} `json:"taskRegistry,omitempty"`
	MemoryMgr map[string]interface{} `json:"memoryMgr,omitempty"`
	PlanStore map[string]interface{} `json:"planStore,omitempty"`
}

// NewSearchService instantiates a new SearchService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchService() *SearchService {
	this := SearchService{}
	return &this
}

// NewSearchServiceWithDefaults instantiates a new SearchService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchServiceWithDefaults() *SearchService {
	this := SearchService{}
	return &this
}

// GetSessionStore returns the SessionStore field value if set, zero value otherwise.
func (o *SearchService) GetSessionStore() map[string]interface{} {
	if o == nil || IsNil(o.SessionStore) {
		var ret map[string]interface{}
		return ret
	}
	return o.SessionStore
}

// GetSessionStoreOk returns a tuple with the SessionStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchService) GetSessionStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SessionStore) {
		return map[string]interface{}{}, false
	}
	return o.SessionStore, true
}

// HasSessionStore returns a boolean if a field has been set.
func (o *SearchService) HasSessionStore() bool {
	if o != nil && !IsNil(o.SessionStore) {
		return true
	}

	return false
}

// SetSessionStore gets a reference to the given map[string]interface{} and assigns it to the SessionStore field.
func (o *SearchService) SetSessionStore(v map[string]interface{}) {
	o.SessionStore = v
}

// GetTaskRegistry returns the TaskRegistry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchService) GetTaskRegistry() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.TaskRegistry
}

// GetTaskRegistryOk returns a tuple with the TaskRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchService) GetTaskRegistryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TaskRegistry) {
		return map[string]interface{}{}, false
	}
	return o.TaskRegistry, true
}

// HasTaskRegistry returns a boolean if a field has been set.
func (o *SearchService) HasTaskRegistry() bool {
	if o != nil && !IsNil(o.TaskRegistry) {
		return true
	}

	return false
}

// SetTaskRegistry gets a reference to the given map[string]interface{} and assigns it to the TaskRegistry field.
func (o *SearchService) SetTaskRegistry(v map[string]interface{}) {
	o.TaskRegistry = v
}

// GetMemoryMgr returns the MemoryMgr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchService) GetMemoryMgr() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.MemoryMgr
}

// GetMemoryMgrOk returns a tuple with the MemoryMgr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchService) GetMemoryMgrOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.MemoryMgr) {
		return map[string]interface{}{}, false
	}
	return o.MemoryMgr, true
}

// HasMemoryMgr returns a boolean if a field has been set.
func (o *SearchService) HasMemoryMgr() bool {
	if o != nil && !IsNil(o.MemoryMgr) {
		return true
	}

	return false
}

// SetMemoryMgr gets a reference to the given map[string]interface{} and assigns it to the MemoryMgr field.
func (o *SearchService) SetMemoryMgr(v map[string]interface{}) {
	o.MemoryMgr = v
}

// GetPlanStore returns the PlanStore field value if set, zero value otherwise.
func (o *SearchService) GetPlanStore() map[string]interface{} {
	if o == nil || IsNil(o.PlanStore) {
		var ret map[string]interface{}
		return ret
	}
	return o.PlanStore
}

// GetPlanStoreOk returns a tuple with the PlanStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchService) GetPlanStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PlanStore) {
		return map[string]interface{}{}, false
	}
	return o.PlanStore, true
}

// HasPlanStore returns a boolean if a field has been set.
func (o *SearchService) HasPlanStore() bool {
	if o != nil && !IsNil(o.PlanStore) {
		return true
	}

	return false
}

// SetPlanStore gets a reference to the given map[string]interface{} and assigns it to the PlanStore field.
func (o *SearchService) SetPlanStore(v map[string]interface{}) {
	o.PlanStore = v
}

func (o SearchService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionStore) {
		toSerialize["sessionStore"] = o.SessionStore
	}
	if o.TaskRegistry != nil {
		toSerialize["taskRegistry"] = o.TaskRegistry
	}
	if o.MemoryMgr != nil {
		toSerialize["memoryMgr"] = o.MemoryMgr
	}
	if !IsNil(o.PlanStore) {
		toSerialize["planStore"] = o.PlanStore
	}
	return toSerialize, nil
}

type NullableSearchService struct {
	value *SearchService
	isSet bool
}

func (v NullableSearchService) Get() *SearchService {
	return v.value
}

func (v *NullableSearchService) Set(val *SearchService) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchService) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchService(val *SearchService) *NullableSearchService {
	return &NullableSearchService{value: val, isSet: true}
}

func (v NullableSearchService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


