/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEventRequest{}

// UpdateEventRequest struct for UpdateEventRequest
type UpdateEventRequest struct {
	Id string `json:"id"`
	Summary *string `json:"summary,omitempty"`
	Description *string `json:"description,omitempty"`
	Location *string `json:"location,omitempty"`
	Start NullableString `json:"start,omitempty"`
	End NullableString `json:"end,omitempty"`
}

type _UpdateEventRequest UpdateEventRequest

// NewUpdateEventRequest instantiates a new UpdateEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEventRequest(id string) *UpdateEventRequest {
	this := UpdateEventRequest{}
	this.Id = id
	return &this
}

// NewUpdateEventRequestWithDefaults instantiates a new UpdateEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEventRequestWithDefaults() *UpdateEventRequest {
	this := UpdateEventRequest{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateEventRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateEventRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateEventRequest) SetId(v string) {
	o.Id = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *UpdateEventRequest) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventRequest) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *UpdateEventRequest) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *UpdateEventRequest) SetSummary(v string) {
	o.Summary = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateEventRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateEventRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateEventRequest) SetDescription(v string) {
	o.Description = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *UpdateEventRequest) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEventRequest) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *UpdateEventRequest) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *UpdateEventRequest) SetLocation(v string) {
	o.Location = &v
}

// GetStart returns the Start field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEventRequest) GetStart() string {
	if o == nil || IsNil(o.Start.Get()) {
		var ret string
		return ret
	}
	return *o.Start.Get()
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEventRequest) GetStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Start.Get(), o.Start.IsSet()
}

// HasStart returns a boolean if a field has been set.
func (o *UpdateEventRequest) HasStart() bool {
	if o != nil && o.Start.IsSet() {
		return true
	}

	return false
}

// SetStart gets a reference to the given NullableString and assigns it to the Start field.
func (o *UpdateEventRequest) SetStart(v string) {
	o.Start.Set(&v)
}
// SetStartNil sets the value for Start to be an explicit nil
func (o *UpdateEventRequest) SetStartNil() {
	o.Start.Set(nil)
}

// UnsetStart ensures that no value is present for Start, not even an explicit nil
func (o *UpdateEventRequest) UnsetStart() {
	o.Start.Unset()
}

// GetEnd returns the End field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateEventRequest) GetEnd() string {
	if o == nil || IsNil(o.End.Get()) {
		var ret string
		return ret
	}
	return *o.End.Get()
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateEventRequest) GetEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.End.Get(), o.End.IsSet()
}

// HasEnd returns a boolean if a field has been set.
func (o *UpdateEventRequest) HasEnd() bool {
	if o != nil && o.End.IsSet() {
		return true
	}

	return false
}

// SetEnd gets a reference to the given NullableString and assigns it to the End field.
func (o *UpdateEventRequest) SetEnd(v string) {
	o.End.Set(&v)
}
// SetEndNil sets the value for End to be an explicit nil
func (o *UpdateEventRequest) SetEndNil() {
	o.End.Set(nil)
}

// UnsetEnd ensures that no value is present for End, not even an explicit nil
func (o *UpdateEventRequest) UnsetEnd() {
	o.End.Unset()
}

func (o UpdateEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if o.Start.IsSet() {
		toSerialize["start"] = o.Start.Get()
	}
	if o.End.IsSet() {
		toSerialize["end"] = o.End.Get()
	}
	return toSerialize, nil
}

func (o *UpdateEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateEventRequest := _UpdateEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateEventRequest)

	if err != nil {
		return err
	}

	*o = UpdateEventRequest(varUpdateEventRequest)

	return err
}

type NullableUpdateEventRequest struct {
	value *UpdateEventRequest
	isSet bool
}

func (v NullableUpdateEventRequest) Get() *UpdateEventRequest {
	return v.value
}

func (v *NullableUpdateEventRequest) Set(val *UpdateEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEventRequest(val *UpdateEventRequest) *NullableUpdateEventRequest {
	return &NullableUpdateEventRequest{value: val, isSet: true}
}

func (v NullableUpdateEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


