/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRequest{}

// ListRequest struct for ListRequest
type ListRequest struct {
	State *string `json:"state,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
}

// NewListRequest instantiates a new ListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRequest() *ListRequest {
	this := ListRequest{}
	return &this
}

// NewListRequestWithDefaults instantiates a new ListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRequestWithDefaults() *ListRequest {
	this := ListRequest{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ListRequest) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRequest) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ListRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ListRequest) SetState(v string) {
	o.State = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ListRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ListRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ListRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o ListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	return toSerialize, nil
}

type NullableListRequest struct {
	value *ListRequest
	isSet bool
}

func (v NullableListRequest) Get() *ListRequest {
	return v.value
}

func (v *NullableListRequest) Set(val *ListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRequest(val *ListRequest) *NullableListRequest {
	return &NullableListRequest{value: val, isSet: true}
}

func (v NullableListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


