/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShellJobConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShellJobConfig{}

// ShellJobConfig struct for ShellJobConfig
type ShellJobConfig struct {
	Command string `json:"command"`
	Args NullableString `json:"args,omitempty"`
	WorkDir *string `json:"work_dir,omitempty"`
	Env NullableString `json:"env,omitempty"`
	TimeoutSecs *int32 `json:"timeout_secs,omitempty"`
	CaptureOutput bool `json:"capture_output"`
}

type _ShellJobConfig ShellJobConfig

// NewShellJobConfig instantiates a new ShellJobConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShellJobConfig(command string, captureOutput bool) *ShellJobConfig {
	this := ShellJobConfig{}
	this.Command = command
	this.CaptureOutput = captureOutput
	return &this
}

// NewShellJobConfigWithDefaults instantiates a new ShellJobConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShellJobConfigWithDefaults() *ShellJobConfig {
	this := ShellJobConfig{}
	return &this
}

// GetCommand returns the Command field value
func (o *ShellJobConfig) GetCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *ShellJobConfig) SetCommand(v string) {
	o.Command = v
}

// GetArgs returns the Args field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShellJobConfig) GetArgs() string {
	if o == nil || IsNil(o.Args.Get()) {
		var ret string
		return ret
	}
	return *o.Args.Get()
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShellJobConfig) GetArgsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Args.Get(), o.Args.IsSet()
}

// HasArgs returns a boolean if a field has been set.
func (o *ShellJobConfig) HasArgs() bool {
	if o != nil && o.Args.IsSet() {
		return true
	}

	return false
}

// SetArgs gets a reference to the given NullableString and assigns it to the Args field.
func (o *ShellJobConfig) SetArgs(v string) {
	o.Args.Set(&v)
}
// SetArgsNil sets the value for Args to be an explicit nil
func (o *ShellJobConfig) SetArgsNil() {
	o.Args.Set(nil)
}

// UnsetArgs ensures that no value is present for Args, not even an explicit nil
func (o *ShellJobConfig) UnsetArgs() {
	o.Args.Unset()
}

// GetWorkDir returns the WorkDir field value if set, zero value otherwise.
func (o *ShellJobConfig) GetWorkDir() string {
	if o == nil || IsNil(o.WorkDir) {
		var ret string
		return ret
	}
	return *o.WorkDir
}

// GetWorkDirOk returns a tuple with the WorkDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetWorkDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkDir) {
		return nil, false
	}
	return o.WorkDir, true
}

// HasWorkDir returns a boolean if a field has been set.
func (o *ShellJobConfig) HasWorkDir() bool {
	if o != nil && !IsNil(o.WorkDir) {
		return true
	}

	return false
}

// SetWorkDir gets a reference to the given string and assigns it to the WorkDir field.
func (o *ShellJobConfig) SetWorkDir(v string) {
	o.WorkDir = &v
}

// GetEnv returns the Env field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShellJobConfig) GetEnv() string {
	if o == nil || IsNil(o.Env.Get()) {
		var ret string
		return ret
	}
	return *o.Env.Get()
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShellJobConfig) GetEnvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Env.Get(), o.Env.IsSet()
}

// HasEnv returns a boolean if a field has been set.
func (o *ShellJobConfig) HasEnv() bool {
	if o != nil && o.Env.IsSet() {
		return true
	}

	return false
}

// SetEnv gets a reference to the given NullableString and assigns it to the Env field.
func (o *ShellJobConfig) SetEnv(v string) {
	o.Env.Set(&v)
}
// SetEnvNil sets the value for Env to be an explicit nil
func (o *ShellJobConfig) SetEnvNil() {
	o.Env.Set(nil)
}

// UnsetEnv ensures that no value is present for Env, not even an explicit nil
func (o *ShellJobConfig) UnsetEnv() {
	o.Env.Unset()
}

// GetTimeoutSecs returns the TimeoutSecs field value if set, zero value otherwise.
func (o *ShellJobConfig) GetTimeoutSecs() int32 {
	if o == nil || IsNil(o.TimeoutSecs) {
		var ret int32
		return ret
	}
	return *o.TimeoutSecs
}

// GetTimeoutSecsOk returns a tuple with the TimeoutSecs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetTimeoutSecsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSecs) {
		return nil, false
	}
	return o.TimeoutSecs, true
}

// HasTimeoutSecs returns a boolean if a field has been set.
func (o *ShellJobConfig) HasTimeoutSecs() bool {
	if o != nil && !IsNil(o.TimeoutSecs) {
		return true
	}

	return false
}

// SetTimeoutSecs gets a reference to the given int32 and assigns it to the TimeoutSecs field.
func (o *ShellJobConfig) SetTimeoutSecs(v int32) {
	o.TimeoutSecs = &v
}

// GetCaptureOutput returns the CaptureOutput field value
func (o *ShellJobConfig) GetCaptureOutput() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CaptureOutput
}

// GetCaptureOutputOk returns a tuple with the CaptureOutput field value
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetCaptureOutputOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaptureOutput, true
}

// SetCaptureOutput sets field value
func (o *ShellJobConfig) SetCaptureOutput(v bool) {
	o.CaptureOutput = v
}

func (o ShellJobConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShellJobConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	if o.Args.IsSet() {
		toSerialize["args"] = o.Args.Get()
	}
	if !IsNil(o.WorkDir) {
		toSerialize["work_dir"] = o.WorkDir
	}
	if o.Env.IsSet() {
		toSerialize["env"] = o.Env.Get()
	}
	if !IsNil(o.TimeoutSecs) {
		toSerialize["timeout_secs"] = o.TimeoutSecs
	}
	toSerialize["capture_output"] = o.CaptureOutput
	return toSerialize, nil
}

func (o *ShellJobConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
		"capture_output",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShellJobConfig := _ShellJobConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShellJobConfig)

	if err != nil {
		return err
	}

	*o = ShellJobConfig(varShellJobConfig)

	return err
}

type NullableShellJobConfig struct {
	value *ShellJobConfig
	isSet bool
}

func (v NullableShellJobConfig) Get() *ShellJobConfig {
	return v.value
}

func (v *NullableShellJobConfig) Set(val *ShellJobConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableShellJobConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableShellJobConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShellJobConfig(val *ShellJobConfig) *NullableShellJobConfig {
	return &NullableShellJobConfig{value: val, isSet: true}
}

func (v NullableShellJobConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShellJobConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


