/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteSessionRequest{}

// DeleteSessionRequest struct for DeleteSessionRequest
type DeleteSessionRequest struct {
	Id string `json:"id"`
}

type _DeleteSessionRequest DeleteSessionRequest

// NewDeleteSessionRequest instantiates a new DeleteSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteSessionRequest(id string) *DeleteSessionRequest {
	this := DeleteSessionRequest{}
	this.Id = id
	return &this
}

// NewDeleteSessionRequestWithDefaults instantiates a new DeleteSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteSessionRequestWithDefaults() *DeleteSessionRequest {
	this := DeleteSessionRequest{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteSessionRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteSessionRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteSessionRequest) SetId(v string) {
	o.Id = v
}

func (o DeleteSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DeleteSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteSessionRequest := _DeleteSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteSessionRequest)

	if err != nil {
		return err
	}

	*o = DeleteSessionRequest(varDeleteSessionRequest)

	return err
}

type NullableDeleteSessionRequest struct {
	value *DeleteSessionRequest
	isSet bool
}

func (v NullableDeleteSessionRequest) Get() *DeleteSessionRequest {
	return v.value
}

func (v *NullableDeleteSessionRequest) Set(val *DeleteSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteSessionRequest(val *DeleteSessionRequest) *NullableDeleteSessionRequest {
	return &NullableDeleteSessionRequest{value: val, isSet: true}
}

func (v NullableDeleteSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


