/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PauseJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PauseJobRequest{}

// PauseJobRequest struct for PauseJobRequest
type PauseJobRequest struct {
	Id string `json:"id"`
}

type _PauseJobRequest PauseJobRequest

// NewPauseJobRequest instantiates a new PauseJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPauseJobRequest(id string) *PauseJobRequest {
	this := PauseJobRequest{}
	this.Id = id
	return &this
}

// NewPauseJobRequestWithDefaults instantiates a new PauseJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPauseJobRequestWithDefaults() *PauseJobRequest {
	this := PauseJobRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PauseJobRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PauseJobRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PauseJobRequest) SetId(v string) {
	o.Id = v
}

func (o PauseJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PauseJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *PauseJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPauseJobRequest := _PauseJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPauseJobRequest)

	if err != nil {
		return err
	}

	*o = PauseJobRequest(varPauseJobRequest)

	return err
}

type NullablePauseJobRequest struct {
	value *PauseJobRequest
	isSet bool
}

func (v NullablePauseJobRequest) Get() *PauseJobRequest {
	return v.value
}

func (v *NullablePauseJobRequest) Set(val *PauseJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePauseJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePauseJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePauseJobRequest(val *PauseJobRequest) *NullablePauseJobRequest {
	return &NullablePauseJobRequest{value: val, isSet: true}
}

func (v NullablePauseJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePauseJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


