/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RevisePlanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevisePlanRequest{}

// RevisePlanRequest struct for RevisePlanRequest
type RevisePlanRequest struct {
	PlanId string `json:"plan_id"`
	SessionId string `json:"session_id"`
	Feedback string `json:"feedback"`
}

type _RevisePlanRequest RevisePlanRequest

// NewRevisePlanRequest instantiates a new RevisePlanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevisePlanRequest(planId string, sessionId string, feedback string) *RevisePlanRequest {
	this := RevisePlanRequest{}
	this.PlanId = planId
	this.SessionId = sessionId
	this.Feedback = feedback
	return &this
}

// NewRevisePlanRequestWithDefaults instantiates a new RevisePlanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevisePlanRequestWithDefaults() *RevisePlanRequest {
	this := RevisePlanRequest{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *RevisePlanRequest) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *RevisePlanRequest) GetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *RevisePlanRequest) SetPlanId(v string) {
	o.PlanId = v
}

// GetSessionId returns the SessionId field value
func (o *RevisePlanRequest) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *RevisePlanRequest) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *RevisePlanRequest) SetSessionId(v string) {
	o.SessionId = v
}

// GetFeedback returns the Feedback field value
func (o *RevisePlanRequest) GetFeedback() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Feedback
}

// GetFeedbackOk returns a tuple with the Feedback field value
// and a boolean to check if the value has been set.
func (o *RevisePlanRequest) GetFeedbackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Feedback, true
}

// SetFeedback sets field value
func (o *RevisePlanRequest) SetFeedback(v string) {
	o.Feedback = v
}

func (o RevisePlanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevisePlanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan_id"] = o.PlanId
	toSerialize["session_id"] = o.SessionId
	toSerialize["feedback"] = o.Feedback
	return toSerialize, nil
}

func (o *RevisePlanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_id",
		"session_id",
		"feedback",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevisePlanRequest := _RevisePlanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevisePlanRequest)

	if err != nil {
		return err
	}

	*o = RevisePlanRequest(varRevisePlanRequest)

	return err
}

type NullableRevisePlanRequest struct {
	value *RevisePlanRequest
	isSet bool
}

func (v NullableRevisePlanRequest) Get() *RevisePlanRequest {
	return v.value
}

func (v *NullableRevisePlanRequest) Set(val *RevisePlanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRevisePlanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRevisePlanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevisePlanRequest(val *RevisePlanRequest) *NullableRevisePlanRequest {
	return &NullableRevisePlanRequest{value: val, isSet: true}
}

func (v NullableRevisePlanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevisePlanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


