/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatResponse{}

// ChatResponse struct for ChatResponse
type ChatResponse struct {
	Reply string `json:"reply"`
	Model *string `json:"model,omitempty"`
	TokensUsed *int32 `json:"tokens_used,omitempty"`
}

type _ChatResponse ChatResponse

// NewChatResponse instantiates a new ChatResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatResponse(reply string) *ChatResponse {
	this := ChatResponse{}
	this.Reply = reply
	return &this
}

// NewChatResponseWithDefaults instantiates a new ChatResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatResponseWithDefaults() *ChatResponse {
	this := ChatResponse{}
	return &this
}

// GetReply returns the Reply field value
func (o *ChatResponse) GetReply() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reply
}

// GetReplyOk returns a tuple with the Reply field value
// and a boolean to check if the value has been set.
func (o *ChatResponse) GetReplyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reply, true
}

// SetReply sets field value
func (o *ChatResponse) SetReply(v string) {
	o.Reply = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *ChatResponse) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatResponse) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *ChatResponse) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *ChatResponse) SetModel(v string) {
	o.Model = &v
}

// GetTokensUsed returns the TokensUsed field value if set, zero value otherwise.
func (o *ChatResponse) GetTokensUsed() int32 {
	if o == nil || IsNil(o.TokensUsed) {
		var ret int32
		return ret
	}
	return *o.TokensUsed
}

// GetTokensUsedOk returns a tuple with the TokensUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatResponse) GetTokensUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.TokensUsed) {
		return nil, false
	}
	return o.TokensUsed, true
}

// HasTokensUsed returns a boolean if a field has been set.
func (o *ChatResponse) HasTokensUsed() bool {
	if o != nil && !IsNil(o.TokensUsed) {
		return true
	}

	return false
}

// SetTokensUsed gets a reference to the given int32 and assigns it to the TokensUsed field.
func (o *ChatResponse) SetTokensUsed(v int32) {
	o.TokensUsed = &v
}

func (o ChatResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reply"] = o.Reply
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.TokensUsed) {
		toSerialize["tokens_used"] = o.TokensUsed
	}
	return toSerialize, nil
}

func (o *ChatResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reply",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatResponse := _ChatResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatResponse)

	if err != nil {
		return err
	}

	*o = ChatResponse(varChatResponse)

	return err
}

type NullableChatResponse struct {
	value *ChatResponse
	isSet bool
}

func (v NullableChatResponse) Get() *ChatResponse {
	return v.value
}

func (v *NullableChatResponse) Set(val *ChatResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChatResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChatResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatResponse(val *ChatResponse) *NullableChatResponse {
	return &NullableChatResponse{value: val, isSet: true}
}

func (v NullableChatResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


