/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplyImprovementRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyImprovementRequest{}

// ApplyImprovementRequest struct for ApplyImprovementRequest
type ApplyImprovementRequest struct {
	ImprovementId string `json:"improvement_id"`
}

type _ApplyImprovementRequest ApplyImprovementRequest

// NewApplyImprovementRequest instantiates a new ApplyImprovementRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyImprovementRequest(improvementId string) *ApplyImprovementRequest {
	this := ApplyImprovementRequest{}
	this.ImprovementId = improvementId
	return &this
}

// NewApplyImprovementRequestWithDefaults instantiates a new ApplyImprovementRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyImprovementRequestWithDefaults() *ApplyImprovementRequest {
	this := ApplyImprovementRequest{}
	return &this
}

// GetImprovementId returns the ImprovementId field value
func (o *ApplyImprovementRequest) GetImprovementId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImprovementId
}

// GetImprovementIdOk returns a tuple with the ImprovementId field value
// and a boolean to check if the value has been set.
func (o *ApplyImprovementRequest) GetImprovementIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImprovementId, true
}

// SetImprovementId sets field value
func (o *ApplyImprovementRequest) SetImprovementId(v string) {
	o.ImprovementId = v
}

func (o ApplyImprovementRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyImprovementRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["improvement_id"] = o.ImprovementId
	return toSerialize, nil
}

func (o *ApplyImprovementRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"improvement_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplyImprovementRequest := _ApplyImprovementRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplyImprovementRequest)

	if err != nil {
		return err
	}

	*o = ApplyImprovementRequest(varApplyImprovementRequest)

	return err
}

type NullableApplyImprovementRequest struct {
	value *ApplyImprovementRequest
	isSet bool
}

func (v NullableApplyImprovementRequest) Get() *ApplyImprovementRequest {
	return v.value
}

func (v *NullableApplyImprovementRequest) Set(val *ApplyImprovementRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyImprovementRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyImprovementRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyImprovementRequest(val *ApplyImprovementRequest) *NullableApplyImprovementRequest {
	return &NullableApplyImprovementRequest{value: val, isSet: true}
}

func (v NullableApplyImprovementRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyImprovementRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


