/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the TerminalSession type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminalSession{}

// TerminalSession struct for TerminalSession
type TerminalSession struct {
	ID *string `json:"ID,omitempty"`
	WorkingDir *string `json:"WorkingDir,omitempty"`
	CreatedAt *string `json:"CreatedAt,omitempty"`
	LastUsed *string `json:"LastUsed,omitempty"`
	CommandCount *int32 `json:"CommandCount,omitempty"`
}

// NewTerminalSession instantiates a new TerminalSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminalSession() *TerminalSession {
	this := TerminalSession{}
	return &this
}

// NewTerminalSessionWithDefaults instantiates a new TerminalSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminalSessionWithDefaults() *TerminalSession {
	this := TerminalSession{}
	return &this
}

// GetID returns the ID field value if set, zero value otherwise.
func (o *TerminalSession) GetID() string {
	if o == nil || IsNil(o.ID) {
		var ret string
		return ret
	}
	return *o.ID
}

// GetIDOk returns a tuple with the ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSession) GetIDOk() (*string, bool) {
	if o == nil || IsNil(o.ID) {
		return nil, false
	}
	return o.ID, true
}

// HasID returns a boolean if a field has been set.
func (o *TerminalSession) HasID() bool {
	if o != nil && !IsNil(o.ID) {
		return true
	}

	return false
}

// SetID gets a reference to the given string and assigns it to the ID field.
func (o *TerminalSession) SetID(v string) {
	o.ID = &v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise.
func (o *TerminalSession) GetWorkingDir() string {
	if o == nil || IsNil(o.WorkingDir) {
		var ret string
		return ret
	}
	return *o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSession) GetWorkingDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *TerminalSession) HasWorkingDir() bool {
	if o != nil && !IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given string and assigns it to the WorkingDir field.
func (o *TerminalSession) SetWorkingDir(v string) {
	o.WorkingDir = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TerminalSession) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSession) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TerminalSession) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *TerminalSession) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise.
func (o *TerminalSession) GetLastUsed() string {
	if o == nil || IsNil(o.LastUsed) {
		var ret string
		return ret
	}
	return *o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSession) GetLastUsedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsed) {
		return nil, false
	}
	return o.LastUsed, true
}

// HasLastUsed returns a boolean if a field has been set.
func (o *TerminalSession) HasLastUsed() bool {
	if o != nil && !IsNil(o.LastUsed) {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given string and assigns it to the LastUsed field.
func (o *TerminalSession) SetLastUsed(v string) {
	o.LastUsed = &v
}

// GetCommandCount returns the CommandCount field value if set, zero value otherwise.
func (o *TerminalSession) GetCommandCount() int32 {
	if o == nil || IsNil(o.CommandCount) {
		var ret int32
		return ret
	}
	return *o.CommandCount
}

// GetCommandCountOk returns a tuple with the CommandCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerminalSession) GetCommandCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CommandCount) {
		return nil, false
	}
	return o.CommandCount, true
}

// HasCommandCount returns a boolean if a field has been set.
func (o *TerminalSession) HasCommandCount() bool {
	if o != nil && !IsNil(o.CommandCount) {
		return true
	}

	return false
}

// SetCommandCount gets a reference to the given int32 and assigns it to the CommandCount field.
func (o *TerminalSession) SetCommandCount(v int32) {
	o.CommandCount = &v
}

func (o TerminalSession) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminalSession) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ID) {
		toSerialize["ID"] = o.ID
	}
	if !IsNil(o.WorkingDir) {
		toSerialize["WorkingDir"] = o.WorkingDir
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["CreatedAt"] = o.CreatedAt
	}
	if !IsNil(o.LastUsed) {
		toSerialize["LastUsed"] = o.LastUsed
	}
	if !IsNil(o.CommandCount) {
		toSerialize["CommandCount"] = o.CommandCount
	}
	return toSerialize, nil
}

type NullableTerminalSession struct {
	value *TerminalSession
	isSet bool
}

func (v NullableTerminalSession) Get() *TerminalSession {
	return v.value
}

func (v *NullableTerminalSession) Set(val *TerminalSession) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminalSession) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminalSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminalSession(val *TerminalSession) *NullableTerminalSession {
	return &NullableTerminalSession{value: val, isSet: true}
}

func (v NullableTerminalSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminalSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


