/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddJobResponse{}

// AddJobResponse struct for AddJobResponse
type AddJobResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Schedule string `json:"schedule"`
	Enabled bool `json:"enabled"`
	LastRun NullableString `json:"last_run,omitempty"`
	NextRun NullableString `json:"next_run,omitempty"`
	LastError *string `json:"last_error,omitempty"`
	RunCount int32 `json:"run_count"`
	IsRunning bool `json:"is_running"`
}

type _AddJobResponse AddJobResponse

// NewAddJobResponse instantiates a new AddJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddJobResponse(id string, name string, schedule string, enabled bool, runCount int32, isRunning bool) *AddJobResponse {
	this := AddJobResponse{}
	this.Id = id
	this.Name = name
	this.Schedule = schedule
	this.Enabled = enabled
	this.RunCount = runCount
	this.IsRunning = isRunning
	return &this
}

// NewAddJobResponseWithDefaults instantiates a new AddJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddJobResponseWithDefaults() *AddJobResponse {
	this := AddJobResponse{}
	return &this
}

// GetId returns the Id field value
func (o *AddJobResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AddJobResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AddJobResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddJobResponse) SetName(v string) {
	o.Name = v
}

// GetSchedule returns the Schedule field value
func (o *AddJobResponse) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *AddJobResponse) SetSchedule(v string) {
	o.Schedule = v
}

// GetEnabled returns the Enabled field value
func (o *AddJobResponse) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *AddJobResponse) SetEnabled(v bool) {
	o.Enabled = v
}

// GetLastRun returns the LastRun field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddJobResponse) GetLastRun() string {
	if o == nil || IsNil(o.LastRun.Get()) {
		var ret string
		return ret
	}
	return *o.LastRun.Get()
}

// GetLastRunOk returns a tuple with the LastRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddJobResponse) GetLastRunOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastRun.Get(), o.LastRun.IsSet()
}

// HasLastRun returns a boolean if a field has been set.
func (o *AddJobResponse) HasLastRun() bool {
	if o != nil && o.LastRun.IsSet() {
		return true
	}

	return false
}

// SetLastRun gets a reference to the given NullableString and assigns it to the LastRun field.
func (o *AddJobResponse) SetLastRun(v string) {
	o.LastRun.Set(&v)
}
// SetLastRunNil sets the value for LastRun to be an explicit nil
func (o *AddJobResponse) SetLastRunNil() {
	o.LastRun.Set(nil)
}

// UnsetLastRun ensures that no value is present for LastRun, not even an explicit nil
func (o *AddJobResponse) UnsetLastRun() {
	o.LastRun.Unset()
}

// GetNextRun returns the NextRun field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddJobResponse) GetNextRun() string {
	if o == nil || IsNil(o.NextRun.Get()) {
		var ret string
		return ret
	}
	return *o.NextRun.Get()
}

// GetNextRunOk returns a tuple with the NextRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddJobResponse) GetNextRunOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextRun.Get(), o.NextRun.IsSet()
}

// HasNextRun returns a boolean if a field has been set.
func (o *AddJobResponse) HasNextRun() bool {
	if o != nil && o.NextRun.IsSet() {
		return true
	}

	return false
}

// SetNextRun gets a reference to the given NullableString and assigns it to the NextRun field.
func (o *AddJobResponse) SetNextRun(v string) {
	o.NextRun.Set(&v)
}
// SetNextRunNil sets the value for NextRun to be an explicit nil
func (o *AddJobResponse) SetNextRunNil() {
	o.NextRun.Set(nil)
}

// UnsetNextRun ensures that no value is present for NextRun, not even an explicit nil
func (o *AddJobResponse) UnsetNextRun() {
	o.NextRun.Unset()
}

// GetLastError returns the LastError field value if set, zero value otherwise.
func (o *AddJobResponse) GetLastError() string {
	if o == nil || IsNil(o.LastError) {
		var ret string
		return ret
	}
	return *o.LastError
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetLastErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastError) {
		return nil, false
	}
	return o.LastError, true
}

// HasLastError returns a boolean if a field has been set.
func (o *AddJobResponse) HasLastError() bool {
	if o != nil && !IsNil(o.LastError) {
		return true
	}

	return false
}

// SetLastError gets a reference to the given string and assigns it to the LastError field.
func (o *AddJobResponse) SetLastError(v string) {
	o.LastError = &v
}

// GetRunCount returns the RunCount field value
func (o *AddJobResponse) GetRunCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RunCount
}

// GetRunCountOk returns a tuple with the RunCount field value
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetRunCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunCount, true
}

// SetRunCount sets field value
func (o *AddJobResponse) SetRunCount(v int32) {
	o.RunCount = v
}

// GetIsRunning returns the IsRunning field value
func (o *AddJobResponse) GetIsRunning() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRunning
}

// GetIsRunningOk returns a tuple with the IsRunning field value
// and a boolean to check if the value has been set.
func (o *AddJobResponse) GetIsRunningOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRunning, true
}

// SetIsRunning sets field value
func (o *AddJobResponse) SetIsRunning(v bool) {
	o.IsRunning = v
}

func (o AddJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["schedule"] = o.Schedule
	toSerialize["enabled"] = o.Enabled
	if o.LastRun.IsSet() {
		toSerialize["last_run"] = o.LastRun.Get()
	}
	if o.NextRun.IsSet() {
		toSerialize["next_run"] = o.NextRun.Get()
	}
	if !IsNil(o.LastError) {
		toSerialize["last_error"] = o.LastError
	}
	toSerialize["run_count"] = o.RunCount
	toSerialize["is_running"] = o.IsRunning
	return toSerialize, nil
}

func (o *AddJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"schedule",
		"enabled",
		"run_count",
		"is_running",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddJobResponse := _AddJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddJobResponse)

	if err != nil {
		return err
	}

	*o = AddJobResponse(varAddJobResponse)

	return err
}

type NullableAddJobResponse struct {
	value *AddJobResponse
	isSet bool
}

func (v NullableAddJobResponse) Get() *AddJobResponse {
	return v.value
}

func (v *NullableAddJobResponse) Set(val *AddJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddJobResponse(val *AddJobResponse) *NullableAddJobResponse {
	return &NullableAddJobResponse{value: val, isSet: true}
}

func (v NullableAddJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


