/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ListEventsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEventsRequest{}

// ListEventsRequest struct for ListEventsRequest
type ListEventsRequest struct {
	TimeMin *string `json:"time_min,omitempty"`
	TimeMax *string `json:"time_max,omitempty"`
	MaxResults *int32 `json:"max_results,omitempty"`
}

// NewListEventsRequest instantiates a new ListEventsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEventsRequest() *ListEventsRequest {
	this := ListEventsRequest{}
	return &this
}

// NewListEventsRequestWithDefaults instantiates a new ListEventsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEventsRequestWithDefaults() *ListEventsRequest {
	this := ListEventsRequest{}
	return &this
}

// GetTimeMin returns the TimeMin field value if set, zero value otherwise.
func (o *ListEventsRequest) GetTimeMin() string {
	if o == nil || IsNil(o.TimeMin) {
		var ret string
		return ret
	}
	return *o.TimeMin
}

// GetTimeMinOk returns a tuple with the TimeMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEventsRequest) GetTimeMinOk() (*string, bool) {
	if o == nil || IsNil(o.TimeMin) {
		return nil, false
	}
	return o.TimeMin, true
}

// HasTimeMin returns a boolean if a field has been set.
func (o *ListEventsRequest) HasTimeMin() bool {
	if o != nil && !IsNil(o.TimeMin) {
		return true
	}

	return false
}

// SetTimeMin gets a reference to the given string and assigns it to the TimeMin field.
func (o *ListEventsRequest) SetTimeMin(v string) {
	o.TimeMin = &v
}

// GetTimeMax returns the TimeMax field value if set, zero value otherwise.
func (o *ListEventsRequest) GetTimeMax() string {
	if o == nil || IsNil(o.TimeMax) {
		var ret string
		return ret
	}
	return *o.TimeMax
}

// GetTimeMaxOk returns a tuple with the TimeMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEventsRequest) GetTimeMaxOk() (*string, bool) {
	if o == nil || IsNil(o.TimeMax) {
		return nil, false
	}
	return o.TimeMax, true
}

// HasTimeMax returns a boolean if a field has been set.
func (o *ListEventsRequest) HasTimeMax() bool {
	if o != nil && !IsNil(o.TimeMax) {
		return true
	}

	return false
}

// SetTimeMax gets a reference to the given string and assigns it to the TimeMax field.
func (o *ListEventsRequest) SetTimeMax(v string) {
	o.TimeMax = &v
}

// GetMaxResults returns the MaxResults field value if set, zero value otherwise.
func (o *ListEventsRequest) GetMaxResults() int32 {
	if o == nil || IsNil(o.MaxResults) {
		var ret int32
		return ret
	}
	return *o.MaxResults
}

// GetMaxResultsOk returns a tuple with the MaxResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEventsRequest) GetMaxResultsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxResults) {
		return nil, false
	}
	return o.MaxResults, true
}

// HasMaxResults returns a boolean if a field has been set.
func (o *ListEventsRequest) HasMaxResults() bool {
	if o != nil && !IsNil(o.MaxResults) {
		return true
	}

	return false
}

// SetMaxResults gets a reference to the given int32 and assigns it to the MaxResults field.
func (o *ListEventsRequest) SetMaxResults(v int32) {
	o.MaxResults = &v
}

func (o ListEventsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEventsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeMin) {
		toSerialize["time_min"] = o.TimeMin
	}
	if !IsNil(o.TimeMax) {
		toSerialize["time_max"] = o.TimeMax
	}
	if !IsNil(o.MaxResults) {
		toSerialize["max_results"] = o.MaxResults
	}
	return toSerialize, nil
}

type NullableListEventsRequest struct {
	value *ListEventsRequest
	isSet bool
}

func (v NullableListEventsRequest) Get() *ListEventsRequest {
	return v.value
}

func (v *NullableListEventsRequest) Set(val *ListEventsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListEventsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListEventsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEventsRequest(val *ListEventsRequest) *NullableListEventsRequest {
	return &NullableListEventsRequest{value: val, isSet: true}
}

func (v NullableListEventsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEventsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


