/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the WSUnsubscribeMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WSUnsubscribeMessage{}

// WSUnsubscribeMessage struct for WSUnsubscribeMessage
type WSUnsubscribeMessage struct {
	Type *string `json:"type,omitempty"`
	Channel *string `json:"channel,omitempty"`
	SessionId *string `json:"session_id,omitempty"`
}

// NewWSUnsubscribeMessage instantiates a new WSUnsubscribeMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWSUnsubscribeMessage() *WSUnsubscribeMessage {
	this := WSUnsubscribeMessage{}
	return &this
}

// NewWSUnsubscribeMessageWithDefaults instantiates a new WSUnsubscribeMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWSUnsubscribeMessageWithDefaults() *WSUnsubscribeMessage {
	this := WSUnsubscribeMessage{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WSUnsubscribeMessage) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WSUnsubscribeMessage) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WSUnsubscribeMessage) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WSUnsubscribeMessage) SetType(v string) {
	o.Type = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *WSUnsubscribeMessage) GetChannel() string {
	if o == nil || IsNil(o.Channel) {
		var ret string
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WSUnsubscribeMessage) GetChannelOk() (*string, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *WSUnsubscribeMessage) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given string and assigns it to the Channel field.
func (o *WSUnsubscribeMessage) SetChannel(v string) {
	o.Channel = &v
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *WSUnsubscribeMessage) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WSUnsubscribeMessage) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *WSUnsubscribeMessage) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *WSUnsubscribeMessage) SetSessionId(v string) {
	o.SessionId = &v
}

func (o WSUnsubscribeMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WSUnsubscribeMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.SessionId) {
		toSerialize["session_id"] = o.SessionId
	}
	return toSerialize, nil
}

type NullableWSUnsubscribeMessage struct {
	value *WSUnsubscribeMessage
	isSet bool
}

func (v NullableWSUnsubscribeMessage) Get() *WSUnsubscribeMessage {
	return v.value
}

func (v *NullableWSUnsubscribeMessage) Set(val *WSUnsubscribeMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableWSUnsubscribeMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableWSUnsubscribeMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWSUnsubscribeMessage(val *WSUnsubscribeMessage) *NullableWSUnsubscribeMessage {
	return &NullableWSUnsubscribeMessage{value: val, isSet: true}
}

func (v NullableWSUnsubscribeMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWSUnsubscribeMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


