/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the PipelineService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineService{}

// PipelineService struct for PipelineService
type PipelineService struct {
	Mu map[string]interface{} `json:"mu,omitempty"`
	Pipelines NullableString `json:"pipelines,omitempty"`
}

// NewPipelineService instantiates a new PipelineService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineService() *PipelineService {
	this := PipelineService{}
	return &this
}

// NewPipelineServiceWithDefaults instantiates a new PipelineService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineServiceWithDefaults() *PipelineService {
	this := PipelineService{}
	return &this
}

// GetMu returns the Mu field value if set, zero value otherwise.
func (o *PipelineService) GetMu() map[string]interface{} {
	if o == nil || IsNil(o.Mu) {
		var ret map[string]interface{}
		return ret
	}
	return o.Mu
}

// GetMuOk returns a tuple with the Mu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineService) GetMuOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Mu) {
		return map[string]interface{}{}, false
	}
	return o.Mu, true
}

// HasMu returns a boolean if a field has been set.
func (o *PipelineService) HasMu() bool {
	if o != nil && !IsNil(o.Mu) {
		return true
	}

	return false
}

// SetMu gets a reference to the given map[string]interface{} and assigns it to the Mu field.
func (o *PipelineService) SetMu(v map[string]interface{}) {
	o.Mu = v
}

// GetPipelines returns the Pipelines field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PipelineService) GetPipelines() string {
	if o == nil || IsNil(o.Pipelines.Get()) {
		var ret string
		return ret
	}
	return *o.Pipelines.Get()
}

// GetPipelinesOk returns a tuple with the Pipelines field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PipelineService) GetPipelinesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pipelines.Get(), o.Pipelines.IsSet()
}

// HasPipelines returns a boolean if a field has been set.
func (o *PipelineService) HasPipelines() bool {
	if o != nil && o.Pipelines.IsSet() {
		return true
	}

	return false
}

// SetPipelines gets a reference to the given NullableString and assigns it to the Pipelines field.
func (o *PipelineService) SetPipelines(v string) {
	o.Pipelines.Set(&v)
}
// SetPipelinesNil sets the value for Pipelines to be an explicit nil
func (o *PipelineService) SetPipelinesNil() {
	o.Pipelines.Set(nil)
}

// UnsetPipelines ensures that no value is present for Pipelines, not even an explicit nil
func (o *PipelineService) UnsetPipelines() {
	o.Pipelines.Unset()
}

func (o PipelineService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mu) {
		toSerialize["mu"] = o.Mu
	}
	if o.Pipelines.IsSet() {
		toSerialize["pipelines"] = o.Pipelines.Get()
	}
	return toSerialize, nil
}

type NullablePipelineService struct {
	value *PipelineService
	isSet bool
}

func (v NullablePipelineService) Get() *PipelineService {
	return v.value
}

func (v *NullablePipelineService) Set(val *PipelineService) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineService) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineService(val *PipelineService) *NullablePipelineService {
	return &NullablePipelineService{value: val, isSet: true}
}

func (v NullablePipelineService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


