/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ListEventsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEventsRequest{}

// ListEventsRequest struct for ListEventsRequest
type ListEventsRequest struct {
	TimeMinomitempty *string `json:"time_min,omitempty,omitempty"`
	TimeMaxomitempty *string `json:"time_max,omitempty,omitempty"`
	MaxResultsomitempty *int32 `json:"max_results,omitempty,omitempty"`
}

// NewListEventsRequest instantiates a new ListEventsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEventsRequest() *ListEventsRequest {
	this := ListEventsRequest{}
	return &this
}

// NewListEventsRequestWithDefaults instantiates a new ListEventsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEventsRequestWithDefaults() *ListEventsRequest {
	this := ListEventsRequest{}
	return &this
}

// GetTimeMinomitempty returns the TimeMinomitempty field value if set, zero value otherwise.
func (o *ListEventsRequest) GetTimeMinomitempty() string {
	if o == nil || IsNil(o.TimeMinomitempty) {
		var ret string
		return ret
	}
	return *o.TimeMinomitempty
}

// GetTimeMinomitemptyOk returns a tuple with the TimeMinomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEventsRequest) GetTimeMinomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.TimeMinomitempty) {
		return nil, false
	}
	return o.TimeMinomitempty, true
}

// HasTimeMinomitempty returns a boolean if a field has been set.
func (o *ListEventsRequest) HasTimeMinomitempty() bool {
	if o != nil && !IsNil(o.TimeMinomitempty) {
		return true
	}

	return false
}

// SetTimeMinomitempty gets a reference to the given string and assigns it to the TimeMinomitempty field.
func (o *ListEventsRequest) SetTimeMinomitempty(v string) {
	o.TimeMinomitempty = &v
}

// GetTimeMaxomitempty returns the TimeMaxomitempty field value if set, zero value otherwise.
func (o *ListEventsRequest) GetTimeMaxomitempty() string {
	if o == nil || IsNil(o.TimeMaxomitempty) {
		var ret string
		return ret
	}
	return *o.TimeMaxomitempty
}

// GetTimeMaxomitemptyOk returns a tuple with the TimeMaxomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEventsRequest) GetTimeMaxomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.TimeMaxomitempty) {
		return nil, false
	}
	return o.TimeMaxomitempty, true
}

// HasTimeMaxomitempty returns a boolean if a field has been set.
func (o *ListEventsRequest) HasTimeMaxomitempty() bool {
	if o != nil && !IsNil(o.TimeMaxomitempty) {
		return true
	}

	return false
}

// SetTimeMaxomitempty gets a reference to the given string and assigns it to the TimeMaxomitempty field.
func (o *ListEventsRequest) SetTimeMaxomitempty(v string) {
	o.TimeMaxomitempty = &v
}

// GetMaxResultsomitempty returns the MaxResultsomitempty field value if set, zero value otherwise.
func (o *ListEventsRequest) GetMaxResultsomitempty() int32 {
	if o == nil || IsNil(o.MaxResultsomitempty) {
		var ret int32
		return ret
	}
	return *o.MaxResultsomitempty
}

// GetMaxResultsomitemptyOk returns a tuple with the MaxResultsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListEventsRequest) GetMaxResultsomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxResultsomitempty) {
		return nil, false
	}
	return o.MaxResultsomitempty, true
}

// HasMaxResultsomitempty returns a boolean if a field has been set.
func (o *ListEventsRequest) HasMaxResultsomitempty() bool {
	if o != nil && !IsNil(o.MaxResultsomitempty) {
		return true
	}

	return false
}

// SetMaxResultsomitempty gets a reference to the given int32 and assigns it to the MaxResultsomitempty field.
func (o *ListEventsRequest) SetMaxResultsomitempty(v int32) {
	o.MaxResultsomitempty = &v
}

func (o ListEventsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEventsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TimeMinomitempty) {
		toSerialize["time_min,omitempty"] = o.TimeMinomitempty
	}
	if !IsNil(o.TimeMaxomitempty) {
		toSerialize["time_max,omitempty"] = o.TimeMaxomitempty
	}
	if !IsNil(o.MaxResultsomitempty) {
		toSerialize["max_results,omitempty"] = o.MaxResultsomitempty
	}
	return toSerialize, nil
}

type NullableListEventsRequest struct {
	value *ListEventsRequest
	isSet bool
}

func (v NullableListEventsRequest) Get() *ListEventsRequest {
	return v.value
}

func (v *NullableListEventsRequest) Set(val *ListEventsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListEventsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListEventsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEventsRequest(val *ListEventsRequest) *NullableListEventsRequest {
	return &NullableListEventsRequest{value: val, isSet: true}
}

func (v NullableListEventsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEventsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


