/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublishRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishRequest{}

// PublishRequest struct for PublishRequest
type PublishRequest struct {
	Topic string `json:"topic"`
	Type string `json:"type"`
	Sourceomitempty *string `json:"source,omitempty,omitempty"`
	Payloadomitempty NullableString `json:"payload,omitempty,omitempty"`
}

type _PublishRequest PublishRequest

// NewPublishRequest instantiates a new PublishRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishRequest(topic string, type_ string) *PublishRequest {
	this := PublishRequest{}
	this.Topic = topic
	this.Type = type_
	return &this
}

// NewPublishRequestWithDefaults instantiates a new PublishRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishRequestWithDefaults() *PublishRequest {
	this := PublishRequest{}
	return &this
}

// GetTopic returns the Topic field value
func (o *PublishRequest) GetTopic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Topic
}

// GetTopicOk returns a tuple with the Topic field value
// and a boolean to check if the value has been set.
func (o *PublishRequest) GetTopicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Topic, true
}

// SetTopic sets field value
func (o *PublishRequest) SetTopic(v string) {
	o.Topic = v
}

// GetType returns the Type field value
func (o *PublishRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PublishRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PublishRequest) SetType(v string) {
	o.Type = v
}

// GetSourceomitempty returns the Sourceomitempty field value if set, zero value otherwise.
func (o *PublishRequest) GetSourceomitempty() string {
	if o == nil || IsNil(o.Sourceomitempty) {
		var ret string
		return ret
	}
	return *o.Sourceomitempty
}

// GetSourceomitemptyOk returns a tuple with the Sourceomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishRequest) GetSourceomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Sourceomitempty) {
		return nil, false
	}
	return o.Sourceomitempty, true
}

// HasSourceomitempty returns a boolean if a field has been set.
func (o *PublishRequest) HasSourceomitempty() bool {
	if o != nil && !IsNil(o.Sourceomitempty) {
		return true
	}

	return false
}

// SetSourceomitempty gets a reference to the given string and assigns it to the Sourceomitempty field.
func (o *PublishRequest) SetSourceomitempty(v string) {
	o.Sourceomitempty = &v
}

// GetPayloadomitempty returns the Payloadomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishRequest) GetPayloadomitempty() string {
	if o == nil || IsNil(o.Payloadomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.Payloadomitempty.Get()
}

// GetPayloadomitemptyOk returns a tuple with the Payloadomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishRequest) GetPayloadomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Payloadomitempty.Get(), o.Payloadomitempty.IsSet()
}

// HasPayloadomitempty returns a boolean if a field has been set.
func (o *PublishRequest) HasPayloadomitempty() bool {
	if o != nil && o.Payloadomitempty.IsSet() {
		return true
	}

	return false
}

// SetPayloadomitempty gets a reference to the given NullableString and assigns it to the Payloadomitempty field.
func (o *PublishRequest) SetPayloadomitempty(v string) {
	o.Payloadomitempty.Set(&v)
}
// SetPayloadomitemptyNil sets the value for Payloadomitempty to be an explicit nil
func (o *PublishRequest) SetPayloadomitemptyNil() {
	o.Payloadomitempty.Set(nil)
}

// UnsetPayloadomitempty ensures that no value is present for Payloadomitempty, not even an explicit nil
func (o *PublishRequest) UnsetPayloadomitempty() {
	o.Payloadomitempty.Unset()
}

func (o PublishRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["topic"] = o.Topic
	toSerialize["type"] = o.Type
	if !IsNil(o.Sourceomitempty) {
		toSerialize["source,omitempty"] = o.Sourceomitempty
	}
	if o.Payloadomitempty.IsSet() {
		toSerialize["payload,omitempty"] = o.Payloadomitempty.Get()
	}
	return toSerialize, nil
}

func (o *PublishRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"topic",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublishRequest := _PublishRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublishRequest)

	if err != nil {
		return err
	}

	*o = PublishRequest(varPublishRequest)

	return err
}

type NullablePublishRequest struct {
	value *PublishRequest
	isSet bool
}

func (v NullablePublishRequest) Get() *PublishRequest {
	return v.value
}

func (v *NullablePublishRequest) Set(val *PublishRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishRequest(val *PublishRequest) *NullablePublishRequest {
	return &NullablePublishRequest{value: val, isSet: true}
}

func (v NullablePublishRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


