/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShellJobConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShellJobConfig{}

// ShellJobConfig struct for ShellJobConfig
type ShellJobConfig struct {
	Command string `json:"command"`
	Argsomitempty NullableString `json:"args,omitempty,omitempty"`
	WorkDiromitempty *string `json:"work_dir,omitempty,omitempty"`
	Envomitempty NullableString `json:"env,omitempty,omitempty"`
	TimeoutSecsomitempty *int32 `json:"timeout_secs,omitempty,omitempty"`
	CaptureOutput bool `json:"capture_output"`
}

type _ShellJobConfig ShellJobConfig

// NewShellJobConfig instantiates a new ShellJobConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShellJobConfig(command string, captureOutput bool) *ShellJobConfig {
	this := ShellJobConfig{}
	this.Command = command
	this.CaptureOutput = captureOutput
	return &this
}

// NewShellJobConfigWithDefaults instantiates a new ShellJobConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShellJobConfigWithDefaults() *ShellJobConfig {
	this := ShellJobConfig{}
	return &this
}

// GetCommand returns the Command field value
func (o *ShellJobConfig) GetCommand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Command
}

// GetCommandOk returns a tuple with the Command field value
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetCommandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Command, true
}

// SetCommand sets field value
func (o *ShellJobConfig) SetCommand(v string) {
	o.Command = v
}

// GetArgsomitempty returns the Argsomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShellJobConfig) GetArgsomitempty() string {
	if o == nil || IsNil(o.Argsomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.Argsomitempty.Get()
}

// GetArgsomitemptyOk returns a tuple with the Argsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShellJobConfig) GetArgsomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Argsomitempty.Get(), o.Argsomitempty.IsSet()
}

// HasArgsomitempty returns a boolean if a field has been set.
func (o *ShellJobConfig) HasArgsomitempty() bool {
	if o != nil && o.Argsomitempty.IsSet() {
		return true
	}

	return false
}

// SetArgsomitempty gets a reference to the given NullableString and assigns it to the Argsomitempty field.
func (o *ShellJobConfig) SetArgsomitempty(v string) {
	o.Argsomitempty.Set(&v)
}
// SetArgsomitemptyNil sets the value for Argsomitempty to be an explicit nil
func (o *ShellJobConfig) SetArgsomitemptyNil() {
	o.Argsomitempty.Set(nil)
}

// UnsetArgsomitempty ensures that no value is present for Argsomitempty, not even an explicit nil
func (o *ShellJobConfig) UnsetArgsomitempty() {
	o.Argsomitempty.Unset()
}

// GetWorkDiromitempty returns the WorkDiromitempty field value if set, zero value otherwise.
func (o *ShellJobConfig) GetWorkDiromitempty() string {
	if o == nil || IsNil(o.WorkDiromitempty) {
		var ret string
		return ret
	}
	return *o.WorkDiromitempty
}

// GetWorkDiromitemptyOk returns a tuple with the WorkDiromitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetWorkDiromitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.WorkDiromitempty) {
		return nil, false
	}
	return o.WorkDiromitempty, true
}

// HasWorkDiromitempty returns a boolean if a field has been set.
func (o *ShellJobConfig) HasWorkDiromitempty() bool {
	if o != nil && !IsNil(o.WorkDiromitempty) {
		return true
	}

	return false
}

// SetWorkDiromitempty gets a reference to the given string and assigns it to the WorkDiromitempty field.
func (o *ShellJobConfig) SetWorkDiromitempty(v string) {
	o.WorkDiromitempty = &v
}

// GetEnvomitempty returns the Envomitempty field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShellJobConfig) GetEnvomitempty() string {
	if o == nil || IsNil(o.Envomitempty.Get()) {
		var ret string
		return ret
	}
	return *o.Envomitempty.Get()
}

// GetEnvomitemptyOk returns a tuple with the Envomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShellJobConfig) GetEnvomitemptyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Envomitempty.Get(), o.Envomitempty.IsSet()
}

// HasEnvomitempty returns a boolean if a field has been set.
func (o *ShellJobConfig) HasEnvomitempty() bool {
	if o != nil && o.Envomitempty.IsSet() {
		return true
	}

	return false
}

// SetEnvomitempty gets a reference to the given NullableString and assigns it to the Envomitempty field.
func (o *ShellJobConfig) SetEnvomitempty(v string) {
	o.Envomitempty.Set(&v)
}
// SetEnvomitemptyNil sets the value for Envomitempty to be an explicit nil
func (o *ShellJobConfig) SetEnvomitemptyNil() {
	o.Envomitempty.Set(nil)
}

// UnsetEnvomitempty ensures that no value is present for Envomitempty, not even an explicit nil
func (o *ShellJobConfig) UnsetEnvomitempty() {
	o.Envomitempty.Unset()
}

// GetTimeoutSecsomitempty returns the TimeoutSecsomitempty field value if set, zero value otherwise.
func (o *ShellJobConfig) GetTimeoutSecsomitempty() int32 {
	if o == nil || IsNil(o.TimeoutSecsomitempty) {
		var ret int32
		return ret
	}
	return *o.TimeoutSecsomitempty
}

// GetTimeoutSecsomitemptyOk returns a tuple with the TimeoutSecsomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetTimeoutSecsomitemptyOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeoutSecsomitempty) {
		return nil, false
	}
	return o.TimeoutSecsomitempty, true
}

// HasTimeoutSecsomitempty returns a boolean if a field has been set.
func (o *ShellJobConfig) HasTimeoutSecsomitempty() bool {
	if o != nil && !IsNil(o.TimeoutSecsomitempty) {
		return true
	}

	return false
}

// SetTimeoutSecsomitempty gets a reference to the given int32 and assigns it to the TimeoutSecsomitempty field.
func (o *ShellJobConfig) SetTimeoutSecsomitempty(v int32) {
	o.TimeoutSecsomitempty = &v
}

// GetCaptureOutput returns the CaptureOutput field value
func (o *ShellJobConfig) GetCaptureOutput() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CaptureOutput
}

// GetCaptureOutputOk returns a tuple with the CaptureOutput field value
// and a boolean to check if the value has been set.
func (o *ShellJobConfig) GetCaptureOutputOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CaptureOutput, true
}

// SetCaptureOutput sets field value
func (o *ShellJobConfig) SetCaptureOutput(v bool) {
	o.CaptureOutput = v
}

func (o ShellJobConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShellJobConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["command"] = o.Command
	if o.Argsomitempty.IsSet() {
		toSerialize["args,omitempty"] = o.Argsomitempty.Get()
	}
	if !IsNil(o.WorkDiromitempty) {
		toSerialize["work_dir,omitempty"] = o.WorkDiromitempty
	}
	if o.Envomitempty.IsSet() {
		toSerialize["env,omitempty"] = o.Envomitempty.Get()
	}
	if !IsNil(o.TimeoutSecsomitempty) {
		toSerialize["timeout_secs,omitempty"] = o.TimeoutSecsomitempty
	}
	toSerialize["capture_output"] = o.CaptureOutput
	return toSerialize, nil
}

func (o *ShellJobConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"command",
		"capture_output",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShellJobConfig := _ShellJobConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShellJobConfig)

	if err != nil {
		return err
	}

	*o = ShellJobConfig(varShellJobConfig)

	return err
}

type NullableShellJobConfig struct {
	value *ShellJobConfig
	isSet bool
}

func (v NullableShellJobConfig) Get() *ShellJobConfig {
	return v.value
}

func (v *NullableShellJobConfig) Set(val *ShellJobConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableShellJobConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableShellJobConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShellJobConfig(val *ShellJobConfig) *NullableShellJobConfig {
	return &NullableShellJobConfig{value: val, isSet: true}
}

func (v NullableShellJobConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShellJobConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


