/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
)

// checks if the ChatService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatService{}

// ChatService struct for ChatService
type ChatService struct {
	Bus map[string]interface{} `json:"bus,omitempty"`
	AgentRegistry map[string]interface{} `json:"agentRegistry,omitempty"`
	SessionStore map[string]interface{} `json:"sessionStore,omitempty"`
	Logger map[string]interface{} `json:"logger,omitempty"`
}

// NewChatService instantiates a new ChatService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatService() *ChatService {
	this := ChatService{}
	return &this
}

// NewChatServiceWithDefaults instantiates a new ChatService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatServiceWithDefaults() *ChatService {
	this := ChatService{}
	return &this
}

// GetBus returns the Bus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatService) GetBus() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Bus
}

// GetBusOk returns a tuple with the Bus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatService) GetBusOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Bus) {
		return map[string]interface{}{}, false
	}
	return o.Bus, true
}

// HasBus returns a boolean if a field has been set.
func (o *ChatService) HasBus() bool {
	if o != nil && !IsNil(o.Bus) {
		return true
	}

	return false
}

// SetBus gets a reference to the given map[string]interface{} and assigns it to the Bus field.
func (o *ChatService) SetBus(v map[string]interface{}) {
	o.Bus = v
}

// GetAgentRegistry returns the AgentRegistry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatService) GetAgentRegistry() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AgentRegistry
}

// GetAgentRegistryOk returns a tuple with the AgentRegistry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatService) GetAgentRegistryOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AgentRegistry) {
		return map[string]interface{}{}, false
	}
	return o.AgentRegistry, true
}

// HasAgentRegistry returns a boolean if a field has been set.
func (o *ChatService) HasAgentRegistry() bool {
	if o != nil && !IsNil(o.AgentRegistry) {
		return true
	}

	return false
}

// SetAgentRegistry gets a reference to the given map[string]interface{} and assigns it to the AgentRegistry field.
func (o *ChatService) SetAgentRegistry(v map[string]interface{}) {
	o.AgentRegistry = v
}

// GetSessionStore returns the SessionStore field value if set, zero value otherwise.
func (o *ChatService) GetSessionStore() map[string]interface{} {
	if o == nil || IsNil(o.SessionStore) {
		var ret map[string]interface{}
		return ret
	}
	return o.SessionStore
}

// GetSessionStoreOk returns a tuple with the SessionStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatService) GetSessionStoreOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.SessionStore) {
		return map[string]interface{}{}, false
	}
	return o.SessionStore, true
}

// HasSessionStore returns a boolean if a field has been set.
func (o *ChatService) HasSessionStore() bool {
	if o != nil && !IsNil(o.SessionStore) {
		return true
	}

	return false
}

// SetSessionStore gets a reference to the given map[string]interface{} and assigns it to the SessionStore field.
func (o *ChatService) SetSessionStore(v map[string]interface{}) {
	o.SessionStore = v
}

// GetLogger returns the Logger field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatService) GetLogger() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Logger
}

// GetLoggerOk returns a tuple with the Logger field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatService) GetLoggerOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Logger) {
		return map[string]interface{}{}, false
	}
	return o.Logger, true
}

// HasLogger returns a boolean if a field has been set.
func (o *ChatService) HasLogger() bool {
	if o != nil && !IsNil(o.Logger) {
		return true
	}

	return false
}

// SetLogger gets a reference to the given map[string]interface{} and assigns it to the Logger field.
func (o *ChatService) SetLogger(v map[string]interface{}) {
	o.Logger = v
}

func (o ChatService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Bus != nil {
		toSerialize["bus"] = o.Bus
	}
	if o.AgentRegistry != nil {
		toSerialize["agentRegistry"] = o.AgentRegistry
	}
	if !IsNil(o.SessionStore) {
		toSerialize["sessionStore"] = o.SessionStore
	}
	if o.Logger != nil {
		toSerialize["logger"] = o.Logger
	}
	return toSerialize, nil
}

type NullableChatService struct {
	value *ChatService
	isSet bool
}

func (v NullableChatService) Get() *ChatService {
	return v.value
}

func (v *NullableChatService) Set(val *ChatService) {
	v.value = val
	v.isSet = true
}

func (v NullableChatService) IsSet() bool {
	return v.isSet
}

func (v *NullableChatService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatService(val *ChatService) *NullableChatService {
	return &NullableChatService{value: val, isSet: true}
}

func (v NullableChatService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


