/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddJobRequest{}

// AddJobRequest struct for AddJobRequest
type AddJobRequest struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Schedule string `json:"schedule"`
	Type string `json:"type"`
	AgentConfig map[string]interface{} `json:"agent_config,omitempty"`
	ShellConfig map[string]interface{} `json:"shell_config,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
}

type _AddJobRequest AddJobRequest

// NewAddJobRequest instantiates a new AddJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddJobRequest(id string, name string, schedule string, type_ string) *AddJobRequest {
	this := AddJobRequest{}
	this.Id = id
	this.Name = name
	this.Schedule = schedule
	this.Type = type_
	return &this
}

// NewAddJobRequestWithDefaults instantiates a new AddJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddJobRequestWithDefaults() *AddJobRequest {
	this := AddJobRequest{}
	return &this
}

// GetId returns the Id field value
func (o *AddJobRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AddJobRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AddJobRequest) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *AddJobRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddJobRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddJobRequest) SetName(v string) {
	o.Name = v
}

// GetSchedule returns the Schedule field value
func (o *AddJobRequest) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *AddJobRequest) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *AddJobRequest) SetSchedule(v string) {
	o.Schedule = v
}

// GetType returns the Type field value
func (o *AddJobRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AddJobRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AddJobRequest) SetType(v string) {
	o.Type = v
}

// GetAgentConfig returns the AgentConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddJobRequest) GetAgentConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AgentConfig
}

// GetAgentConfigOk returns a tuple with the AgentConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddJobRequest) GetAgentConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AgentConfig) {
		return map[string]interface{}{}, false
	}
	return o.AgentConfig, true
}

// HasAgentConfig returns a boolean if a field has been set.
func (o *AddJobRequest) HasAgentConfig() bool {
	if o != nil && !IsNil(o.AgentConfig) {
		return true
	}

	return false
}

// SetAgentConfig gets a reference to the given map[string]interface{} and assigns it to the AgentConfig field.
func (o *AddJobRequest) SetAgentConfig(v map[string]interface{}) {
	o.AgentConfig = v
}

// GetShellConfig returns the ShellConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddJobRequest) GetShellConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.ShellConfig
}

// GetShellConfigOk returns a tuple with the ShellConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddJobRequest) GetShellConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ShellConfig) {
		return map[string]interface{}{}, false
	}
	return o.ShellConfig, true
}

// HasShellConfig returns a boolean if a field has been set.
func (o *AddJobRequest) HasShellConfig() bool {
	if o != nil && !IsNil(o.ShellConfig) {
		return true
	}

	return false
}

// SetShellConfig gets a reference to the given map[string]interface{} and assigns it to the ShellConfig field.
func (o *AddJobRequest) SetShellConfig(v map[string]interface{}) {
	o.ShellConfig = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AddJobRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddJobRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AddJobRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AddJobRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o AddJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["schedule"] = o.Schedule
	toSerialize["type"] = o.Type
	if o.AgentConfig != nil {
		toSerialize["agent_config"] = o.AgentConfig
	}
	if o.ShellConfig != nil {
		toSerialize["shell_config"] = o.ShellConfig
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

func (o *AddJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"schedule",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddJobRequest := _AddJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddJobRequest)

	if err != nil {
		return err
	}

	*o = AddJobRequest(varAddJobRequest)

	return err
}

type NullableAddJobRequest struct {
	value *AddJobRequest
	isSet bool
}

func (v NullableAddJobRequest) Get() *AddJobRequest {
	return v.value
}

func (v *NullableAddJobRequest) Set(val *AddJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddJobRequest(val *AddJobRequest) *NullableAddJobRequest {
	return &NullableAddJobRequest{value: val, isSet: true}
}

func (v NullableAddJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


