/*
Meept HTTP API

REST API for Meept daemon - exposes chat, memory, task queue, skills, and self-improvement capabilities

API version: 0.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meeptclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterProjectRequest{}

// RegisterProjectRequest struct for RegisterProjectRequest
type RegisterProjectRequest struct {
	Idomitempty *string `json:"id,omitempty,omitempty"`
	Name string `json:"name"`
	GitUrlomitempty *string `json:"git_url,omitempty,omitempty"`
	LocalPathomitempty *string `json:"local_path,omitempty,omitempty"`
}

type _RegisterProjectRequest RegisterProjectRequest

// NewRegisterProjectRequest instantiates a new RegisterProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterProjectRequest(name string) *RegisterProjectRequest {
	this := RegisterProjectRequest{}
	this.Name = name
	return &this
}

// NewRegisterProjectRequestWithDefaults instantiates a new RegisterProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterProjectRequestWithDefaults() *RegisterProjectRequest {
	this := RegisterProjectRequest{}
	return &this
}

// GetIdomitempty returns the Idomitempty field value if set, zero value otherwise.
func (o *RegisterProjectRequest) GetIdomitempty() string {
	if o == nil || IsNil(o.Idomitempty) {
		var ret string
		return ret
	}
	return *o.Idomitempty
}

// GetIdomitemptyOk returns a tuple with the Idomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetIdomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.Idomitempty) {
		return nil, false
	}
	return o.Idomitempty, true
}

// HasIdomitempty returns a boolean if a field has been set.
func (o *RegisterProjectRequest) HasIdomitempty() bool {
	if o != nil && !IsNil(o.Idomitempty) {
		return true
	}

	return false
}

// SetIdomitempty gets a reference to the given string and assigns it to the Idomitempty field.
func (o *RegisterProjectRequest) SetIdomitempty(v string) {
	o.Idomitempty = &v
}

// GetName returns the Name field value
func (o *RegisterProjectRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegisterProjectRequest) SetName(v string) {
	o.Name = v
}

// GetGitUrlomitempty returns the GitUrlomitempty field value if set, zero value otherwise.
func (o *RegisterProjectRequest) GetGitUrlomitempty() string {
	if o == nil || IsNil(o.GitUrlomitempty) {
		var ret string
		return ret
	}
	return *o.GitUrlomitempty
}

// GetGitUrlomitemptyOk returns a tuple with the GitUrlomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetGitUrlomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.GitUrlomitempty) {
		return nil, false
	}
	return o.GitUrlomitempty, true
}

// HasGitUrlomitempty returns a boolean if a field has been set.
func (o *RegisterProjectRequest) HasGitUrlomitempty() bool {
	if o != nil && !IsNil(o.GitUrlomitempty) {
		return true
	}

	return false
}

// SetGitUrlomitempty gets a reference to the given string and assigns it to the GitUrlomitempty field.
func (o *RegisterProjectRequest) SetGitUrlomitempty(v string) {
	o.GitUrlomitempty = &v
}

// GetLocalPathomitempty returns the LocalPathomitempty field value if set, zero value otherwise.
func (o *RegisterProjectRequest) GetLocalPathomitempty() string {
	if o == nil || IsNil(o.LocalPathomitempty) {
		var ret string
		return ret
	}
	return *o.LocalPathomitempty
}

// GetLocalPathomitemptyOk returns a tuple with the LocalPathomitempty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterProjectRequest) GetLocalPathomitemptyOk() (*string, bool) {
	if o == nil || IsNil(o.LocalPathomitempty) {
		return nil, false
	}
	return o.LocalPathomitempty, true
}

// HasLocalPathomitempty returns a boolean if a field has been set.
func (o *RegisterProjectRequest) HasLocalPathomitempty() bool {
	if o != nil && !IsNil(o.LocalPathomitempty) {
		return true
	}

	return false
}

// SetLocalPathomitempty gets a reference to the given string and assigns it to the LocalPathomitempty field.
func (o *RegisterProjectRequest) SetLocalPathomitempty(v string) {
	o.LocalPathomitempty = &v
}

func (o RegisterProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Idomitempty) {
		toSerialize["id,omitempty"] = o.Idomitempty
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.GitUrlomitempty) {
		toSerialize["git_url,omitempty"] = o.GitUrlomitempty
	}
	if !IsNil(o.LocalPathomitempty) {
		toSerialize["local_path,omitempty"] = o.LocalPathomitempty
	}
	return toSerialize, nil
}

func (o *RegisterProjectRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterProjectRequest := _RegisterProjectRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterProjectRequest)

	if err != nil {
		return err
	}

	*o = RegisterProjectRequest(varRegisterProjectRequest)

	return err
}

type NullableRegisterProjectRequest struct {
	value *RegisterProjectRequest
	isSet bool
}

func (v NullableRegisterProjectRequest) Get() *RegisterProjectRequest {
	return v.value
}

func (v *NullableRegisterProjectRequest) Set(val *RegisterProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterProjectRequest(val *RegisterProjectRequest) *NullableRegisterProjectRequest {
	return &NullableRegisterProjectRequest{value: val, isSet: true}
}

func (v NullableRegisterProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


