package preferences

import (
	"fmt"
	"os"
	"path/filepath"
)

// GeneratePreCommitHook generates a git pre-commit hook script.
func GeneratePreCommitHook(hookPath string) error {
	script := `#!/bin/bash
# Auto-generated by Meept User Instructions
# DO NOT EDIT MANUALLY

# Execute git_pre_commit instructions
meept rpc call instruction.execute_git_hook '{"type": "pre_commit"}'
exit_code=$?

if [ $exit_code -ne 0 ]; then
    echo "Git pre-commit instruction failed"
    exit 1
fi

exit 0
`
	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(hookPath), 0755); err != nil {
		return fmt.Errorf("failed to create hook directory: %w", err)
	}

	// Write hook script
	if err := os.WriteFile(hookPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write hook script: %w", err)
	}

	return nil
}

// GeneratePostCommitHook generates a git post-commit hook script.
func GeneratePostCommitHook(hookPath string) error {
	script := `#!/bin/bash
# Auto-generated by Meept User Instructions
# DO NOT EDIT MANUALLY

# Execute git_post_commit instructions (non-blocking)
meept rpc call instruction.execute_git_hook '{"type": "post_commit"}' &

exit 0
`
	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(hookPath), 0755); err != nil {
		return fmt.Errorf("failed to create hook directory: %w", err)
	}

	// Write hook script
	if err := os.WriteFile(hookPath, []byte(script), 0755); err != nil {
		return fmt.Errorf("failed to write hook script: %w", err)
	}

	return nil
}
