// Code generated by "stringer -linecomment -type=PairModality -output=internal/agent/pairmodality_string.go internal/agent/pair_modality.go"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PairModalityNone-0]
	_ = x[PairModalitySpecReview-1]
	_ = x[PairModalityPairSession-2]
	_ = x[PairModalityDebate-3]
	_ = x[PairModalityInline-4]
}

const _PairModality_name = "PairModalityNonePairModalitySpecReviewPairModalityPairSessionPairModalityDebatePairModalityInline"

var _PairModality_index = [...]uint8{0, 16, 38, 61, 79, 97}

func (i PairModality) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PairModality_index)-1 {
		return "PairModality(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PairModality_name[_PairModality_index[idx]:_PairModality_index[idx+1]]
}
