package tools

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/caimlas/meept/internal/code/ast"
	"github.com/caimlas/meept/internal/llm"
	"github.com/caimlas/meept/internal/tools"
)

// ASTResolveTool applies or discards pending AST edit proposals.
type ASTResolveTool struct{}

// NewASTResolveTool creates a new AST resolve tool.
func NewASTResolveTool() (*ASTResolveTool, error) {
	return &ASTResolveTool{}, nil
}

func (t *ASTResolveTool) Name() string { return "ast_resolve" }

func (t *ASTResolveTool) Category() string { return "code" }

func (t *ASTResolveTool) Description() string {
	return `Apply or discard a pending AST edit proposal generated by the "ast_edit" tool.
Pass the same file_path and the proposed_edits JSON array from ast_edit output.
Set apply=true to write changes to disk, apply=false to discard.`
}

func (t *ASTResolveTool) Parameters() llm.FunctionParameters {
	return llm.FunctionParameters{
		Type: SchemaTypeObject,
		Properties: map[string]llm.ParameterProperty{
			SchemaPropFilePath: {
				Type:        SchemaTypeString,
				Description: "Path to the source file containing the edits.",
			},
			"apply": {
				Type:        SchemaTypeBoolean,
				Description: "If true, apply the edits to disk. If false, discard the proposal.",
			},
			"edits_json": {
				Type:        SchemaTypeString,
				Description: "JSON array of proposed edits from ast_edit output. Each edit must have start_line, start_column, end_line, end_column, and new_text.",
			},
		},
		Required: []string{SchemaPropFilePath, "apply"},
	}
}

func (t *ASTResolveTool) Execute(ctx context.Context, args map[string]any) (any, error) {
	filePath, _ := args[SchemaPropFilePath].(string)
	if filePath == "" {
		return nil, fmt.Errorf("file_path is required")
	}

	apply, ok := args["apply"].(bool)
	if !ok {
		return nil, fmt.Errorf("apply is required")
	}

	if !apply {
		return map[string]any{
			SchemaPropMessage:  "proposal discarded",
			SchemaPropFilePath: filePath,
			"applied":          false,
		}, nil
	}

	// Parse edits from JSON string
	editsJSON, _ := args["edits_json"].(string)
	if editsJSON == "" {
		return nil, fmt.Errorf("edits_json is required when apply=true")
	}

	var rawEdits []map[string]any
	if err := json.Unmarshal([]byte(editsJSON), &rawEdits); err != nil {
		return nil, fmt.Errorf("invalid edits_json: %w", err)
	}

	edits := make([]ast.EditProposal, 0, len(rawEdits))
	for i, e := range rawEdits {
		edit := ast.EditProposal{FilePath: filePath}

		if v, ok := e["start_line"].(float64); ok {
			edit.StartLine = int(v)
		}
		if v, ok := e["start_column"].(float64); ok {
			edit.StartCol = int(v)
		}
		if v, ok := e["end_line"].(float64); ok {
			edit.EndLine = int(v)
		}
		if v, ok := e["end_column"].(float64); ok {
			edit.EndCol = int(v)
		}
		if v, ok := e["new_text"].(string); ok {
			edit.NewText = v
		}

		if edit.StartLine == 0 && edit.StartCol == 0 && edit.EndLine == 0 && edit.EndCol == 0 {
			return nil, fmt.Errorf("edit %d has invalid range", i)
		}

		edits = append(edits, edit)
	}

	if err := ast.ApplyEdits(filePath, edits); err != nil {
		return nil, fmt.Errorf("failed to apply edits: %w", err)
	}

	return map[string]any{
		SchemaPropMessage:  fmt.Sprintf("applied %d edits to %s", len(edits), filePath),
		SchemaPropFilePath: filePath,
		"applied":          true,
		SchemaPropCount:    len(edits),
	}, nil
}

// Ensure tool implements the Tool interface
var _ tools.Tool = (*ASTResolveTool)(nil)
