// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (Serializers().toBuilder()
      ..add(AddJobRequest.serializer)
      ..add(AddJobResponse.serializer)
      ..add(AddWorkerRequest.serializer)
      ..add(AgentJobConfig.serializer)
      ..add(AgentProgressEvent.serializer)
      ..add(AgentProgressEventTypeEnum.serializer)
      ..add(ApplyImprovementRequest.serializer)
      ..add(ApprovePlanRequest.serializer)
      ..add(AttachSessionRequest.serializer)
      ..add(AttendeeInfo.serializer)
      ..add(AuditEntry.serializer)
      ..add(AuditRequest.serializer)
      ..add(BranchSessionRequest.serializer)
      ..add(BusService.serializer)
      ..add(BusStatsResponse.serializer)
      ..add(CacheInspectResult.serializer)
      ..add(CacheService.serializer)
      ..add(CacheStatsResponse.serializer)
      ..add(CalendarEvent.serializer)
      ..add(CalendarService.serializer)
      ..add(CancelRequest.serializer)
      ..add(CancelTaskRequest.serializer)
      ..add(ChatRequest.serializer)
      ..add(ChatResponse.serializer)
      ..add(ChatService.serializer)
      ..add(CheckRequest.serializer)
      ..add(CheckResponse.serializer)
      ..add(ClaimRequest.serializer)
      ..add(ClearCacheRequest.serializer)
      ..add(CommandHistory.serializer)
      ..add(CompactSessionRequest.serializer)
      ..add(CompleteRequest.serializer)
      ..add(Config.serializer)
      ..add(ConfirmPlanRequest.serializer)
      ..add(CreateEventRequest.serializer)
      ..add(CreatePipelineRequest.serializer)
      ..add(CreatePlanRequest.serializer)
      ..add(CreateSessionRequest.serializer)
      ..add(CreateTaskRequest.serializer)
      ..add(DaemonService.serializer)
      ..add(DaemonStatus.serializer)
      ..add(DeletePipelineRequest.serializer)
      ..add(DeleteSessionRequest.serializer)
      ..add(DeleteTaskRequest.serializer)
      ..add(DetachSessionRequest.serializer)
      ..add(EnableJobRequest.serializer)
      ..add(EnqueueRequest.serializer)
      ..add(ExecuteRequest.serializer)
      ..add(ExecuteResult.serializer)
      ..add(FailRequest.serializer)
      ..add(FollowUpRequest.serializer)
      ..add(ForkSessionRequest.serializer)
      ..add(GenerateImprovementRequest.serializer)
      ..add(GetMessagesRequest.serializer)
      ..add(GetRequest.serializer)
      ..add(GetSessionRequest.serializer)
      ..add(GetTaskRequest.serializer)
      ..add(GetTaskStepsRequest.serializer)
      ..add(GetTreeRequest.serializer)
      ..add(InvalidateRequest.serializer)
      ..add(ListBranchesRequest.serializer)
      ..add(ListEventsRequest.serializer)
      ..add(ListEventsResponse.serializer)
      ..add(ListJobsResponse.serializer)
      ..add(ListOptions.serializer)
      ..add(ListRequest.serializer)
      ..add(ListSessionsRequest.serializer)
      ..add(MemoryQueryRequest.serializer)
      ..add(MemoryResult.serializer)
      ..add(MemoryService.serializer)
      ..add(ModelInfo.serializer)
      ..add(ModelService.serializer)
      ..add(PaginatedResponse.serializer)
      ..add(PauseJobRequest.serializer)
      ..add(Pipeline.serializer)
      ..add(PipelineInfo.serializer)
      ..add(PipelineListRequest.serializer)
      ..add(PipelineService.serializer)
      ..add(PipelineStatusResponse.serializer)
      ..add(PipelineStep.serializer)
      ..add(PipelineStepStatus.serializer)
      ..add(PlanService.serializer)
      ..add(ProjectService.serializer)
      ..add(ProviderInfo.serializer)
      ..add(PublishRequest.serializer)
      ..add(QueueService.serializer)
      ..add(QueueStatusRequest.serializer)
      ..add(QueueStatusResponse.serializer)
      ..add(RegisterProjectRequest.serializer)
      ..add(RejectImprovementRequest.serializer)
      ..add(RejectPlanRequest.serializer)
      ..add(RemoveJobRequest.serializer)
      ..add(RemoveWorkerRequest.serializer)
      ..add(ResumeJobRequest.serializer)
      ..add(ResumeSessionRequest.serializer)
      ..add(RetryRequest.serializer)
      ..add(RevisePlanRequest.serializer)
      ..add(RuntimeService.serializer)
      ..add(RuntimeStatusResponse.serializer)
      ..add(ScaleWorkersRequest.serializer)
      ..add(SchedulerService.serializer)
      ..add(SearchRequest.serializer)
      ..add(SearchResult.serializer)
      ..add(SearchService.serializer)
      ..add(SecurityService.serializer)
      ..add(SelfImproveService.serializer)
      ..add(ServiceError.serializer)
      ..add(ServiceRegistry.serializer)
      ..add(SessionService.serializer)
      ..add(SetProjectRequest.serializer)
      ..add(ShardDetail.serializer)
      ..add(ShellJobConfig.serializer)
      ..add(SkillInfo.serializer)
      ..add(SkillUIDescriptor.serializer)
      ..add(SkillsGetRequest.serializer)
      ..add(SkillsListRequest.serializer)
      ..add(SkillsService.serializer)
      ..add(StatusRequest.serializer)
      ..add(StatusResponse.serializer)
      ..add(SteerRequest.serializer)
      ..add(TaskListRequest.serializer)
      ..add(TaskService.serializer)
      ..add(TemplateInfo.serializer)
      ..add(TemplatesClearRequest.serializer)
      ..add(TemplatesClearResult.serializer)
      ..add(TemplatesGetRequest.serializer)
      ..add(TemplatesInvokeRequest.serializer)
      ..add(TemplatesInvokeResult.serializer)
      ..add(TemplatesListRequest.serializer)
      ..add(TemplatesService.serializer)
      ..add(TerminalService.serializer)
      ..add(TerminalSession.serializer)
      ..add(TriggerRequest.serializer)
      ..add(UIActionDef.serializer)
      ..add(UIFieldDef.serializer)
      ..add(UpdateEventRequest.serializer)
      ..add(UpdateStatusRequest.serializer)
      ..add(UpdateTaskRequest.serializer)
      ..add(ValidateImprovementRequest.serializer)
      ..add(VectorSearchRequest.serializer)
      ..add(VectorSearchResult.serializer)
      ..add(VectorStats.serializer)
      ..add(VectorStoreRequest.serializer)
      ..add(WSSubscribeMessage.serializer)
      ..add(WSSubscribeMessageTypeEnum.serializer)
      ..add(WSUnsubscribeMessage.serializer)
      ..add(WSUnsubscribeMessageTypeEnum.serializer)
      ..add(WorkerService.serializer)
      ..add(WorkerStatsResponse.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(String)]),
          () => ListBuilder<String>()))
    .build();

// ignore_for_file: deprecated_member_use_from_same_package,type=lint
