id: instr_1782151724377123000
name: git:pre_commit
trigger: git:pre_commit
action: shell_execute
action_args:
    command: git status
enabled: true
scope: global
priority: normal
created_at: 2026-06-22T12:08:44.377124-06:00
updated_at: 2026-06-22T18:08:44.377124Z
