#!/usr/bin/env python3
"""
Verify the agent-harness literature catalog (docs/research/harness-techniques.json)
against the repository and render docs/research/harness-techniques.md.

Modes:
    python3 scripts/research-harness-lit.py            # verify evidence + render
    python3 scripts/research-harness-lit.py --check    # verify + fail if on-disk md drifted
    python3 scripts/research-harness-lit.py --search   # arXiv snapshot (network; optional)

Verification:
    Techniques with status "shipped" or "partial" must reference at least one
    evidence path that exists in the repository (file or directory). If an
    evidence entry carries "must_contain" and the path is a file, the file
    bytes must contain that substring (case-sensitive). Failures are printed
    to stderr as "MISSING <id> <path>" / "MUST_CONTAIN <id> <path> <needle>"
    and the script exits 1 before rendering anything. Candidate/skip rows are
    not evidence-checked.

Rendering:
    The markdown is fully deterministic: categories sorted alphabetically,
    techniques sorted by id within a category. Source urls starting with http
    stay absolute; repo-relative urls are rewritten relative to the markdown
    location docs/research/ (prefixed with "../"). The file is written
    atomically via a tempfile + os.replace.

Search:
    --search queries the arXiv API for each catalog "search_queries" entry,
    records docs/research/snapshots/harness-lit-YYYY-MM-DD.json, and prints
    any paper whose url is not already cited by a catalog source (potential
    new techniques). A failed or empty query records []; if every query fails
    on an unreachable network the script warns and exits 0; if every query
    fails while the network is reachable it exits 1.
"""

import argparse
import datetime
import html
import json
import os
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

CATALOG_REL = Path("docs/research/harness-techniques.json")
OUTPUT_REL = Path("docs/research/harness-techniques.md")
SNAPSHOT_DIR_REL = Path("docs/research/snapshots")
GENERATED_MARKER = "<!-- generated by scripts/research-harness-lit.py; do not edit -->"
USER_AGENT = "meept-research-harness-lit/1.0"
ARXIV_API = "http://export.arxiv.org/api/query"
ATOM_NS = "http://www.w3.org/2005/Atom"
STATUSES = ("shipped", "partial", "candidate", "skip")
EVIDENCE_REQUIRED_STATUSES = ("shipped", "partial")


# ── Repository / catalog ───────────────────────────────────────────────


def find_repo_root() -> Path:
    """Walk up from this script until a repo-root marker (go.mod or .git) is found."""
    current = Path(__file__).resolve().parent
    for candidate in [current, *current.parents]:
        if (candidate / "go.mod").exists() or (candidate / ".git").exists():
            return candidate
    print("error: could not locate repository root (no go.mod or .git)", file=sys.stderr)
    raise SystemExit(1)


def load_catalog(root: Path) -> Dict[str, Any]:
    catalog_path = root / CATALOG_REL
    with catalog_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


# ── Verification ───────────────────────────────────────────────────────


def verify_evidence(root: Path, catalog: Dict[str, Any]) -> List[str]:
    """Return one failure line per evidence problem (MISSING / MUST_CONTAIN)."""
    failures: List[str] = []
    for technique in catalog.get("techniques", []):
        tid = technique.get("id", "<no-id>")
        if technique.get("status") not in EVIDENCE_REQUIRED_STATUSES:
            continue
        evidence = technique.get("evidence") or []
        if not evidence:
            failures.append(f"MISSING {tid} (no evidence paths)")
            continue
        for entry in evidence:
            rel = entry.get("path", "")
            path = root / rel
            if not path.exists():
                failures.append(f"MISSING {tid} {rel}")
                continue
            needle = entry.get("must_contain")
            if needle is not None and path.is_file():
                if needle.encode("utf-8") not in path.read_bytes():
                    failures.append(f"MUST_CONTAIN {tid} {rel} {needle}")
    return failures


# ── Rendering ──────────────────────────────────────────────────────────


def md_escape(text: str) -> str:
    """Make a string safe inside a markdown table cell."""
    return text.replace("\r\n", " ").replace("\r", " ").replace("\n", " ").replace("|", "\\|")


def source_link(url: str, title: str, md_dir: Path, root: Path) -> str:
    """Render a source as a markdown link, rewriting repo-relative urls.

    Absolute (http) urls stay absolute. Repo-root-relative urls are resolved
    relative to the markdown's directory (docs/research/), e.g.
    "analysis/pi-agent.md" -> "../analysis/pi-agent.md" and
    "docs/research/x.md" -> "../../docs/research/x.md".
    """
    if url.startswith("http"):
        href = url
    else:
        href = Path(os.path.relpath(root / url, md_dir)).as_posix()
    return f"[{md_escape(title)}]({href})"


def render_markdown(catalog: Dict[str, Any], root: Path) -> str:
    techniques = catalog.get("techniques", [])
    md_dir = (root / OUTPUT_REL).parent

    counts: Dict[str, int] = {}
    for technique in techniques:
        status = technique.get("status", "")
        counts[status] = counts.get(status, 0) + 1

    lines: List[str] = [
        GENERATED_MARKER,
        "",
        "# Agent harness techniques vs meept",
        "",
        f"Generated from `{CATALOG_REL.as_posix()}` (version {catalog.get('version', '?')}, "
        f"updated {catalog.get('updated', '?')}). Do not edit by hand; "
        "run `python3 scripts/research-harness-lit.py` to regenerate.",
        "",
        "Status counts: " + ", ".join(f"{status} {counts.get(status, 0)}" for status in STATUSES),
        "",
    ]

    by_category: Dict[str, List[Dict[str, Any]]] = {}
    for technique in techniques:
        by_category.setdefault(technique.get("category", "uncategorized"), []).append(technique)

    for category in sorted(by_category):
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Technique | Status | Sources | Evidence | Notes |")
        lines.append("| --- | --- | --- | --- | --- |")
        for technique in sorted(by_category[category], key=lambda t: t.get("id", "")):
            source_cell = ", ".join(
                source_link(s.get("url", ""), s.get("title", ""), md_dir, root)
                for s in technique.get("sources", [])
            ) or "—"
            evidence_cell = ", ".join(
                f"`{e.get('path', '')}`" for e in technique.get("evidence", [])
            ) or "—"
            lines.append(
                f"| {md_escape(technique.get('name', ''))} "
                f"| {technique.get('status', '')} "
                f"| {source_cell} "
                f"| {evidence_cell} "
                f"| {md_escape(technique.get('notes', ''))} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def write_atomic(path: Path, content: str) -> None:
    """Write content to path atomically: tempfile in the same dir, then os.replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), prefix=path.name + ".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


# ── Commands ───────────────────────────────────────────────────────────


def command_render(root: Path, check_only: bool) -> int:
    catalog = load_catalog(root)

    failures = verify_evidence(root, catalog)
    if failures:
        for line in failures:
            print(line, file=sys.stderr)
        print(f"error: {len(failures)} evidence problem(s); not rendering", file=sys.stderr)
        return 1

    fresh = render_markdown(catalog, root)
    output = root / OUTPUT_REL

    if check_only:
        if not output.exists():
            print(
                f"DRIFT: {OUTPUT_REL.as_posix()} is missing; "
                "run: python3 scripts/research-harness-lit.py",
                file=sys.stderr,
            )
            return 1
        on_disk = output.read_text(encoding="utf-8").replace("\r\n", "\n")
        if on_disk != fresh:
            print(
                f"DRIFT: {OUTPUT_REL.as_posix()} differs from a fresh render; "
                "run: python3 scripts/research-harness-lit.py",
                file=sys.stderr,
            )
            return 1
        print(f"[OK] {OUTPUT_REL.as_posix()} matches the catalog.")
        return 0

    write_atomic(output, fresh)
    print(f"[OK] verified {len(techniques_count(catalog))} techniques; wrote {OUTPUT_REL.as_posix()}.")
    return 0


def techniques_count(catalog: Dict[str, Any]) -> List[Dict[str, Any]]:
    return catalog.get("techniques", [])


def fetch_arxiv(query: str) -> Tuple[List[Dict[str, str]], Optional[str]]:
    """Fetch one arXiv query. Returns (results, error); error is None on success.

    Results carry id/title/url plus the published year (used for stdout only).
    """
    params = urllib.parse.urlencode({
        "search_query": "all:" + query,
        "start": 0,
        "max_results": 5,
    })
    request = urllib.request.Request(ARXIV_API + "?" + params, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            payload = response.read()
    except urllib.error.HTTPError as exc:
        return [], f"HTTP {exc.code}"
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        return [], f"network: {exc}"

    try:
        root_el = ET.fromstring(payload)
    except ET.ParseError as exc:
        return [], f"xml parse: {exc}"

    results: List[Dict[str, str]] = []
    for entry in root_el.findall(f"{{{ATOM_NS}}}entry"):
        entry_id = (entry.findtext(f"{{{ATOM_NS}}}id") or "").strip()
        if not entry_id:
            continue
        title = html.unescape((entry.findtext(f"{{{ATOM_NS}}}title") or "").strip())
        title = " ".join(title.split())
        published = entry.findtext(f"{{{ATOM_NS}}}published") or ""
        results.append({"id": entry_id, "title": title, "year": published[:4], "url": entry_id})
    results.sort(key=lambda item: item["id"])
    return results, None


def command_search(root: Path, catalog: Dict[str, Any]) -> int:
    queries = catalog.get("search_queries", [])
    if not queries:
        print("warning: catalog has no search_queries; nothing to search", file=sys.stderr)
        return 0

    cited_urls = {
        source.get("url", "").strip()
        for technique in techniques_count(catalog)
        for source in technique.get("sources", [])
    }

    snapshot: Dict[str, Any] = {"date": datetime.date.today().isoformat(), "queries": {}}
    failures: List[str] = []
    offline_failures = 0
    new_count = 0

    for index, query in enumerate(queries):
        results, error = fetch_arxiv(query)
        if error is not None:
            failures.append(f"warning: arXiv query failed ({error}): {query}")
            if error.startswith("network:"):
                offline_failures += 1
            snapshot["queries"][query] = []
        else:
            snapshot["queries"][query] = [
                {"id": r["id"], "title": r["title"], "url": r["url"]} for r in results
            ]
            for result in results:
                if result["url"] not in cited_urls:
                    new_count += 1
                    print(f"NEW: [{result['year'] or '????'}] {result['title']}")
                    print(f"     {result['url']}")
        if index < len(queries) - 1:
            time.sleep(3)

    if len(failures) == len(queries) and offline_failures == len(queries):
        print("warning: arXiv unreachable (no network); snapshot skipped, flag accepted", file=sys.stderr)
        return 0

    snapshot_dir = root / SNAPSHOT_DIR_REL
    snapshot_dir.mkdir(parents=True, exist_ok=True)
    snapshot_path = snapshot_dir / f"harness-lit-{snapshot['date']}.json"
    write_atomic(snapshot_path, json.dumps(snapshot, indent=2) + "\n")
    print(
        f"[OK] snapshot written: {snapshot_path.relative_to(root).as_posix()} "
        f"({new_count} uncited paper(s))."
    )

    if failures:
        for line in failures:
            print(line, file=sys.stderr)
        if len(failures) == len(queries):
            print("error: all arXiv queries failed", file=sys.stderr)
            return 1
        print(f"warning: {len(failures)} of {len(queries)} queries failed", file=sys.stderr)
    return 0


# ── Main ───────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Verify docs/research/harness-techniques.json evidence and render "
            "docs/research/harness-techniques.md."
        )
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the on-disk markdown differs from a fresh render",
    )
    parser.add_argument(
        "--search",
        action="store_true",
        help="query arXiv for each catalog search query and write a snapshot (network)",
    )
    args = parser.parse_args()

    root = find_repo_root()
    catalog = load_catalog(root)

    if args.search:
        return command_search(root, catalog)
    return command_render(root, check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
